# -*- coding: utf-8 -*-
"""
Patient Q&A library content (English + Arabic).
Each item becomes its own page: learn/<slug>.html and ar/learn/<slug>.html.
Edit text here, then run:  python3 build.py

Fields
  slug     page address (lowercase-with-dashes)
  cat      category key (see CATEGORIES)
  q        question  {en, ar}
  short    one- or two-sentence answer shown first  {en, ar}
  body     list of paragraphs  {en: [...], ar: [...]}
  bullets  optional list of points  {en: [...], ar: [...]}
  see      related slugs
  src      source keys (see SOURCES)
"""

UPDATED = "2026-10-02"

CATEGORIES = [
    ("basics",    {"en": "The basics",            "ar": "الأساسيات"}),
    ("tests",     {"en": "Symptoms and tests",    "ar": "الأعراض والفحوص"}),
    ("living",    {"en": "Daily life",            "ar": "الحياة اليومية"}),
    ("treatment", {"en": "Treatment",             "ar": "العلاج"}),
    ("risks",     {"en": "Risks and follow-up",   "ar": "المخاطر والمتابعة"}),
    ("groups",    {"en": "Special situations",    "ar": "حالات خاصة"}),
]

SOURCES = {
    # key: (citation, link)
    "easl2024": ("EASL–EASD–EASO Clinical Practice Guidelines on the management of MASLD. J Hepatol 2024;81:492–542.", "https://doi.org/10.1016/j.jhep.2024.04.031"),
    "aasld2023": ("Rinella ME, et al. AASLD Practice Guidance on the clinical assessment and management of NAFLD. Hepatology 2023;77:1797–835.", "https://doi.org/10.1097/HEP.0000000000000323"),
    "delphi2023": ("Rinella ME, et al. A multisociety Delphi consensus statement on new fatty liver disease nomenclature. J Hepatol 2023;79:1542–56.", "https://doi.org/10.1016/j.jhep.2023.06.003"),
    "saudi2026": ("Abaalkhail F, et al. MASLD management in Saudi Arabia: a modified Delphi-based adaptation of international standards. Saudi J Gastroenterol 2026;32(2):104–20.", "https://doi.org/10.4103/sjg.sjg_199_25"),
    "global2025": ("Younossi ZM, et al. Global consensus recommendations for MASLD and MASH. Gastroenterology 2025;169(5):1017–32.", "https://doi.org/10.1053/j.gastro.2025.02.044"),
    "global2026": ("Younossi ZM, et al. Updated global consensus recommendations for risk stratification, treatment initiation, and response monitoring in MASLD. Clin Gastroenterol Hepatol 2026;24(9):2333–47.", "https://doi.org/10.1016/j.cgh.2026.03.030"),
    "riazi2022": ("Riazi K, et al. The prevalence and incidence of NAFLD worldwide: a systematic review and meta-analysis. Lancet Gastroenterol Hepatol 2022;7:851–61.", "https://doi.org/10.1016/S2468-1253(22)00165-0"),
    "nhsfibro": ("North Cumbria Integrated Care NHS Foundation Trust. What is a Fibroscan and why do I need it? Patient leaflet.", "https://www.ncic.nhs.uk/patients-visitors/patient-information-leaflets/fibroscan-ultrasound"),
    "blt2026": ("British Liver Trust. Two MASH treatments receive MHRA approval, 2026.", "https://britishlivertrust.org.uk/new-hope-for-people-living-with-mash-as-two-treatments-receive-mhra-approval/"),
    "ec2025": ("Madrigal Pharmaceuticals. European Commission approval of Rezdiffra, 19 August 2025.", "https://ir.madrigalpharma.com/node/16716"),
}

# Official organisations listed on the Q&A index page
ORGS = [
    ("EASL – European Association for the Study of the Liver", "https://easl.eu"),
    ("AASLD – American Association for the Study of Liver Diseases", "https://www.aasld.org"),
    ("AGA – American Gastroenterological Association", "https://gastro.org"),
    ("ACG – American College of Gastroenterology", "https://gi.org"),
    ("WGO – World Gastroenterology Organisation", "https://www.worldgastroenterology.org"),
    ("British Liver Trust (patient charity)", "https://britishlivertrust.org.uk"),
    ("American Liver Foundation (patient charity)", "https://liverfoundation.org"),
]

ITEMS = [
# ---------------------------------------------------------------- BASICS
{
 "slug": "what-is-fatty-liver", "cat": "basics",
 "q": {"en": "What is fatty liver (MASLD)?", "ar": "ما هو الكبد الدهني (MASLD)؟"},
 "short": {"en": "Fatty liver means extra fat is stored inside the liver cells. When it is linked to weight, blood sugar, blood pressure or blood fats, doctors call it MASLD.",
           "ar": "الكبد الدهني يعني تراكم دهون زائدة داخل خلايا الكبد. وعندما يرتبط بالوزن أو سكر الدم أو ضغط الدم أو دهون الدم، يسمّيه الأطباء MASLD."},
 "body": {"en": ["A healthy liver holds a little fat. When fat makes up more than about 5% of the liver, it is called steatosis, or fatty liver.",
                 "MASLD stands for metabolic dysfunction-associated steatotic liver disease. \"Metabolic\" means it comes with problems such as overweight, diabetes, high blood pressure or high triglycerides.",
                 "It is the most common liver condition in the world. Most people have no symptoms, so it is often found by chance on a blood test or ultrasound."],
          "ar": ["يحتوي الكبد السليم على قليل من الدهون. وعندما تزيد الدهون على نحو 5% من الكبد يسمّى ذلك تشحّم الكبد أو الكبد الدهني.",
                 "MASLD اختصار لعبارة: مرض الكبد الدهني المرتبط بالخلل الأيضي. وكلمة \"أيضي\" تعني أنه يأتي مع مشكلات مثل الوزن الزائد أو السكري أو ارتفاع ضغط الدم أو ارتفاع الدهون الثلاثية.",
                 "وهو أكثر أمراض الكبد شيوعًا في العالم. معظم المصابين لا يشعرون بأعراض، لذلك يُكتشف غالبًا بالصدفة في تحليل دم أو أشعة صوتية."]},
 "see": ["what-is-mash", "name-change-nafld-masld", "is-fatty-liver-serious"],
 "src": ["delphi2023", "easl2024"],
},
{
 "slug": "name-change-nafld-masld", "cat": "basics",
 "q": {"en": "Why did the name change from NAFLD to MASLD?", "ar": "لماذا تغيّر الاسم من NAFLD إلى MASLD؟"},
 "short": {"en": "In 2023, liver societies changed the name to describe the real cause, metabolic problems, and to remove words that felt judgemental.",
           "ar": "في عام 2023 غيّرت جمعيات الكبد الاسم ليصف السبب الحقيقي، وهو الخلل الأيضي، وليتخلّص من كلمات قد تبدو جارحة."},
 "body": {"en": ["The old name, NAFLD (non-alcoholic fatty liver disease), described the disease by what it is not. Many patients also found the words \"alcoholic\" and \"fatty\" stigmatising.",
                 "The new umbrella name is steatotic liver disease (SLD). Under it sit MASLD (metabolic), MetALD (metabolic plus moderate alcohol), and ALD (alcohol-related).",
                 "Almost everyone who had NAFLD now has MASLD. Research done under the old name still applies."],
          "ar": ["كان الاسم القديم NAFLD (مرض الكبد الدهني غير الكحولي) يصف المرض بما ليس هو. كما وجد كثير من المرضى كلمتي \"كحولي\" و\"دهني\" مسيئتين.",
                 "الاسم الجامع الجديد هو مرض الكبد التشحّمي (SLD)، ويندرج تحته: MASLD (الأيضي)، وMetALD (الأيضي مع كحول بكمية متوسطة)، وALD (المرتبط بالكحول).",
                 "تقريبًا كل من كان مشخّصًا بـ NAFLD أصبح مشخّصًا بـ MASLD، والأبحاث التي أُجريت تحت الاسم القديم ما زالت صالحة."]},
 "see": ["what-is-fatty-liver", "alcohol-and-fatty-liver"],
 "src": ["delphi2023"],
},
{
 "slug": "what-is-mash", "cat": "basics",
 "q": {"en": "What is MASH, and how is it different?", "ar": "ما هو MASH، وما الفرق بينه وبين MASLD؟"},
 "short": {"en": "MASH is the active, inflamed form of MASLD. The fat is now harming liver cells, and over years this can cause scarring.",
           "ar": "MASH هو الشكل النشط الملتهب من MASLD، حيث تبدأ الدهون بإيذاء خلايا الكبد، وقد يؤدي ذلك مع السنين إلى التندّب."},
 "body": {"en": ["Most people with MASLD have fat alone. In some, the fat triggers inflammation and cell injury. This is MASH: metabolic dysfunction-associated steatohepatitis (old name: NASH).",
                 "MASH matters because it can lead to fibrosis (scarring). Scarring is graded from F0 (none) to F4 (cirrhosis).",
                 "You cannot tell MASLD from MASH by symptoms. Blood-test scores and liver stiffness scans help doctors judge the risk."],
          "ar": ["معظم مرضى MASLD لديهم دهون فقط. لكن لدى بعضهم تسبّب الدهون التهابًا وإصابة في الخلايا، وهذا هو MASH: التهاب الكبد الدهني المرتبط بالخلل الأيضي (اسمه القديم NASH).",
                 "تكمن أهمية MASH في أنه قد يؤدي إلى التليّف (التندّب)، ويُصنّف التليّف من F0 (لا يوجد) إلى F4 (التشمّع).",
                 "لا يمكن التفريق بين MASLD وMASH من الأعراض. تساعد مؤشرات تحليل الدم وفحوص صلابة الكبد الأطباء على تقدير الخطر."]},
 "see": ["what-is-fatty-liver", "cirrhosis-and-cancer", "what-is-fib4"],
 "src": ["delphi2023", "easl2024"],
},
{
 "slug": "how-common", "cat": "basics",
 "q": {"en": "How common is fatty liver?", "ar": "ما مدى انتشار الكبد الدهني؟"},
 "short": {"en": "Very common. About 1 in 3 adults worldwide has fatty liver, and the number is higher in people with diabetes or obesity.",
           "ar": "شائع جدًا. نحو بالغ من كل ثلاثة حول العالم لديه كبد دهني، والنسبة أعلى لدى مرضى السكري والسمنة."},
 "body": {"en": ["A large review of studies from around the world found fatty liver in about a third of adults.",
                 "Rates are high in the Middle East, where obesity and type 2 diabetes are common. More than half of people with type 2 diabetes have fatty liver.",
                 "Being common does not mean it is harmless. Only some people develop serious scarring, and finding them early is the goal."],
          "ar": ["وجدت مراجعة كبيرة لدراسات من أنحاء العالم أن نحو ثلث البالغين لديهم كبد دهني.",
                 "النسب مرتفعة في الشرق الأوسط حيث تنتشر السمنة والسكري من النوع الثاني. وأكثر من نصف مرضى السكري من النوع الثاني لديهم كبد دهني.",
                 "انتشاره لا يعني أنه غير ضار. قلة فقط يصابون بتليّف شديد، والهدف هو اكتشافهم مبكرًا."]},
 "see": ["what-causes-it", "is-fatty-liver-serious"],
 "src": ["riazi2022", "easl2024", "saudi2026"],
},
{
 "slug": "what-causes-it", "cat": "basics",
 "q": {"en": "What causes fatty liver?", "ar": "ما أسباب الكبد الدهني؟"},
 "short": {"en": "Mostly insulin resistance: the body struggles to handle sugar and fat, so the liver stores the extra as fat.",
           "ar": "السبب الرئيسي هو مقاومة الإنسولين: يعجز الجسم عن التعامل مع السكر والدهون جيدًا، فيخزّن الكبد الفائض على شكل دهون."},
 "bullets": {"en": ["Extra weight, especially around the waist", "Type 2 diabetes or prediabetes", "High blood pressure", "High triglycerides or low HDL (good) cholesterol", "Too many sugary drinks and processed foods", "Little physical activity", "Genes: fatty liver can run in families"],
             "ar": ["الوزن الزائد، خاصة حول الخصر", "السكري من النوع الثاني أو مرحلة ما قبل السكري", "ارتفاع ضغط الدم", "ارتفاع الدهون الثلاثية أو انخفاض الكوليسترول النافع HDL", "الإكثار من المشروبات السكرية والأطعمة المصنّعة", "قلة النشاط البدني", "الوراثة: قد يتكرر الكبد الدهني في العائلة"]},
 "body": {"en": ["Your doctor will also check for other causes, such as alcohol, some medicines, or viral hepatitis, because they need different care."],
          "ar": ["سيتحقق طبيبك أيضًا من الأسباب الأخرى مثل الكحول أو بعض الأدوية أو التهاب الكبد الفيروسي، لأنها تحتاج إلى رعاية مختلفة."]},
 "see": ["not-overweight", "what-to-eat", "exercise"],
 "src": ["easl2024", "delphi2023"],
},
{
 "slug": "is-fatty-liver-serious", "cat": "basics",
 "q": {"en": "Is fatty liver serious?", "ar": "هل الكبد الدهني خطير؟"},
 "short": {"en": "For most people it stays mild. But in some it leads to scarring, cirrhosis or liver cancer, and it raises the risk of heart disease in everyone.",
           "ar": "لدى معظم الناس يبقى بسيطًا، لكنه لدى بعضهم يؤدي إلى التليّف أو التشمّع أو سرطان الكبد، كما يرفع خطر أمراض القلب لدى الجميع."},
 "body": {"en": ["The most important sign of how serious it is, is the amount of scarring (fibrosis). Little or no scarring means a low risk of liver problems.",
                 "The good news: fat, inflammation and even early scarring can improve when you lose weight and treat diabetes and blood pressure."],
          "ar": ["أهم مؤشر على خطورته هو مقدار التندّب (التليّف). قلة التليّف أو غيابه تعني خطرًا منخفضًا لمشكلات الكبد.",
                 "والخبر الجيد: الدهون والالتهاب وحتى التليّف المبكر قد تتحسّن مع خسارة الوزن وعلاج السكري والضغط."]},
 "see": ["cirrhosis-and-cancer", "why-heart-matters", "how-much-weight"],
 "src": ["easl2024"],
},
# ---------------------------------------------------------------- TESTS
{
 "slug": "symptoms", "cat": "tests",
 "q": {"en": "Does fatty liver cause symptoms?", "ar": "هل يسبّب الكبد الدهني أعراضًا؟"},
 "short": {"en": "Usually not. Many people feel completely well, even when there is scarring.",
           "ar": "غالبًا لا. يشعر كثيرون بأنهم بصحة جيدة تمامًا، حتى مع وجود تليّف."},
 "body": {"en": ["Some people notice tiredness or a dull ache on the right side under the ribs.",
                 "Clear symptoms usually appear only in advanced cirrhosis. That is why people at risk should be checked, not wait for symptoms."],
          "ar": ["قد يلاحظ البعض تعبًا أو ألمًا خفيفًا في الجهة اليمنى تحت الأضلاع.",
                 "تظهر الأعراض الواضحة عادةً فقط في التشمّع المتقدّم، لذلك يجب فحص المعرّضين للخطر وعدم انتظار الأعراض."]},
 "bullets": {"en": ["Get urgent care for: vomiting blood, black stools, yellow eyes, confusion, or a fast-swelling belly."],
             "ar": ["اطلب رعاية عاجلة عند: قيء الدم، أو البراز الأسود، أو اصفرار العينين، أو الارتباك، أو تضخّم البطن السريع."]},
 "see": ["ultrasound-says-fatty", "what-is-fib4"],
 "src": ["easl2024"],
},
{
 "slug": "ultrasound-says-fatty", "cat": "tests",
 "q": {"en": "My ultrasound says \"fatty liver\". What now?", "ar": "تقرير الأشعة الصوتية يقول \"كبد دهني\". ماذا أفعل الآن؟"},
 "short": {"en": "Don't panic and don't ignore it. The next step is to find out if there is scarring, starting with a simple blood-test score called FIB-4.",
           "ar": "لا تقلق ولا تتجاهل الأمر. الخطوة التالية هي معرفة ما إذا كان هناك تليّف، بدءًا بحساب بسيط من تحليل الدم اسمه FIB-4."},
 "bullets": {"en": ["Ask your doctor to calculate your FIB-4 score", "Check blood sugar, blood pressure and cholesterol", "Tell your doctor how much alcohol you drink, honestly", "Start small lifestyle changes now"],
             "ar": ["اطلب من طبيبك حساب مؤشر FIB-4", "افحص السكر وضغط الدم والكوليسترول", "أخبر طبيبك بصدق عن كمية الكحول التي تتناولها إن وُجدت", "ابدأ الآن بتغييرات صغيرة في نمط حياتك"]},
 "body": {"en": ["An ultrasound shows fat but cannot measure scarring well. That is why the next tests matter more than the word \"fatty\" on the report."],
          "ar": ["تُظهر الأشعة الصوتية الدهون لكنها لا تقيس التليّف جيدًا، لذلك فالفحوص التالية أهم من كلمة \"دهني\" في التقرير."]},
 "see": ["what-is-fib4", "fibroscan", "how-much-weight"],
 "src": ["easl2024", "global2025", "saudi2026"],
},
{
 "slug": "liver-enzymes", "cat": "tests",
 "q": {"en": "What are liver enzymes (ALT and AST)?", "ar": "ما هي إنزيمات الكبد (ALT وAST)؟"},
 "short": {"en": "ALT and AST are proteins that leak into the blood when liver cells are irritated. They are clues, not a full answer.",
           "ar": "ALT وAST بروتينات تتسرّب إلى الدم عند تهيّج خلايا الكبد. هي مؤشرات وليست إجابة كاملة."},
 "body": {"en": ["Raised enzymes can be a sign of fatty liver, but many people with fatty liver, even with scarring, have normal enzymes.",
                 "So normal enzymes do not rule out liver disease. Doctors use them inside scores like FIB-4, together with age and platelets."],
          "ar": ["قد يكون ارتفاع الإنزيمات علامة على الكبد الدهني، لكن كثيرين من مرضى الكبد الدهني، حتى مع التليّف، تكون إنزيماتهم طبيعية.",
                 "لذلك فالإنزيمات الطبيعية لا تنفي مرض الكبد. يستخدمها الأطباء ضمن مؤشرات مثل FIB-4 مع العمر والصفائح الدموية."]},
 "see": ["what-is-fib4", "ultrasound-says-fatty"],
 "src": ["easl2024", "aasld2023"],
},
{
 "slug": "what-is-fib4", "cat": "tests",
 "q": {"en": "What is the FIB-4 score?", "ar": "ما هو مؤشر FIB-4؟"},
 "short": {"en": "FIB-4 is a free score calculated from your age and three routine blood results. It tells your doctor whether serious scarring is unlikely or needs a closer look.",
           "ar": "FIB-4 مؤشر مجاني يُحسب من عمرك وثلاث نتائج روتينية في تحليل الدم، ويخبر طبيبك إن كان التليّف الشديد غير مرجّح أو يحتاج إلى فحص أدق."},
 "body": {"en": ["It uses age, AST, ALT and platelet count. No extra test is needed if you already have these results.",
                 "A low score (below 1.3, or below 2.0 if you are 65 or older) means advanced scarring is unlikely. A higher score means the next step is a liver stiffness scan such as FibroScan.",
                 "FIB-4 is less reliable under age 35. It is a guide for your doctor, not a diagnosis."],
          "ar": ["يعتمد على العمر وAST وALT وعدد الصفائح الدموية، ولا يحتاج إلى فحص إضافي إذا كانت هذه النتائج متوفرة لديك.",
                 "النتيجة المنخفضة (أقل من 1.3، أو أقل من 2.0 لمن عمره 65 سنة فأكثر) تعني أن التليّف المتقدّم غير مرجّح. أما النتيجة الأعلى فتعني أن الخطوة التالية هي فحص صلابة الكبد مثل فيبروسكان.",
                 "مؤشر FIB-4 أقل دقة تحت سن 35، وهو دليل لطبيبك وليس تشخيصًا."]},
 "see": ["fibroscan", "liver-enzymes", "biopsy"],
 "src": ["easl2024", "saudi2026", "global2026"],
},
{
 "slug": "fibroscan", "cat": "tests",
 "q": {"en": "What is a FibroScan, and how do I prepare?", "ar": "ما هو فحص فيبروسكان، وكيف أستعد له؟"},
 "short": {"en": "FibroScan is a quick, painless scan that measures how stiff your liver is. Stiffer means more scarring.",
           "ar": "فيبروسكان فحص سريع غير مؤلم يقيس صلابة الكبد. كلما زادت الصلابة زاد التليّف."},
 "body": {"en": ["You lie on your back with your right arm raised. A probe on the skin sends a gentle pulse. It takes about 10 minutes and there are no needles.",
                 "Most centres ask you not to eat for about 3 hours before, because a recent meal can raise the reading. Wear clothes that let the doctor reach your right side.",
                 "The result has two numbers: stiffness in kPa (scarring) and CAP (fat). As a rough guide, below 8 kPa is reassuring and 12 kPa or more suggests advanced scarring."],
          "ar": ["تستلقي على ظهرك ويدك اليمنى مرفوعة، ويضع الطبيب مجسًّا على الجلد يرسل نبضة خفيفة. يستغرق نحو 10 دقائق دون أي إبر.",
                 "تطلب معظم المراكز عدم الأكل قبل الفحص بنحو 3 ساعات، لأن الوجبة الحديثة قد ترفع القراءة. البس ملابس تسمح بالوصول إلى جانبك الأيمن.",
                 "للنتيجة رقمان: الصلابة بوحدة كيلوباسكال (للتليّف) وCAP (للدهون). وكقاعدة تقريبية: أقل من 8 مطمئن، و12 فأكثر يشير إلى تليّف متقدّم."]},
 "see": ["what-is-fib4", "biopsy", "how-often-checked"],
 "src": ["easl2024", "nhsfibro", "saudi2026"],
},
{
 "slug": "biopsy", "cat": "tests",
 "q": {"en": "Do I need a liver biopsy?", "ar": "هل أحتاج إلى خزعة من الكبد؟"},
 "short": {"en": "Usually not. Today most people are assessed with blood-test scores and scans. A biopsy is kept for unclear cases.",
           "ar": "غالبًا لا. يُقيَّم معظم المرضى اليوم بمؤشرات تحليل الدم والفحوص الإشعاعية، وتُترك الخزعة للحالات غير الواضحة."},
 "body": {"en": ["A biopsy takes a tiny piece of liver with a needle. It gives detailed information but carries small risks such as pain or bleeding.",
                 "Your specialist may suggest one if test results disagree, if another liver disease is suspected, or for a clinical trial."],
          "ar": ["الخزعة تأخذ قطعة صغيرة جدًا من الكبد بإبرة، وتعطي معلومات مفصّلة لكنها تحمل مخاطر بسيطة مثل الألم أو النزيف.",
                 "قد يقترحها أخصائي الكبد إذا تعارضت نتائج الفحوص، أو إذا اشتُبه في مرض كبدي آخر، أو للمشاركة في تجربة سريرية."]},
 "see": ["fibroscan", "what-is-fib4"],
 "src": ["easl2024", "aasld2023"],
},
# ---------------------------------------------------------------- LIVING
{
 "slug": "how-much-weight", "cat": "living",
 "q": {"en": "How much weight do I need to lose?", "ar": "كم يجب أن أخسر من وزني؟"},
 "short": {"en": "Even 5% of your body weight helps. Losing 7–10% can calm inflammation, and 10% or more can improve scarring.",
           "ar": "حتى 5% من وزنك تفيد. خسارة 7–10% قد تهدّئ الالتهاب، و10% أو أكثر قد تحسّن التليّف."},
 "body": {"en": ["For someone who weighs 100 kg, 5% is 5 kg and 10% is 10 kg.",
                 "Slow and steady is best: about 0.5 to 1 kg a week. Very fast weight loss is not better for the liver.",
                 "If you are not overweight, a smaller loss of 3–5% plus more activity can still help."],
          "ar": ["لمن يزن 100 كيلوغرام: 5% تعني 5 كيلوغرامات، و10% تعني 10 كيلوغرامات.",
                 "الأفضل هو النزول التدريجي الثابت: نحو نصف كيلو إلى كيلو أسبوعيًا. النزول السريع جدًا ليس أفضل للكبد.",
                 "إن لم يكن وزنك زائدًا، فخسارة أقل (3–5%) مع نشاط أكبر قد تفيد أيضًا."]},
 "see": ["what-to-eat", "exercise", "not-overweight"],
 "src": ["easl2024", "global2025"],
},
{
 "slug": "what-to-eat", "cat": "living",
 "q": {"en": "What should I eat?", "ar": "ماذا آكل؟"},
 "short": {"en": "A Mediterranean-style diet works best: lots of vegetables, legumes, whole grains, fish and olive oil, with fewer sugary and processed foods.",
           "ar": "النظام الغذائي على طريقة حوض المتوسط هو الأفضل: كثير من الخضروات والبقوليات والحبوب الكاملة والسمك وزيت الزيتون، مع تقليل السكريات والأطعمة المصنّعة."},
 "bullets": {"en": ["Fill half your plate with vegetables", "Choose brown bread, bulgur or brown rice over white", "Eat fish twice a week; beans and lentils often", "Use olive oil instead of ghee or butter", "Cut sugary drinks, sweets and fried food"],
             "ar": ["املأ نصف طبقك بالخضروات", "اختر الخبز الأسمر أو البرغل أو الأرز البني بدل الأبيض", "تناول السمك مرتين أسبوعيًا، والفول والعدس كثيرًا", "استخدم زيت الزيتون بدل السمن أو الزبدة", "قلّل المشروبات السكرية والحلويات والمقليات"]},
 "body": {"en": ["No single \"liver diet\" or special food cures fatty liver. The overall pattern, kept up for years, is what counts."],
          "ar": ["لا يوجد \"رجيم للكبد\" أو طعام خاص يعالج الكبد الدهني. المهم هو النمط الغذائي العام والاستمرار عليه لسنوات."]},
 "see": ["drinks", "how-much-weight", "ramadan"],
 "src": ["easl2024"],
},
{
 "slug": "drinks", "cat": "living",
 "q": {"en": "Which drinks are good or bad for my liver?", "ar": "ما المشروبات المفيدة أو الضارة لكبدي؟"},
 "short": {"en": "Water is best. Plain coffee may even help the liver. Sugary drinks and packaged juices are among the worst.",
           "ar": "الماء هو الأفضل، والقهوة السادة قد تفيد الكبد. أما المشروبات السكرية والعصائر المعلّبة فمن أسوأ الخيارات."},
 "bullets": {"en": ["Good: water, plain coffee, tea without sugar, laban", "Limit: fresh juice (eat the whole fruit instead)", "Avoid: soft drinks, energy drinks, sweetened juices, sweet tea and coffee drinks", "Alcohol: the less the better"],
             "ar": ["مفيد: الماء، والقهوة السادة، والشاي بلا سكر، واللبن", "قلّل: العصير الطازج (تناول الفاكهة كاملة بدلًا منه)", "تجنّب: المشروبات الغازية، ومشروبات الطاقة، والعصائر المحلّاة، والشاي والقهوة المحلّاة", "الكحول: كلما قلّ كان أفضل"]},
 "body": {"en": ["Sugary drinks are high in fructose, which the liver turns into fat easily. Swapping them for water is one of the simplest changes you can make."],
          "ar": ["المشروبات السكرية غنية بالفركتوز الذي يحوّله الكبد إلى دهون بسهولة، واستبدالها بالماء من أبسط التغييرات التي يمكنك القيام بها."]},
 "see": ["what-to-eat", "alcohol-and-fatty-liver"],
 "src": ["easl2024"],
},
{
 "slug": "exercise", "cat": "living",
 "q": {"en": "What exercise helps fatty liver?", "ar": "ما الرياضة التي تفيد الكبد الدهني؟"},
 "short": {"en": "Any activity you can keep doing. Aim for 150 minutes a week of brisk walking or similar, plus some strength exercise.",
           "ar": "أي نشاط تستطيع الاستمرار عليه. استهدف 150 دقيقة أسبوعيًا من المشي السريع أو ما يشابهه، مع بعض تمارين القوة."},
 "body": {"en": ["Exercise lowers liver fat even if your weight does not change much.",
                 "Start small, for example 10 minutes a day, and build up. In hot weather, walk early, late, or indoors.",
                 "Add strength exercise twice a week, such as light weights, resistance bands or body-weight moves."],
          "ar": ["الرياضة تخفض دهون الكبد حتى لو لم يتغيّر وزنك كثيرًا.",
                 "ابدأ بالقليل، مثل 10 دقائق يوميًا، ثم زِد تدريجيًا. في الطقس الحار امشِ صباحًا باكرًا أو مساءً أو في مكان مغلق.",
                 "أضف تمارين القوة مرتين أسبوعيًا، مثل الأوزان الخفيفة أو أحزمة المقاومة أو تمارين وزن الجسم."]},
 "see": ["how-much-weight", "what-to-eat"],
 "src": ["easl2024", "global2025"],
},
{
 "slug": "ramadan", "cat": "living",
 "q": {"en": "Can I fast in Ramadan with fatty liver?", "ar": "هل يمكنني صيام رمضان مع الكبد الدهني؟"},
 "short": {"en": "Most people with fatty liver can fast safely. Check with your doctor first if you have diabetes, cirrhosis or take several medicines.",
           "ar": "يستطيع معظم مرضى الكبد الدهني الصيام بأمان. استشر طبيبك أولًا إن كنت مصابًا بالسكري أو التشمّع أو تتناول أدوية متعددة."},
 "body": {"en": ["Ramadan can help weight loss if iftar and suhoor are planned. Problems usually come from large, sweet, fried meals at night.",
                 "People with advanced cirrhosis may be advised not to fast. Diabetes medicines often need new doses or timing."],
          "ar": ["قد يساعد رمضان على خسارة الوزن إذا خُطّط للإفطار والسحور، وتأتي المشكلات عادةً من الوجبات الليلية الكبيرة والحلوة والمقلية.",
                 "قد يُنصح مرضى التشمّع المتقدّم بعدم الصيام، وتحتاج أدوية السكري غالبًا إلى تعديل الجرعات أو المواعيد."]},
 "see": ["what-to-eat", "drinks"],
 "src": ["easl2024"],
},
{
 "slug": "alcohol-and-fatty-liver", "cat": "living",
 "q": {"en": "Is alcohol safe with fatty liver?", "ar": "هل الكحول آمن مع الكبد الدهني؟"},
 "short": {"en": "No amount is proven safe. Alcohol adds to the damage from fat, so less is better and none is best if there is scarring.",
           "ar": "لا توجد كمية ثبت أنها آمنة. الكحول يضيف إلى ضرر الدهون، فكلما قلّ كان أفضل، والامتناع هو الأفضل عند وجود تليّف."},
 "body": {"en": ["When metabolic risk and moderate drinking come together, doctors call it MetALD. The liver is hit from two sides and damage can be faster.",
                 "If you have advanced fibrosis or cirrhosis, stop alcohol completely. Be open with your doctor about how much you drink."],
          "ar": ["عندما تجتمع عوامل الخطر الأيضية مع شرب الكحول بكمية متوسطة يسمّيها الأطباء MetALD، حيث يتعرّض الكبد للضرر من جهتين وقد يكون الضرر أسرع.",
                 "إن كان لديك تليّف متقدّم أو تشمّع فامتنع عن الكحول تمامًا، وكن صريحًا مع طبيبك بشأن الكمية التي تشربها."]},
 "see": ["name-change-nafld-masld", "drinks"],
 "src": ["easl2024", "delphi2023"],
},
{
 "slug": "herbs-and-supplements", "cat": "living",
 "q": {"en": "Do herbs, \"detox\" or supplements help?", "ar": "هل تفيد الأعشاب أو \"تنظيف الكبد\" أو المكمّلات؟"},
 "short": {"en": "No herb, detox or supplement is proven to treat fatty liver. Some herbal products can even harm the liver.",
           "ar": "لا توجد أعشاب أو برامج \"تنظيف\" أو مكمّلات ثبت أنها تعالج الكبد الدهني، وبعض المنتجات العشبية قد تضرّ الكبد."},
 "body": {"en": ["The liver cleans itself. \"Liver cleanse\" products are not needed and can waste money.",
                 "Concentrated herbal extracts and some body-building supplements have caused liver injury. Always tell your doctor about anything you take, including herbs."],
          "ar": ["الكبد ينظّف نفسه بنفسه، ومنتجات \"تنظيف الكبد\" غير ضرورية وقد تكون إهدارًا للمال.",
                 "تسبّبت بعض المستخلصات العشبية المركّزة وبعض مكمّلات بناء العضلات في إصابات للكبد. أخبر طبيبك دائمًا بكل ما تتناوله، بما في ذلك الأعشاب."]},
 "see": ["is-there-a-medicine", "what-to-eat"],
 "src": ["easl2024", "global2025"],
},
# ---------------------------------------------------------------- TREATMENT
{
 "slug": "is-there-a-medicine", "cat": "treatment",
 "q": {"en": "Is there a medicine for fatty liver?", "ar": "هل يوجد دواء للكبد الدهني؟"},
 "short": {"en": "Yes, for some people. Two medicines are now approved in several countries for MASH with moderate or advanced scarring. They work alongside lifestyle change, not instead of it.",
           "ar": "نعم، لبعض المرضى. يوجد اليوم دواءان معتمدان في عدة دول لالتهاب الكبد الدهني مع تليّف متوسط أو متقدّم، ويعملان إلى جانب تغيير نمط الحياة لا بديلًا عنه."},
 "body": {"en": ["One is a daily tablet that helps the liver burn fat. The other is a weekly injection from the GLP-1 family that also lowers weight.",
                 "They are for adults with MASH and stage F2–F3 fibrosis, without cirrhosis. People with only simple fatty liver usually do not need them.",
                 "Medicines for diabetes and weight, such as GLP-1 injections, can also help the liver. Your doctor will decide what fits you, and what is available in your country."],
          "ar": ["أحدهما قرص يومي يساعد الكبد على حرق الدهون، والآخر حقنة أسبوعية من عائلة GLP-1 تخفّض الوزن أيضًا.",
                 "وهما للبالغين المصابين بالتهاب الكبد الدهني مع تليّف في المرحلة F2–F3 دون تشمّع. أما من لديهم دهون بسيطة فقط فلا يحتاجون إليهما عادةً.",
                 "كما أن أدوية السكري والوزن، مثل حقن GLP-1، قد تفيد الكبد أيضًا. وسيحدّد طبيبك ما يناسبك وما هو متاح في بلدك."]},
 "see": ["statins", "weight-loss-surgery", "herbs-and-supplements"],
 "src": ["easl2024", "ec2025", "blt2026", "global2026"],
},
{
 "slug": "statins", "cat": "treatment",
 "q": {"en": "Are statins (cholesterol pills) safe for my liver?", "ar": "هل الستاتينات (أدوية الكوليسترول) آمنة على كبدي؟"},
 "short": {"en": "Yes. Statins are safe in fatty liver and protect your heart. Do not stop them because of fatty liver or mildly raised enzymes.",
           "ar": "نعم. الستاتينات آمنة مع الكبد الدهني وتحمي قلبك. لا توقفها بسبب الكبد الدهني أو الارتفاع البسيط في الإنزيمات."},
 "body": {"en": ["Many people are wrongly told to stop statins when they have fatty liver. Guidelines say they are safe, including in people with compensated cirrhosis.",
                 "Because heart disease is the main danger in fatty liver, statins are often one of the most helpful medicines you can take."],
          "ar": ["يُنصح كثيرون خطأً بإيقاف الستاتينات عند وجود كبد دهني، بينما تقول الإرشادات إنها آمنة، حتى لدى مرضى التشمّع المعاوض.",
                 "ولأن أمراض القلب هي الخطر الأكبر مع الكبد الدهني، فالستاتينات غالبًا من أكثر الأدوية فائدة لك."]},
 "see": ["why-heart-matters", "is-there-a-medicine"],
 "src": ["easl2024", "aasld2023"],
},
{
 "slug": "weight-loss-surgery", "cat": "treatment",
 "q": {"en": "Does weight-loss surgery help the liver?", "ar": "هل تفيد جراحة السمنة الكبد؟"},
 "short": {"en": "Yes. For people with obesity who qualify for surgery, it can clear MASH and improve scarring.",
           "ar": "نعم. لمن يعانون السمنة وتنطبق عليهم شروط الجراحة، قد تزيل التهاب الكبد الدهني وتحسّن التليّف."},
 "body": {"en": ["Your liver should be checked before surgery. If there is cirrhosis, surgery is riskier and should be done in a specialist centre.",
                 "Endoscopic options, such as a gastric balloon or endoscopic sleeve, are less invasive. Their liver benefits look promising but are less proven."],
          "ar": ["يجب فحص الكبد قبل الجراحة، فوجود التشمّع يجعلها أكثر خطورة ويستلزم إجراءها في مركز متخصص.",
                 "الخيارات التنظيرية مثل بالون المعدة أو التكميم بالمنظار أقل تدخّلًا، وفوائدها للكبد واعدة لكنها أقل إثباتًا."]},
 "see": ["how-much-weight", "is-there-a-medicine"],
 "src": ["easl2024", "saudi2026"],
},
# ---------------------------------------------------------------- RISKS
{
 "slug": "cirrhosis-and-cancer", "cat": "risks",
 "q": {"en": "Can fatty liver turn into cirrhosis or cancer?", "ar": "هل يمكن أن يتحوّل الكبد الدهني إلى تشمّع أو سرطان؟"},
 "short": {"en": "It can, in a small share of people, usually over many years. The risk is mainly in people who already have advanced scarring.",
           "ar": "نعم لدى نسبة صغيرة من المرضى، وعادةً على مدى سنوات طويلة. ويتركّز الخطر أساسًا لدى من لديهم تليّف متقدّم."},
 "body": {"en": ["Cirrhosis means the liver is badly scarred. It can lead to fluid in the belly, bleeding, confusion and liver cancer.",
                 "People with cirrhosis need a liver ultrasound about every 6 months to find cancer early, when it is easier to treat.",
                 "Treating the cause early, by losing weight, controlling diabetes and avoiding alcohol, lowers the risk."],
          "ar": ["التشمّع يعني تندّبًا شديدًا في الكبد، وقد يؤدي إلى تجمّع السوائل في البطن أو النزيف أو الارتباك أو سرطان الكبد.",
                 "يحتاج مرضى التشمّع إلى أشعة صوتية للكبد كل 6 أشهر تقريبًا لاكتشاف السرطان مبكرًا عندما يكون علاجه أسهل.",
                 "علاج السبب مبكرًا، بخسارة الوزن وضبط السكري وتجنّب الكحول، يقلّل الخطر."]},
 "see": ["is-fatty-liver-serious", "how-often-checked"],
 "src": ["easl2024"],
},
{
 "slug": "why-heart-matters", "cat": "risks",
 "q": {"en": "Why does my heart matter if I have fatty liver?", "ar": "لماذا يهمّ قلبي إذا كان لدي كبد دهني؟"},
 "short": {"en": "Because heart disease, not liver disease, is the most common cause of death in people with fatty liver.",
           "ar": "لأن أمراض القلب، لا أمراض الكبد، هي السبب الأكثر شيوعًا للوفاة لدى مرضى الكبد الدهني."},
 "bullets": {"en": ["Know your blood pressure, sugar (HbA1c) and cholesterol numbers", "Take your heart and diabetes medicines as prescribed", "Stop smoking", "Move more every day"],
             "ar": ["اعرف أرقام ضغط دمك وسكرك (السكر التراكمي) والكوليسترول", "تناول أدوية القلب والسكري كما وُصفت لك", "أقلع عن التدخين", "تحرّك أكثر كل يوم"]},
 "body": {"en": ["Fatty liver and heart disease share the same roots. Looking after one helps the other."],
          "ar": ["للكبد الدهني وأمراض القلب الجذور نفسها، والعناية بأحدهما تفيد الآخر."]},
 "see": ["statins", "exercise"],
 "src": ["easl2024"],
},
{
 "slug": "how-often-checked", "cat": "risks",
 "q": {"en": "How often should I be checked?", "ar": "كم مرة يجب أن أُفحص؟"},
 "short": {"en": "It depends on your scarring stage. Low-risk people are usually re-checked every 1 to 3 years; people with more scarring are seen more often.",
           "ar": "يعتمد ذلك على مرحلة التليّف. يُعاد فحص منخفضي الخطر عادةً كل سنة إلى ثلاث سنوات، ويُتابع من لديهم تليّف أكبر بشكل أقرب."},
 "bullets": {"en": ["Low FIB-4: repeat FIB-4 every 1–3 years with your family doctor", "Higher scores: follow-up with a liver specialist and repeat stiffness scans", "Cirrhosis: ultrasound about every 6 months for cancer screening"],
             "ar": ["مؤشر FIB-4 منخفض: أعد حسابه كل سنة إلى ثلاث سنوات مع طبيب الأسرة", "نتائج أعلى: متابعة مع أخصائي الكبد وإعادة فحص الصلابة", "التشمّع: أشعة صوتية كل 6 أشهر تقريبًا للكشف عن السرطان"]},
 "body": {"en": ["Keep a copy of your results so you can see the trend over time."],
          "ar": ["احتفظ بنسخة من نتائجك لتتابع تطوّرها مع الوقت."]},
 "see": ["what-is-fib4", "fibroscan", "cirrhosis-and-cancer"],
 "src": ["easl2024", "global2026"],
},
# ---------------------------------------------------------------- GROUPS
{
 "slug": "not-overweight", "cat": "groups",
 "q": {"en": "I'm not overweight. Can I still have fatty liver?", "ar": "وزني ليس زائدًا. هل يمكن أن يكون لدي كبد دهني؟"},
 "short": {"en": "Yes. This is called lean MASLD. It is linked to belly fat, insulin resistance and genes, and it needs the same checks.",
           "ar": "نعم، ويسمّى الكبد الدهني لدى النحفاء. وهو مرتبط بدهون البطن ومقاومة الإنسولين والوراثة، ويحتاج إلى الفحوص نفسها."},
 "body": {"en": ["A normal weight on the scale can hide extra fat around the organs.",
                 "A smaller weight loss of 3–5%, more activity and less sugar can still help a lot."],
          "ar": ["قد يُخفي الوزن الطبيعي على الميزان دهونًا زائدة حول الأعضاء الداخلية.",
                 "خسارة وزن أقل (3–5%) مع نشاط أكبر وسكريات أقل قد تفيد كثيرًا."]},
 "see": ["what-causes-it", "how-much-weight"],
 "src": ["easl2024"],
},
{
 "slug": "children", "cat": "groups",
 "q": {"en": "Can children get fatty liver?", "ar": "هل يصاب الأطفال بالكبد الدهني؟"},
 "short": {"en": "Yes, especially children with obesity. It needs care from a paediatric specialist and the whole family's help.",
           "ar": "نعم، خاصة الأطفال المصابون بالسمنة، ويحتاج ذلك إلى رعاية أخصائي أطفال ومساعدة الأسرة كلها."},
 "body": {"en": ["Children's tests are different: adult scores like FIB-4 are not used for them.",
                 "Family changes work best: fewer sugary drinks at home, more active play, less screen time, and regular family meals."],
          "ar": ["فحوص الأطفال مختلفة، ولا تُستخدم لهم مؤشرات البالغين مثل FIB-4.",
                 "التغييرات على مستوى الأسرة هي الأنجح: مشروبات سكرية أقل في المنزل، ولعب أكثر نشاطًا، ووقت أقل أمام الشاشات، ووجبات عائلية منتظمة."]},
 "see": ["what-to-eat", "drinks"],
 "src": ["easl2024"],
},
{
 "slug": "pregnancy", "cat": "groups",
 "q": {"en": "What about fatty liver and pregnancy?", "ar": "ماذا عن الكبد الدهني والحمل؟"},
 "short": {"en": "Fatty liver raises the risk of diabetes and high blood pressure in pregnancy. Plan ahead with your doctor, ideally before you conceive.",
           "ar": "الكبد الدهني يزيد خطر سكري الحمل وارتفاع ضغط الدم أثناء الحمل. خطّطي مسبقًا مع طبيبك، ويفضّل قبل حدوث الحمل."},
 "body": {"en": ["Losing weight before pregnancy is helpful. During pregnancy, the aim is healthy eating and safe activity, not weight loss.",
                 "The new MASH medicines are not used in pregnancy. Tell your doctor if you are pregnant or planning to be."],
          "ar": ["خسارة الوزن قبل الحمل مفيدة، أما أثناء الحمل فالهدف هو التغذية الصحية والنشاط الآمن، لا إنقاص الوزن.",
                 "لا تُستخدم أدوية التهاب الكبد الدهني الجديدة أثناء الحمل. أخبري طبيبك إن كنتِ حاملًا أو تخطّطين للحمل."]},
 "see": ["is-there-a-medicine", "what-to-eat"],
 "src": ["easl2024"],
},
]
