# -*- coding: utf-8 -*-
"""Module 2: Choosing drug treatment for MASH. Same schema as content/modules.py."""

# New sources (checked on PubMed). Other keys come from learn.py, ref.py and modules.py.
SOURCES = {
    "sema2025": ("Bansal MB, et al. Semaglutide therapy for metabolic dysfunction-associated steatohepatitis: November 2025 updates to AASLD Practice Guidance. Hepatology 2026;83(5):1326–40.", "https://doi.org/10.1097/HEP.0000000000001608"),
}

MODULE = {
 "slug": "drug-treatment",
 "number": 2,
 "title": {"en": "Choosing drug treatment for MASH", "ar": "اختيار العلاج الدوائي لـ MASH"},
 "subtitle": {"en": "Who needs a drug, how resmetirom and semaglutide compare, and how to start, monitor and stop them safely.",
              "ar": "مَن يحتاج إلى دواء، وكيف يُقارَن الريسميتيروم بالسيماغلوتايد، وكيف نبدأ العلاج ونتابعه ونوقفه بأمان."},
 "minutes": 28,
 "audience": {"en": "Primary care physicians, internists, endocrinologists, gastroenterologists, residents",
              "ar": "أطباء الرعاية الأولية، وأطباء الباطنة، وأطباء الغدد الصماء، وأطباء الجهاز الهضمي، والأطباء المقيمون"},
 "objectives": [
  ("Identify adults with at-risk MASH (F2–F3, no cirrhosis) who are candidates for drug treatment, using non-invasive tests.", "تحديد البالغين المصابين بـ MASH عالي الخطورة (F2–F3 دون تشمّع) المرشّحين للعلاج الدوائي باستخدام الفحوص غير الجراحية."),
  ("Prescribe resmetirom safely: weight-based dose, CYP2C8 and statin interactions, thyroid checks and monitoring.", "وصف الريسميتيروم بأمان: الجرعة حسب الوزن، وتداخلات CYP2C8 والستاتينات، وفحص الغدة الدرقية، والمتابعة."),
  ("Prescribe semaglutide 2.4 mg for MASH, including titration, side effects, contraindications and muscle preservation.", "وصف السيماغلوتايد 2.4 ملغ لـ MASH، بما في ذلك رفع الجرعة التدريجي، والآثار الجانبية، وموانع الاستعمال، والحفاظ على الكتلة العضلية."),
  ("Compare guideline positions (EASL, AASLD, global, Saudi 2026) on other drugs, and judge response and futility.", "مقارنة مواقف الإرشادات (EASL وAASLD والإجماع العالمي والإجماع السعودي 2026) من الأدوية الأخرى، والحكم على الاستجابة وعدم الجدوى."),
 ],
 "blocks": [
  # 1 ---------------------------------------------------------------
  ("h2", ("Who needs drug treatment", "مَن يحتاج إلى علاج دوائي"), "who"),
  ("p", ("Drug treatment for metabolic dysfunction-associated steatotic liver disease (MASLD) targets one group: adults with steatohepatitis (MASH) and moderate to advanced fibrosis, stage F2–F3, without cirrhosis. Both licensed drugs were tested in this group, and both regulatory approvals in the US cover only MASH with F2–F3 [[resm2024,sema2025]]. People with steatosis alone or F0–F1 fibrosis need lifestyle care and treatment of their metabolic risk factors, not a liver drug.",
         "يستهدف العلاج الدوائي لمرض الكبد المتدهن المرتبط بخلل التمثيل الغذائي (MASLD) فئة واحدة: البالغين المصابين بالتهاب الكبد الدهني (MASH) مع تليّف متوسط إلى متقدّم في المرحلة F2–F3 دون تشمّع. فقد اختُبر الدواءان المرخّصان في هذه الفئة، ولا تشمل موافقتا الولايات المتحدة إلا MASH مع F2–F3 [[resm2024,sema2025]]. أما من لديهم تشحّم فقط أو تليّف F0–F1 فيحتاجون إلى رعاية نمط الحياة وعلاج عوامل الخطر الأيضية، لا إلى دواء للكبد.")),
  ("p", ("A biopsy is not needed. The US labels do not require one, and AASLD selects patients by non-invasive tests, preferably liver stiffness [[resm2024]]. The usual route is the two-step pathway from Module 1: FIB-4 first, then elastography. FIB-4 alone must not be used to rule a patient in or out of treatment [[sema2025]]. Image-based stiffness measured before treatment also gives a baseline for judging response later [[resm2024]].",
         "لا حاجة إلى خزعة، فالنشرات الأمريكية لا تشترطها، وتختار AASLD المرضى بالفحوص غير الجراحية، ويُفضَّل قياس صلابة الكبد [[resm2024]]. والطريق المعتاد هو المسار ذو الخطوتين في الوحدة 1: FIB-4 أولًا ثم قياس المرونة. ولا يجوز الاعتماد على FIB-4 وحده لقبول المريض للعلاج أو استبعاده [[sema2025]]. كما أن قياس الصلابة بالتصوير قبل العلاج يوفر خط أساس للحكم على الاستجابة لاحقًا [[resm2024]].")),
  ("p", ("Cirrhosis is excluded for now because no MASH drug has shown benefit at that stage. MAESTRO-NASH and ESSENCE enrolled F1B–F3 and F2–F3 patients respectively, and the long-term outcome phases of both trials are still running, as is an outcome trial of resmetirom in cirrhosis [[maestro,essence,easl2024]].",
         "يُستبعد التشمّع حاليًا لأنه لم يثبت أي دواء لـ MASH فائدة في هذه المرحلة. فقد شملت تجربة MAESTRO-NASH مرضى F1B–F3، وشملت ESSENCE مرضى F2–F3، وما زالت مراحل المآلات طويلة المدى في التجربتين جارية، وكذلك تجربة لمآلات الريسميتيروم في التشمّع [[maestro,essence,easl2024]].")),
  ("rec", ("No drug aimed at MASH can yet be advised for patients who already have cirrhosis.", "لا يمكن بعدُ التوصية بأي دواء موجّه لـ MASH لدى المرضى الذين وصلوا إلى التشمّع."), 5, "weak", "strong", "easl2024"),
  ("table", {"caption": ("Table 1. Non-invasive eligibility criteria in the AASLD updates", "الجدول 1. معايير الأهلية غير الجراحية في تحديثات AASLD"),
             "head": [("Test", "الفحص"), ("Treat (F2–F3 likely)", "عالِج (F2–F3 مرجّح)"), ("Specialist decision", "قرار المختص"), ("Do not start (cirrhosis likely)", "لا تبدأ (التشمّع مرجّح)")],
             "rows": [
              ["VCTE", "8–15 kPa", ("15–20 kPa, after a second test, imaging or platelet count excludes cirrhosis", "15–20 كيلوباسكال، بعد أن ينفي فحص ثانٍ أو التصوير أو عدد الصفائح وجود التشمّع"), ">20 kPa"],
              ["MRE", "3.1–4.4 kPa", ("4.4–5.0 kPa, same checks", "4.4–5.0 كيلوباسكال، بالضوابط نفسها"), ">5.0 kPa"],
              [("ELF (bands from the semaglutide update)", "ELF (الحدود من تحديث السيماغلوتايد)"), "9.2–10.5", "10.5–11.3", ">11.3"],
             ]}),
  ("p", ("The VCTE and ELF ranges roughly match the middle half of trial participants, so about half of biopsy-proven F2–F3 patients fall outside them [[resm2024,sema2025]]. The global consensus draws the lines differently: VCTE 8 to below 10 kPa needs a second test confirming F2; 10 to below 16 kPa is enough on its own; 16–20 kPa needs a second test excluding cirrhosis; above 20 kPa is a stop [[global2025]].",
         "تطابق نطاقات VCTE وELF تقريبًا النصف الأوسط من المشاركين في التجارب، لذا يقع نحو نصف مرضى F2–F3 المؤكدين بالخزعة خارجها [[resm2024,sema2025]]. ويرسم الإجماع العالمي الحدود بطريقة مختلفة: صلابة VCTE من 8 إلى أقل من 10 كيلوباسكال تحتاج إلى فحص ثانٍ يؤكد F2، ومن 10 إلى أقل من 16 تكفي وحدها، ومن 16 إلى 20 تحتاج إلى فحص ثانٍ ينفي التشمّع، وما فوق 20 يمنع العلاج [[global2025]].")),

  # 2 ---------------------------------------------------------------
  ("h2", ("Lifestyle stays the base", "نمط الحياة يبقى الأساس"), "lifestyle"),
  ("rec", ("Adults with MASLD and overweight should aim for lasting weight loss through diet and behaviour change: more than 5% to cut liver fat, 7–10% to reduce inflammation and more than 10% to improve fibrosis.", "ينبغي أن يسعى البالغون المصابون بـ MASLD وزيادة الوزن إلى خسارة دائمة للوزن عبر الغذاء وتعديل السلوك: أكثر من 5% لتقليل دهون الكبد، و7–10% لتخفيف الالتهاب، وأكثر من 10% لتحسين التليّف."), 2, "strong", "strong", "easl2024"),
  ("p", ("Every guidance document places drugs on top of lifestyle change and control of diabetes, blood pressure and lipids, never instead of them [[resm2024,sema2025]]. A prescription is a good moment to restate diet, activity and alcohol advice. Patients should also hear that treatment is long term: in the STEP trials, stopping semaglutide reversed the cardiometabolic gains [[sema2025]].",
         "تضع جميع وثائق الإرشاد الأدوية فوق تعديل نمط الحياة وضبط السكري والضغط والدهون، لا بديلًا عنها [[resm2024,sema2025]]. ووقت الوصف فرصة جيدة لتكرار نصائح الغذاء والنشاط والكحول. وينبغي أن يعرف المريض أن العلاج طويل الأمد، ففي تجارب STEP أدى إيقاف السيماغلوتايد إلى فقدان المكاسب القلبية الأيضية [[sema2025]].")),

  # 3 ---------------------------------------------------------------
  ("h2", ("Resmetirom", "الريسميتيروم"), "resmetirom"),
  ("p", ("Resmetirom is an oral, liver-directed agonist highly selective for the thyroid hormone receptor β1. Thyroid hormone action in the liver increases lipophagy and mitochondrial biogenesis and suppresses lipogenesis, which lowers liver fat [[easl2024]].",
         "الريسميتيروم منبّه فموي موجّه للكبد، عالي الانتقائية لمستقبل هرمون الغدة الدرقية β1. ويزيد تأثير هرمون الدرقية في الكبد من الالتهام الذاتي للدهون وتكوين الميتوكوندريا ويثبط تخليق الدهون، فتنخفض دهون الكبد [[easl2024]].")),
  ("p", ("In MAESTRO-NASH, 966 adults with biopsy-proven MASH (F1B–F3) received 80 mg, 100 mg or placebo daily. At 52 weeks, MASH resolved without fibrosis worsening in 25.9% (80 mg) and 29.9% (100 mg), against 9.7% on placebo. Fibrosis improved by at least one stage in 24.2% and 25.9%, against 14.2%. LDL cholesterol fell by 13.6–16.3% by week 24, and serious adverse events were similar across groups [[maestro]]. Weight and glucose control did not change [[easl2024]].",
         "في تجربة MAESTRO-NASH تلقّى 966 بالغًا مصابًا بـ MASH مؤكد بالخزعة (F1B–F3) جرعة 80 ملغ أو 100 ملغ أو دواءً وهميًا يوميًا. وبعد 52 أسبوعًا زال MASH دون تفاقم التليّف لدى 25.9% (80 ملغ) و29.9% (100 ملغ) مقابل 9.7% مع الدواء الوهمي، وتحسّن التليّف مرحلة على الأقل لدى 24.2% و25.9% مقابل 14.2%. وانخفض الكوليسترول الضار LDL بنسبة 13.6–16.3% بحلول الأسبوع 24، وتشابهت الأحداث الجانبية الخطيرة بين المجموعات [[maestro]]. ولم يتغيّر الوزن ولا ضبط السكر [[easl2024]].")),
  ("rec", ("Where the drug is approved locally, consider resmetirom as a MASH-directed treatment for adults with non-cirrhotic MASH and fibrosis of stage F2 or higher.", "حيث يكون الدواء معتمدًا محليًا، يُنظر في الريسميتيروم علاجًا موجّهًا لـ MASH لدى البالغين المصابين بـ MASH دون تشمّع مع تليّف في المرحلة F2 أو أعلى."), 2, "strong", "consensus", "easl2024"),
  ("rec", ("If approved locally, resmetirom may be considered in non-cirrhotic MASLD with documented advanced fibrosis, at-risk steatohepatitis with significant fibrosis, or non-invasive results that signal a risk of liver events.", "إذا كان معتمدًا محليًا، يمكن النظر في الريسميتيروم لمرضى MASLD دون تشمّع مع تليّف متقدّم موثّق، أو التهاب كبد دهني عالي الخطورة مع تليّف ملحوظ، أو نتائج غير جراحية تنذر بخطر مضاعفات كبدية."), 3, "open", "consensus", "easl2024"),
  ("p", ("Before starting, AASLD advises against resmetirom in cirrhosis, other active liver disease such as autoimmune hepatitis or primary biliary cholangitis, alcohol above 20 g/day for women or 30 g/day for men, untreated thyroid disease, and symptomatic gallstone disease such as acute cholecystitis. Check TSH at baseline or within the previous 6 months [[resm2024]].",
         "قبل البدء، لا توصي AASLD بالريسميتيروم في التشمّع، أو مرض كبدي نشط آخر مثل التهاب الكبد المناعي الذاتي أو التهاب الأقنية الصفراوية الأولي، أو تناول كحول يزيد على 20 غ/يوم للنساء أو 30 غ/يوم للرجال، أو مرض درقي غير معالَج، أو مرض حصى مرارية عرضي مثل التهاب المرارة الحاد. افحص TSH عند البدء أو خلال الأشهر الستة السابقة [[resm2024]].")),
  ("table", {"caption": ("Table 2. Prescribing resmetirom (AASLD 2024)", "الجدول 2. وصف الريسميتيروم (AASLD 2024)"),
             "head": [("Item", "البند"), ("Practical rule", "القاعدة العملية")],
             "rows": [
              [("Dose", "الجرعة"), ("80 mg once daily if <100 kg; 100 mg if ≥100 kg", "80 ملغ مرة يوميًا لمن وزنه <100 كغ، و100 ملغ لمن وزنه ≥100 كغ")],
              [("With a moderate CYP2C8 inhibitor (e.g. clopidogrel)", "مع مثبط متوسط لـ CYP2C8 (مثل الكلوبيدوغريل)"), ("60 mg if <100 kg; 80 mg if ≥100 kg", "60 ملغ لمن وزنه <100 كغ، و80 ملغ لمن وزنه ≥100 كغ")],
              [("Statin maximum", "الحد الأعلى للستاتين"), ("Rosuvastatin and simvastatin 20 mg/day; atorvastatin and pravastatin 40 mg/day; recheck lipids and keep CV targets", "روزوفاستاتين وسيمفاستاتين 20 ملغ/يوم؛ وأتورفاستاتين وبرافاستاتين 40 ملغ/يوم؛ أعد فحص الدهون وحافظ على الأهداف القلبية")],
              [("Thyroid", "الغدة الدرقية"), ("Correct thyroid dysfunction first; if on levothyroxine or known thyroid disease, TSH and free T4 every 3–6 months", "صحّح خلل الدرقية أولًا؛ ومع الليفوثيروكسين أو مرض درقي معروف: TSH وfree T4 كل 3–6 أشهر")],
              [("Liver panel", "تحاليل الكبد"), ("Baseline, then 3, 6 and 12 months; every 6 months after that is suggested", "عند البدء ثم بعد 3 و6 و12 شهرًا، ويُقترح كل 6 أشهر بعد ذلك")],
              [("Stop for liver injury", "الإيقاف لإصابة الكبد"), ("ALT or AST >5× ULN, or ALP >2× ULN, on 2 occasions; or bilirubin >2.5 mg/dL or INR >1.5 with raised enzymes", "ALT أو AST >5 أضعاف الحد الأعلى، أو ALP >ضعفي الحد الأعلى، في مناسبتين؛ أو بيليروبين >2.5 ملغ/دل أو INR >1.5 مع ارتفاع الإنزيمات")],
             ]}),
  ("p", ("Resmetirom is a substrate of CYP2C8 and of the transporters OATP1B1 and OATP1B3, which explains both the clopidogrel and the statin rules [[resm2024]]. Diarrhoea (24–34%) and nausea (12–22%) are the commonest side effects, usually starting within 12 weeks; diarrhoea lasted more than 4 weeks in about half of those affected. Symptomatic gallstone disease was more frequent, but past biliary colic is not a contraindication. Free T4 fell by 16–21% on average, and 1.8% needed new levothyroxine [[resm2024]].",
         "الريسميتيروم ركيزة لـ CYP2C8 ولناقلَي OATP1B1 وOATP1B3، وهذا يفسّر قاعدتي الكلوبيدوغريل والستاتين [[resm2024]]. والإسهال (24–34%) والغثيان (12–22%) أكثر الآثار الجانبية شيوعًا، ويبدآن عادة خلال 12 أسبوعًا، واستمر الإسهال أكثر من 4 أسابيع لدى نحو نصف من أصيبوا به. وكان مرض الحصى المرارية العرضي أكثر تكرارًا، لكن نوبات المغص المراري السابقة ليست مانعًا. وانخفض free T4 بنسبة 16–21% في المتوسط، واحتاج 1.8% إلى ليفوثيروكسين جديد [[resm2024]].")),
  ("aside", ("In MAESTRO-NASH, 49% of treated patients had a ≥25% fall in VCTE stiffness, yet only about a quarter improved on biopsy. Stiffness overestimates histological response [[resm2024]].",
             "في MAESTRO-NASH انخفضت صلابة VCTE بنسبة ≥25% لدى 49% من المعالَجين، بينما تحسّن نحو الربع فقط في الخزعة. أي أن الصلابة تبالغ في تقدير الاستجابة النسيجية [[resm2024]].")),
  ("p", ("Judge response at 12 months with the same test used at baseline. AASLD treats a fall in stiffness of at least 25% on VCTE or 20% on MRE, or normalisation of a raised ALT, as benefit: continue. A similar rise, or a steadily rising ALT, suggests failure: consider stopping. A fall in MRI-PDFF of less than 30% predicted a response rate no better than placebo. In between, decide with the patient; stable fibrosis may still be worthwhile in F3 [[resm2024]]. The global consensus sets the VCTE threshold at 30%, defines futility as worsening of two concordant tests, and warns against using ALT alone [[global2025]].",
         "قيّم الاستجابة بعد 12 شهرًا بالفحص نفسه المستخدم في البداية. تعدّ AASLD انخفاض الصلابة 25% على الأقل بـ VCTE أو 20% بـ MRE، أو عودة ALT المرتفع إلى الطبيعي، دليلًا على الفائدة فيستمر العلاج. أما ارتفاع مماثل أو ارتفاع مستمر في ALT فيشير إلى الفشل، فيُنظر في الإيقاف. وانخفاض MRI-PDFF بأقل من 30% تنبأ بمعدل استجابة لا يفوق الدواء الوهمي. وبين الحالتين يُتخذ القرار مع المريض، فثبات التليّف قد يكون مكسبًا في F3 [[resm2024]]. ويضع الإجماع العالمي حد VCTE عند 30%، ويعرّف عدم الجدوى بتدهور فحصين متوافقين، ويحذّر من الاعتماد على ALT وحده [[global2025]].")),
  ("rec", ("For patients on resmetirom, there are as yet no data on durability of benefit, prediction of individual response, liver outcomes or long-term safety.", "لا تتوفر بعدُ بيانات لدى مرضى الريسميتيروم عن استمرار الفائدة، أو التنبؤ بالاستجابة الفردية، أو المآلات الكبدية، أو السلامة طويلة المدى."), 5, None, "strong", "easl2024"),

  # 4 ---------------------------------------------------------------
  ("h2", ("Semaglutide 2.4 mg", "السيماغلوتايد 2.4 ملغ"), "semaglutide"),
  ("p", ("Semaglutide is a once-weekly GLP-1 receptor agonist with a half-life of about 5–7 days. Hepatocytes and stellate cells carry almost no GLP-1 receptors, so its liver benefit is thought to come indirectly, through weight loss, better glucose and lipid control and less systemic inflammation [[sema2025]].",
         "السيماغلوتايد منبّه أسبوعي لمستقبل GLP-1 يبلغ عمره النصفي نحو 5–7 أيام. ولا تكاد خلايا الكبد والخلايا النجمية تحمل مستقبلات GLP-1، لذا يُعتقد أن فائدته الكبدية غير مباشرة، عبر خسارة الوزن وتحسين ضبط السكر والدهون وتخفيف الالتهاب الجهازي [[sema2025]].")),
  ("p", ("ESSENCE randomised 1,197 adults with biopsy-proven MASH and F2–F3 fibrosis. In the planned week-72 analysis of the first 800, MASH resolved without fibrosis worsening in 62.9% on semaglutide against 34.3% on placebo, and fibrosis improved without MASH worsening in 36.8% against 22.4%. Weight fell by 10.5% against 2.0% [[essence]]. The US FDA granted accelerated approval for this indication in August 2025; final approval depends on outcome data expected from 2028 [[sema2025]].",
         "أدخلت تجربة ESSENCE بطريقة عشوائية 1,197 بالغًا مصابًا بـ MASH مؤكد بالخزعة مع تليّف F2–F3. وفي التحليل المخطط عند الأسبوع 72 لأول 800 مشارك، زال MASH دون تفاقم التليّف لدى 62.9% مع السيماغلوتايد مقابل 34.3% مع الدواء الوهمي، وتحسّن التليّف دون تفاقم MASH لدى 36.8% مقابل 22.4%، وانخفض الوزن بنسبة 10.5% مقابل 2.0% [[essence]]. ومنحت إدارة الغذاء والدواء الأمريكية موافقة معجّلة لهذا الاستخدام في أغسطس 2025، وتتوقف الموافقة النهائية على بيانات المآلات المتوقعة من 2028 [[sema2025]].")),
  ("p", ("The dose is built up from 0.25 mg to 2.4 mg weekly over 16 weeks [[saudi2026]]. Nausea (36.2% vs 13.2%), diarrhoea (26.9% vs 12.2%), constipation (22.2% vs 8.4%) and vomiting (18.6% vs 5.6%) were the main side effects, mostly mild and short-lived; stopping for adverse events was no more common than with placebo (2.6% vs 3.3%). Advise small, lower-fat meals, stopping eating when full, fluids and fibre. Slow the titration or reduce the dose if symptoms persist [[sema2025]].",
         "تُرفع الجرعة تدريجيًا من 0.25 ملغ إلى 2.4 ملغ أسبوعيًا خلال 16 أسبوعًا [[saudi2026]]. وكانت الآثار الجانبية الرئيسة الغثيان (36.2% مقابل 13.2%) والإسهال (26.9% مقابل 12.2%) والإمساك (22.2% مقابل 8.4%) والقيء (18.6% مقابل 5.6%)، ومعظمها خفيف وعابر، ولم يكن إيقاف العلاج بسبب الآثار الجانبية أكثر منه مع الدواء الوهمي (2.6% مقابل 3.3%). انصح بوجبات صغيرة قليلة الدهون، والتوقف عن الأكل عند الشبع، والسوائل، والألياف. وأبطئ رفع الجرعة أو خفّضها إذا استمرت الأعراض [[sema2025]].")),
  ("ul", [
   ("Contraindicated: personal or family history of medullary thyroid carcinoma or MEN2; severe gastroparesis. Do not start during active suicidal ideation [[sema2025]].", "موانع الاستعمال: تاريخ شخصي أو عائلي لسرطان الغدة الدرقية النخاعي أو MEN2، وخزل المعدة الشديد. ولا تبدأ العلاج أثناء وجود أفكار انتحارية نشطة [[sema2025]]."),
   ("Gallbladder: cholelithiasis 1.6% vs 0.7%; a meta-analysis of 76 trials showed a 37% higher risk of biliary disease. Past gallbladder disease calls for caution, not refusal [[sema2025]].", "المرارة: حصى المرارة 1.6% مقابل 0.7%، وأظهر تحليل تجميعي لـ 76 تجربة زيادة خطر أمراض القنوات الصفراوية بنسبة 37%. ويستدعي تاريخ مرض المرارة الحذر لا الرفض [[sema2025]]."),
   ("Pancreatitis: stop at once if suspected and do not restart after a confirmed episode [[sema2025]].", "التهاب البنكرياس: أوقف الدواء فورًا عند الاشتباه، ولا تُعِده بعد نوبة مؤكدة [[sema2025]]."),
   ("Kidneys and glucose: check creatinine during titration if vomiting or diarrhoea; lower insulin or sulfonylurea doses to avoid hypoglycaemia [[sema2025]].", "الكلى والسكر: افحص الكرياتينين أثناء رفع الجرعة عند القيء أو الإسهال، وخفّض جرعات الإنسولين أو السلفونيل يوريا لتجنّب هبوط السكر [[sema2025]]."),
   ("Eyes: in type 2 diabetes, arrange a retinal exam before starting if none in the past 12 months [[sema2025]].", "العيون: في السكري من النوع الثاني رتّب فحصًا لقاع العين قبل البدء إن لم يُجرَ خلال 12 شهرًا [[sema2025]]."),
  ]),
  ("aside", ("In a DEXA subgroup of ESSENCE, lean mass fell by 6.92 kg on semaglutide against 1.48 kg on placebo. Advise resistance exercise and protein of 1.2–1.5 g/kg/day [[sema2025]].",
             "في مجموعة فرعية من ESSENCE خضعت لفحص DEXA، انخفضت الكتلة العضلية 6.92 كغ مع السيماغلوتايد مقابل 1.48 كغ مع الدواء الوهمي. انصح بتمارين المقاومة وبروتين بمقدار 1.2–1.5 غ/كغ/يوم [[sema2025]].")),
  ("p", ("Liver toxicity was not a problem in ESSENCE: no patient stopped because of raised ALT or AST, so AASLD advises liver tests only when clinically needed. Assess response at 72 weeks. A fall from baseline of at least 30% in VCTE stiffness, 20% in MRE stiffness, at least 0.5 in ELF, or more than 17 U/L (or 20%) in ALT probably reflects benefit; rising ALT or stiffness suggests non-response [[sema2025]].",
         "لم تكن السمّية الكبدية مشكلة في ESSENCE، إذ لم يوقف أي مريض العلاج بسبب ارتفاع ALT أو AST، لذا توصي AASLD بتحاليل الكبد عند الحاجة السريرية فقط. قيّم الاستجابة بعد 72 أسبوعًا: فانخفاض صلابة VCTE بنسبة 30% على الأقل، أو صلابة MRE بنسبة 20%، أو ELF بأكثر من 0.5، أو ALT بأكثر من 17 وحدة/ل (أو 20%) يدل غالبًا على الفائدة، أما ارتفاع ALT أو الصلابة فيشير إلى عدم الاستجابة [[sema2025]].")),
  ("rec", ("GLP-1 receptor agonists are safe in MASH, including compensated cirrhosis, and should be used for type 2 diabetes and obesity because they improve cardiometabolic outcomes.", "منبّهات مستقبل GLP-1 آمنة في MASH، بما في ذلك التشمّع المعاوَض، وينبغي استخدامها للسكري من النوع الثاني والسمنة لأنها تحسّن المآلات القلبية الأيضية."), 2, "strong", "strong", "easl2024"),
  ("rec", ("Without phase III histological proof, GLP-1 receptor agonists cannot yet be advised as MASH-directed treatment.", "في غياب دليل نسيجي من تجارب المرحلة الثالثة، لا يمكن بعدُ التوصية بمنبّهات مستقبل GLP-1 علاجًا موجّهًا لـ MASH."), 5, "strong", "strong", "easl2024"),
  ("p", ("This last recommendation predates the ESSENCE results, which were published in 2025 [[easl2024,essence]]. Expect EASL to revisit it.",
         "سبقت هذه التوصية الأخيرة نتائج ESSENCE المنشورة في 2025 [[easl2024,essence]]، ومن المتوقع أن تراجعها EASL.")),

  # 5 ---------------------------------------------------------------
  ("h2", ("Choosing between them, or combining", "الاختيار بينهما أو الجمع"), "choosing"),
  ("p", ("No head-to-head trial exists, and no guideline ranks one drug above the other. AASLD leaves the choice to clinical judgement, weighing liver risk against the burden of other disease [[resm2024]]. In practice, obesity, type 2 diabetes or established cardiovascular disease point towards semaglutide, which treats these conditions as well; the SELECT trial showed a 1.5% absolute reduction in major cardiovascular events in people with overweight or obesity and established cardiovascular disease [[sema2025]]. Resmetirom is a reasonable choice for patients who are not overweight, cannot tolerate a GLP-1 drug, or remain at F2–F3 despite one. A need for high-dose statin or clopidogrel, or untreated thyroid disease, weighs against resmetirom [[resm2024]].",
         "لا توجد تجربة مقارنة مباشرة، ولا تفضّل أي إرشادات أحد الدواءين على الآخر. وتترك AASLD الاختيار للحكم السريري بموازنة الخطر الكبدي مع عبء الأمراض الأخرى [[resm2024]]. وعمليًا، ترجّح السمنة أو السكري من النوع الثاني أو مرض القلب الوعائي الثابت كفّة السيماغلوتايد لأنه يعالج هذه الحالات أيضًا، وقد أظهرت تجربة SELECT انخفاضًا مطلقًا بنسبة 1.5% في الأحداث القلبية الكبرى لدى المصابين بزيادة الوزن أو السمنة مع مرض قلبي وعائي ثابت [[sema2025]]. ويُعد الريسميتيروم خيارًا معقولًا لمن ليس لديهم زيادة وزن، أو لا يتحمّلون أدوية GLP-1، أو بقوا في F2–F3 رغم تناولها. أما الحاجة إلى ستاتين بجرعة عالية أو إلى الكلوبيدوغريل، أو وجود مرض درقي غير معالَج، فترجّح الابتعاد عن الريسميتيروم [[resm2024]].")),
  ("p", ("Combination is unstudied. About 14% of MAESTRO-NASH patients were on a stable GLP-1 drug and responded to resmetirom as well as others, so EASL considers it reasonable to use resmetirom by the same criteria in these patients [[easl2024,sema2025]]. However, the 2.4 mg dose has never been combined with resmetirom in a trial [[sema2025]].",
         "لم يُدرس الجمع بينهما. فقد كان نحو 14% من مرضى MAESTRO-NASH يتناولون دواء GLP-1 بجرعة ثابتة واستجابوا للريسميتيروم مثل غيرهم، لذا ترى EASL أن استخدام الريسميتيروم بالمعايير نفسها لدى هؤلاء أمر معقول [[easl2024,sema2025]]. لكن جرعة 2.4 ملغ لم تُجمع قط مع الريسميتيروم في أي تجربة [[sema2025]].")),

  # 6 ---------------------------------------------------------------
  ("h2", ("Other drugs: what each guideline says", "الأدوية الأخرى: ماذا تقول كل إرشادات"), "other"),
  ("rec", ("Pioglitazone is safe in non-cirrhotic MASH but, lacking large phase III histological evidence, is not advised as a MASH-directed treatment.", "البيوغليتازون آمن في MASH دون تشمّع، لكن في غياب أدلة نسيجية من تجارب كبيرة في المرحلة الثالثة لا يوصى به علاجًا موجّهًا لـ MASH."), 2, "weak", "consensus", "easl2024"),
  ("rec", ("Vitamin E is not advised as a MASH-directed treatment, given weak phase III evidence and possible long-term risks.", "لا يوصى بفيتامين E علاجًا موجّهًا لـ MASH، بسبب ضعف أدلة المرحلة الثالثة واحتمال وجود مخاطر طويلة المدى."), 2, "weak", "strong", "easl2024"),
  ("rec", ("SGLT2 inhibitors and metformin lack evidence as MASH-directed treatment, but are safe in MASLD and should be used for diabetes, heart failure and kidney disease.", "لا تتوفر أدلة على مثبطات SGLT2 والميتفورمين علاجًا موجّهًا لـ MASH، لكنها آمنة في MASLD وينبغي استخدامها للسكري وقصور القلب ومرض الكلى."), 3, "strong", "strong", "easl2024"),
  ("rec", ("Statins can be used in chronic liver disease, including compensated cirrhosis, and should be prescribed according to cardiovascular risk.", "يمكن استخدام الستاتينات في أمراض الكبد المزمنة، بما في ذلك التشمّع المعاوَض، وينبغي وصفها وفق الخطر القلبي الوعائي."), 1, "strong", "strong", "easl2024"),
  ("table", {"caption": ("Table 3. Other drugs: positions by guideline", "الجدول 3. الأدوية الأخرى: المواقف حسب الإرشادات"),
             "head": [("Drug", "الدواء"), "EASL 2024", "AASLD 2023", ("Global 2025", "الإجماع العالمي 2025"), ("Saudi 2026", "السعودي 2026")],
             "rows": [
              [("Pioglitazone", "البيوغليتازون"), ("Safe; not a MASH treatment", "آمن؛ ليس علاجًا لـ MASH"), ("Can be considered in MASH with T2D", "يمكن النظر فيه في MASH مع السكري"), ("For T2D, not MASH-targeted", "للسكري، لا موجّهًا لـ MASH"), ("Recommended in T2D with biopsy-proven MASH and advanced fibrosis", "يوصى به في السكري مع MASH مؤكد بالخزعة وتليّف متقدّم")],
              [("Vitamin E", "فيتامين E"), ("Not recommended", "لا يوصى به"), ("Selected people without diabetes", "أشخاص مختارون دون سكري"), ("Only selected people without T2D or cirrhosis", "فقط أشخاص مختارون دون سكري أو تشمّع"), ("Can be considered without T2D; not with T2D or advanced fibrosis", "يمكن النظر فيه دون سكري؛ لا مع السكري أو التليّف المتقدّم")],
              [("SGLT2 inhibitors", "مثبطات SGLT2"), ("For their indications; not MASH-targeted", "لدواعيها؛ لا موجّهة لـ MASH"), ("Steatosis may improve; histology unclear", "قد يتحسّن التشحّم؛ والأثر النسيجي غير واضح"), ("For T2D, not MASH-targeted", "للسكري، لا موجّهة لـ MASH"), ("May be considered in T2D for cardiometabolic benefit", "يمكن النظر فيها في السكري للفائدة القلبية الأيضية")],
              [("Metformin", "الميتفورمين"), ("For its indications; not MASH-targeted", "لدواعيه؛ لا موجّه لـ MASH"), ("Should not be used to treat NASH", "لا يُستخدم لعلاج NASH"), ("Not preferred in T2D with MASLD", "ليس مفضّلًا في السكري مع MASLD"), ("Not recommended for MASH", "لا يوصى به لـ MASH")],
              [("Tirzepatide", "التيرزيباتايد"), ("Promising phase 2 data; no recommendation", "بيانات واعدة من المرحلة الثانية؛ دون توصية"), ("Possible benefit (liver fat)", "فائدة محتملة (دهون الكبد)"), ("Not named; GLP-1 RAs preferred for T2D and obesity", "لم يُذكر؛ ومنبّهات GLP-1 مفضّلة للسكري والسمنة"), ("May be considered for obesity", "يمكن النظر فيه للسمنة")],
              [("Statins", "الستاتينات"), ("Use for CV risk, incl. compensated cirrhosis", "تُستخدم للخطر القلبي، ومنه التشمّع المعاوَض"), ("Safe and recommended for CV risk; not a NASH treatment", "آمنة ويوصى بها للخطر القلبي؛ ليست علاجًا لـ NASH"), ("Not addressed", "لم يتناولها"), ("Not addressed", "لم يتناولها")],
             ]}),
  ("p", ("Sources for the table: EASL [[easl2024]], AASLD [[aasld2023]], global consensus [[global2025]] and Saudi consensus [[saudi2026]]. The main split is over pioglitazone and vitamin E: AASLD and the Saudi consensus leave room for both in selected patients, whereas EASL does not endorse either as a MASH treatment. Tirzepatide improved MASH in a phase 2 trial (resolution in 62% at 15 mg against 10% on placebo) but is not licensed for MASH [[saudi2026]].",
         "مصادر الجدول: EASL [[easl2024]]، وAASLD [[aasld2023]]، والإجماع العالمي [[global2025]]، والإجماع السعودي [[saudi2026]]. ويتركّز الخلاف حول البيوغليتازون وفيتامين E: فتترك AASLD والإجماع السعودي مجالًا لهما لدى مرضى مختارين، بينما لا تعتمد EASL أيًّا منهما علاجًا لـ MASH. وقد حسّن التيرزيباتايد MASH في تجربة من المرحلة الثانية (زوال المرض لدى 62% بجرعة 15 ملغ مقابل 10% مع الدواء الوهمي)، لكنه غير مرخّص لـ MASH [[saudi2026]].")),

  # 7 ---------------------------------------------------------------
  ("h2", ("Approval status around the world", "وضع الاعتماد حول العالم"), "approval"),
  ("table", {"caption": ("Table 4. Regulatory status for MASH with F2–F3 fibrosis (as of October 2026)", "الجدول 4. الوضع التنظيمي لـ MASH مع تليّف F2–F3 (حتى أكتوبر 2026)"),
             "head": [("Region", "المنطقة"), ("Resmetirom", "الريسميتيروم"), ("Semaglutide 2.4 mg", "السيماغلوتايد 2.4 ملغ")],
             "rows": [
              [("United States (FDA)", "الولايات المتحدة (FDA)"), ("Accelerated approval, March 2024", "موافقة معجّلة، مارس 2024"), ("Accelerated approval, August 2025", "موافقة معجّلة، أغسطس 2025")],
              [("European Union", "الاتحاد الأوروبي"), ("Conditional authorisation, August 2025", "ترخيص مشروط، أغسطس 2025"), ("Check current status", "تحقّق من الوضع الحالي")],
              [("United Kingdom (MHRA)", "المملكة المتحدة (MHRA)"), ("Approved, June 2026", "معتمد، يونيو 2026"), ("Conditional authorisation, July 2026", "ترخيص مشروط، يوليو 2026")],
              [("Saudi Arabia (SFDA)", "السعودية (هيئة الغذاء والدواء)"), ("Check SFDA", "تحقّق لدى الهيئة"), ("Check SFDA", "تحقّق لدى الهيئة")],
             ]}),
  ("p", ("Sources: FDA dates from the AASLD updates [[resm2024,sema2025]]; EU decision [[ec2025]]; UK decisions, both awaiting NICE appraisal for NHS use [[blt2026]]. All approvals are provisional on outcome data. Approvals change quickly and differ between countries, so always confirm the current SFDA status and the local label before prescribing for MASH.",
         "المصادر: تواريخ FDA من تحديثَي AASLD [[resm2024,sema2025]]، وقرار الاتحاد الأوروبي [[ec2025]]، وقرارات المملكة المتحدة، وكلاهما بانتظار تقييم NICE للاستخدام في الخدمة الصحية الوطنية [[blt2026]]. وجميع هذه الموافقات مشروطة ببيانات المآلات. وتتغيّر الموافقات بسرعة وتختلف بين الدول، لذا تأكد دائمًا من وضع الهيئة العامة للغذاء والدواء والنشرة المحلية قبل الوصف لـ MASH.")),

  # 8 ---------------------------------------------------------------
  ("h2", ("The Saudi 2026 consensus", "الإجماع السعودي 2026"), "saudi"),
  ("p", ("The Saudi consensus adapts international guidance to local practice. It recommends GLP-1 receptor agonists (semaglutide 2.4 mg weekly or liraglutide 3 mg daily) with lifestyle change for MASLD or MASH with BMI above 27 kg/m², type 2 diabetes, cardiovascular disease or other obesity-related conditions. Tirzepatide for obesity and resmetirom 80–100 mg for MASH with fibrosis may be considered, pending more real-world evidence (moderate level of evidence) [[saudi2026]].",
         "يكيّف الإجماع السعودي الإرشادات الدولية مع الممارسة المحلية، فيوصي بمنبّهات مستقبل GLP-1 (السيماغلوتايد 2.4 ملغ أسبوعيًا أو الليراغلوتايد 3 ملغ يوميًا) مع تعديل نمط الحياة لمرضى MASLD أو MASH مع مؤشر كتلة أعلى من 27 كغ/م²، أو السكري من النوع الثاني، أو أمراض القلب، أو حالات أخرى مرتبطة بالسمنة. ويمكن النظر في التيرزيباتايد للسمنة والريسميتيروم 80–100 ملغ لـ MASH مع التليّف، بانتظار مزيد من أدلة الواقع العملي (مستوى دليل متوسط) [[saudi2026]].")),
  ("p", ("At the time of writing, the consensus stated that the drugs available for MASLD in Saudi Arabia were those licensed for diabetes and obesity, such as GLP-1 agonists, pioglitazone and SGLT2 inhibitors, used off-label for the liver, and that resmetirom was not yet approved locally. It also does not advise metformin, acarbose, DPP-4 inhibitors, ursodeoxycholic acid or insulin as MASH treatment (high level of evidence) [[saudi2026]].",
         "ذكر الإجماع وقت كتابته أن الأدوية المتاحة لـ MASLD في السعودية هي المرخّصة للسكري والسمنة، مثل منبّهات GLP-1 والبيوغليتازون ومثبطات SGLT2، وتُستخدم للكبد خارج دواعي النشرة، وأن الريسميتيروم لم يُعتمد محليًا بعد. كما لا يوصي بالميتفورمين أو الأكاربوز أو مثبطات DPP-4 أو حمض أورسوديوكسيكوليك أو الإنسولين علاجًا لـ MASH (مستوى دليل مرتفع) [[saudi2026]].")),

  # 9 ---------------------------------------------------------------
  ("h2", ("Clinical case", "حالة سريرية"), "case"),
  ("case", {"title": ("A 55-year-old man with diabetes and a coronary stent", "رجل عمره 55 عامًا مصاب بالسكري ولديه دعامة تاجية"),
            "parts": [
             (("Presentation", "العرض"), ("Seen in Dammam. Type 2 diabetes on metformin and gliclazide, HbA1c 8.1%. Weight 104 kg, BMI 34 kg/m². Coronary stent 1 year ago; takes clopidogrel and atorvastatin 80 mg. No alcohol. AST 38 U/L, ALT 45 U/L, platelets 230 ×10⁹/L, TSH normal. Viral and autoimmune screens negative.", "يُتابَع في الدمام. مصاب بالسكري من النوع الثاني ويتناول الميتفورمين والغليكلازايد، وHbA1c ‏8.1%. الوزن 104 كغ ومؤشر الكتلة 34 كغ/م². رُكّبت له دعامة تاجية قبل سنة، ويتناول الكلوبيدوغريل والأتورفاستاتين 80 ملغ. لا يتناول الكحول. AST ‏38 وحدة/ل، وALT ‏45 وحدة/ل، والصفائح 230 ×10⁹/ل، وTSH طبيعي. فحوص الفيروسات والمناعة الذاتية سلبية.")),
             (("Staging", "تحديد المرحلة"), ("FIB-4 = (55 × 38) ÷ (230 × √45) = 2,090 ÷ (230 × 6.71) = 2,090 ÷ 1,543 = 1.35, which is indeterminate. VCTE with the XL probe: 11.2 kPa, IQR/median 15%, CAP 330 dB/m. This lies within 8–15 kPa, consistent with F2–F3; platelets are normal and imaging shows no signs of cirrhosis.", "FIB-4 = (55 × 38) ÷ (230 × √45) = 2,090 ÷ (230 × 6.71) = 2,090 ÷ 1,543 = 1.35، وهي نتيجة غير حاسمة. وبفحص VCTE بالمجس XL: الصلابة 11.2 كيلوباسكال، وIQR/الوسيط 15%، وCAP ‏330 ديسيبل/م. وهذا ضمن 8–15 كيلوباسكال بما يتوافق مع F2–F3، والصفائح طبيعية ولا يُظهر التصوير علامات تشمّع.")),
             (("Decision", "القرار"), ("Both drugs are options on liver grounds. Resmetirom would need 80 mg (≥100 kg plus clopidogrel) and atorvastatin cut to 40 mg, which conflicts with his post-stent lipid target. Semaglutide treats his obesity, diabetes and cardiovascular risk as well. After confirming local availability, semaglutide is started at 0.25 mg weekly and increased over 16 weeks to 2.4 mg. Gliclazide is reduced to avoid hypoglycaemia, a retinal exam is booked and he is advised on protein intake and resistance exercise.", "الدواءان خياران من الناحية الكبدية. لكن الريسميتيروم يتطلب جرعة 80 ملغ (وزن ≥100 كغ مع الكلوبيدوغريل) وخفض الأتورفاستاتين إلى 40 ملغ، وهذا يتعارض مع هدف الدهون بعد الدعامة. أما السيماغلوتايد فيعالج السمنة والسكري والخطر القلبي أيضًا. وبعد التأكد من الإتاحة المحلية يبدأ السيماغلوتايد بجرعة 0.25 ملغ أسبوعيًا وتُرفع خلال 16 أسبوعًا إلى 2.4 ملغ. وتُخفّض جرعة الغليكلازايد لتجنّب هبوط السكر، ويُحجز له فحص لقاع العين، ويُنصح بالبروتين وتمارين المقاومة.")),
             (("Week 72", "الأسبوع 72"), ("Weight 93 kg: a loss of 11 kg, or 11 ÷ 104 = 10.6%. VCTE 7.4 kPa: a fall of 3.8 kPa, or 3.8 ÷ 11.2 = 34%. ALT 24 U/L, a fall of 21 U/L. Each change exceeds the AASLD response thresholds (VCTE ≥30%, ALT >17 U/L), so treatment continues.", "الوزن 93 كغ: خسارة 11 كغ، أي 11 ÷ 104 = 10.6%. وVCTE ‏7.4 كيلوباسكال: انخفاض 3.8 كيلوباسكال، أي 3.8 ÷ 11.2 = 34%. وALT ‏24 وحدة/ل، بانخفاض 21 وحدة/ل. وكل تغيّر يتجاوز حدود الاستجابة لدى AASLD (VCTE ≥30%، وALT >17 وحدة/ل)، لذا يستمر العلاج.")),
             (("Teaching points", "نقاط تعليمية"), ("Interactions and comorbidity often decide the drug. Measure stiffness with the same method at baseline and follow-up. A good response does not mean stopping: benefits fade when semaglutide is withdrawn.", "كثيرًا ما تحدّد التداخلات والأمراض المصاحبة اختيار الدواء. قِس الصلابة بالطريقة نفسها عند البدء وفي المتابعة. والاستجابة الجيدة لا تعني الإيقاف، فالفوائد تتلاشى عند سحب السيماغلوتايد.")),
            ]}),

  # 10 --------------------------------------------------------------
  ("h2", ("Test yourself", "اختبر نفسك"), "quiz"),
  ("mcq", [
   {"q": ("An 85 kg woman with MASH F2–F3 takes clopidogrel. What resmetirom dose does AASLD advise?", "امرأة وزنها 85 كغ مصابة بـ MASH ‏F2–F3 وتتناول الكلوبيدوغريل. ما جرعة الريسميتيروم التي توصي بها AASLD؟"),
    "options": [("100 mg daily", "100 ملغ يوميًا"), ("80 mg daily", "80 ملغ يوميًا"), ("60 mg daily", "60 ملغ يوميًا"), ("Resmetirom is contraindicated", "الريسميتيروم ممنوع")],
    "answer": 2,
    "why": ("Below 100 kg the usual dose is 80 mg; a moderate CYP2C8 inhibitor such as clopidogrel lowers it to 60 mg.", "تحت 100 كغ تكون الجرعة المعتادة 80 ملغ، ومع مثبط متوسط لـ CYP2C8 مثل الكلوبيدوغريل تنخفض إلى 60 ملغ.")},
   {"q": ("Which statin dose exceeds the AASLD maximum when given with resmetirom?", "أيّ جرعة ستاتين تتجاوز الحد الأعلى لدى AASLD عند إعطائها مع الريسميتيروم؟"),
    "options": [("Rosuvastatin 40 mg", "روزوفاستاتين 40 ملغ"), ("Atorvastatin 40 mg", "أتورفاستاتين 40 ملغ"), ("Pravastatin 40 mg", "برافاستاتين 40 ملغ"), ("Simvastatin 20 mg", "سيمفاستاتين 20 ملغ")],
    "answer": 0,
    "why": ("Rosuvastatin and simvastatin are capped at 20 mg/day, atorvastatin and pravastatin at 40 mg/day.", "الحد الأعلى للروزوفاستاتين والسيمفاستاتين 20 ملغ/يوم، وللأتورفاستاتين والبرافاستاتين 40 ملغ/يوم.")},
   {"q": ("A patient with MASLD has VCTE 23 kPa and platelets 120 ×10⁹/L. What is correct?", "مريض مصاب بـ MASLD لديه صلابة VCTE ‏23 كيلوباسكال وصفائح 120 ×10⁹/ل. ما الصحيح؟"),
    "options": [("Start resmetirom", "ابدأ الريسميتيروم"), ("Start semaglutide for MASH", "ابدأ السيماغلوتايد لـ MASH"), ("Start vitamin E", "ابدأ فيتامين E"), ("Cirrhosis is likely; no MASH drug is approved at this stage", "التشمّع مرجّح، ولا يوجد دواء معتمد لـ MASH في هذه المرحلة")],
    "answer": 3,
    "why": ("VCTE above 20 kPa suggests cirrhosis, which is outside both licences. GLP-1 drugs may still be used for diabetes or obesity.", "تشير صلابة VCTE فوق 20 كيلوباسكال إلى التشمّع، وهو خارج ترخيص الدواءين. ويمكن مع ذلك استخدام أدوية GLP-1 للسكري أو السمنة.")},
   {"q": ("Which finding is a contraindication to semaglutide?", "أيّ مما يلي يُعد مانعًا لاستعمال السيماغلوتايد؟"),
    "options": [("Gallstones found on ultrasound", "حصى مرارية في الأشعة الصوتية"), ("Mother had medullary thyroid carcinoma", "إصابة الأم بسرطان الغدة الدرقية النخاعي"), ("Compensated cirrhosis with type 2 diabetes", "تشمّع معاوَض مع السكري من النوع الثاني"), ("eGFR 55 mL/min/1.73 m²", "eGFR ‏55 مل/دقيقة/1.73 م²")],
    "answer": 1,
    "why": ("A personal or family history of medullary thyroid carcinoma or MEN2 is a contraindication. Gallstones call for caution, not avoidance.", "التاريخ الشخصي أو العائلي لسرطان الغدة الدرقية النخاعي أو MEN2 مانع للاستعمال، أما حصى المرارة فتستدعي الحذر لا التجنّب.")},
   {"q": ("After 12 months of resmetirom, how does the global consensus define a clinically significant VCTE change?", "بعد 12 شهرًا من الريسميتيروم، كيف يعرّف الإجماع العالمي التغيّر المهم سريريًا في VCTE؟"),
    "options": [("Any fall below 10 kPa", "أي انخفاض إلى ما دون 10 كيلوباسكال"), ("A change of at least 25%", "تغيّر لا يقل عن 25%"), ("A change of at least 30%", "تغيّر لا يقل عن 30%"), ("A fall in CAP of 30%", "انخفاض CAP بنسبة 30%")],
    "answer": 2,
    "why": ("The global consensus uses 30%; AASLD uses 25% for VCTE. CAP changes did not predict response.", "يستخدم الإجماع العالمي 30%، بينما تستخدم AASLD ‏25% لـ VCTE. ولم تتنبأ تغيّرات CAP بالاستجابة.")},
  ]),

  # 11 --------------------------------------------------------------
  ("h2", ("Key messages", "الرسائل الأساسية"), "summary"),
  ("ul", [
   ("Drug treatment is for MASH with F2–F3 fibrosis and no cirrhosis, identified by non-invasive tests; lifestyle change continues alongside.", "العلاج الدوائي لـ MASH مع تليّف F2–F3 دون تشمّع، يُحدَّد بالفحوص غير الجراحية، ويستمر تعديل نمط الحياة إلى جانبه."),
   ("Resmetirom: 80 or 100 mg by weight, lower with clopidogrel, statin caps, TSH first, liver tests at 3, 6 and 12 months.", "الريسميتيروم: 80 أو 100 ملغ حسب الوزن، وجرعة أقل مع الكلوبيدوغريل، وحدود للستاتين، وفحص TSH أولًا، وتحاليل الكبد بعد 3 و6 و12 شهرًا."),
   ("Semaglutide 2.4 mg: titrate over 16 weeks, manage GI effects, protect muscle, avoid in MTC or MEN2.", "السيماغلوتايد 2.4 ملغ: ارفع الجرعة خلال 16 أسبوعًا، وعالج الآثار الهضمية، واحمِ العضلات، وتجنّبه مع سرطان الدرقية النخاعي أو MEN2."),
   ("Judge response with the same stiffness test: AASLD uses 25% (resmetirom) or 30% (semaglutide) on VCTE; the global consensus uses 30%.", "قيّم الاستجابة بفحص الصلابة نفسه: تستخدم AASLD ‏25% (الريسميتيروم) أو 30% (السيماغلوتايد) في VCTE، ويستخدم الإجماع العالمي 30%."),
   ("Guidelines disagree on pioglitazone and vitamin E; approvals differ by country, so check SFDA status before prescribing.", "تختلف الإرشادات حول البيوغليتازون وفيتامين E، وتختلف الموافقات بين الدول، لذا تحقّق من وضع الهيئة العامة للغذاء والدواء قبل الوصف."),
  ]),
 ],
}
