# -*- coding: utf-8 -*-
"""Module 3: The lifestyle prescription (English + Arabic). Same schema as modules.py."""

# New sources only (each checked on PubMed). Existing keys (easl2024, aasld2023, global2025,
# saudi2026, vilar, braves2023, lassailly, asmbs2022) are defined in ref.py / learn.py.
SOURCES = {
    "sema2025": ("Bansal MB, et al. Semaglutide therapy for metabolic dysfunction-associated steatohepatitis: November 2025 updates to AASLD Practice Guidance. Hepatology 2026;83(5):1326–40.", "https://doi.org/10.1097/HEP.0000000000001608"),
    "ramadanma2025": ("Kamrul-Hasan ABM, et al. Impacts of Ramadan fasting on metabolic and hepatic endpoints in individuals with metabolic dysfunction-associated fatty liver disease: a systematic review and meta-analysis. JGH Open 2025;9(8):e70264.", "https://doi.org/10.1002/jgh3.70264"),
    "ramadanrev2026": ("Khalifa R, et al. Intermittent fasting and liver disease: insights from the Ramadan model. Saudi J Gastroenterol 2026;32(2):93–103.", "https://doi.org/10.4103/sjg.sjg_120_25"),
}

MODULE = {
 "slug": "lifestyle-prescription",
 "number": 3,
 "title": {"en": "The lifestyle prescription", "ar": "الوصفة العلاجية لنمط الحياة"},
 "subtitle": {"en": "How much weight to lose, what to eat and drink, how to move, and when lifestyle needs help from drugs or surgery.",
              "ar": "كم من الوزن ينبغي إنقاصه، وماذا يؤكل ويُشرب، وكيف يتحرك المريض، ومتى يحتاج تعديل نمط الحياة إلى مساندة بالأدوية أو الجراحة."},
 "minutes": 25,
 "audience": {"en": "Primary care physicians, internists, endocrinologists, gastroenterologists, residents",
              "ar": "أطباء الرعاية الأولية، وأطباء الباطنة، وأطباء الغدد الصماء، وأطباء الجهاز الهضمي، والأطباء المقيمون"},
 "objectives": [
  ("Set weight-loss targets linked to liver histology, and explain where guidelines differ.", "تحديد أهداف إنقاص الوزن المرتبطة بالتغيرات النسيجية في الكبد، وشرح مواضع اختلاف الإرشادات."),
  ("Write a practical diet and activity plan adapted to Gulf eating habits.", "كتابة خطة عملية للغذاء والنشاط البدني تلائم عادات الأكل في الخليج."),
  ("Assess and advise on alcohol and smoking, including MetALD.", "تقييم تناول الكحول والتدخين وتقديم المشورة بشأنهما، بما في ذلك MetALD."),
  ("Recognise when to add obesity medicines or metabolic surgery, and adapt advice in cirrhosis, sarcopenia and Ramadan.", "معرفة متى تُضاف أدوية السمنة أو الجراحة الأيضية، وتكييف النصائح في التشمّع وضمور العضلات (الساركوبينيا) وصيام رمضان."),
 ],
 "blocks": [
  # 1
  ("h2", ("Why lifestyle is the foundation", "لماذا يُعد نمط الحياة الأساس"), "why"),
  ("p", ("Metabolic dysfunction-associated steatotic liver disease (MASLD) grows out of excess energy intake, poor diet quality and inactivity, and type 2 diabetes and obesity are its strongest drivers [[easl2024]]. Lifestyle change treats these causes directly. It is therefore the first step at every stage, from simple steatosis to compensated cirrhosis, and it continues when drugs or surgery are added.",
         "ينشأ مرض الكبد المتدهن المرتبط بخلل التمثيل الغذائي (MASLD) من فرط السعرات الحرارية وسوء نوعية الغذاء وقلة الحركة، ويُعد السكري من النوع الثاني والسمنة أقوى محرّكاته [[easl2024]]. ويعالج تعديل نمط الحياة هذه الأسباب مباشرة، لذا فهو الخطوة الأولى في كل مرحلة، من التشحّم البسيط إلى التشمّع المعاوَض، ويستمر حتى بعد إضافة الأدوية أو الجراحة.")),
  ("rec", ("Weight loss achieved through diet and behavioural therapy should be advised for adults with MASLD, because it improves liver injury on histology and on non-invasive tests.", "يُنصح البالغون المصابون بـ MASLD بإنقاص الوزن عبر الغذاء والعلاج السلوكي، لأنه يحسّن إصابة الكبد نسيجيًا وفي الفحوص غير الجراحية."), 1, "strong", "strong", "easl2024"),
  ("p", ("Cardiovascular disease and cancer are the main causes of death in MASLD [[saudi2026]], and the same diet and activity changes lower cardiovascular risk [[easl2024,aasld2023]]. The weak point is evidence on hard liver outcomes: lifestyle trials have lasted 2–24 months, and data on death, decompensation and liver cancer remain sparse [[easl2024]].",
         "وتتجاوز الفائدة الكبد، فأمراض القلب والأوعية والسرطان هي الأسباب الرئيسية للوفاة في MASLD [[saudi2026]]، والتغييرات نفسها في الغذاء والنشاط تخفّض الخطر القلبي الوعائي [[easl2024,aasld2023]]. أما نقطة الضعف فهي الأدلة على المآلات الكبدية الصلبة: إذ امتدت تجارب نمط الحياة من شهرين إلى 24 شهرًا، وما تزال البيانات عن الوفاة وعدم المعاوضة وسرطان الكبد شحيحة [[easl2024]].")),

  # 2
  ("h2", ("Weight-loss targets", "أهداف إنقاص الوزن"), "targets"),
  ("rec", ("In overweight adults with MASLD, aim for sustained weight loss of at least 5% to reduce liver fat, 7–10% to reduce inflammation, and at least 10% to improve fibrosis.", "لدى البالغين المصابين بـ MASLD وزيادة الوزن، يُستهدف إنقاص مستدام للوزن بنسبة 5% على الأقل لخفض دهون الكبد، و7–10% لتخفيف الالتهاب، و10% على الأقل لتحسين التليّف."), 2, "strong", "strong", "easl2024"),
  ("p", ("These thresholds come largely from one prospective study of 293 patients with biopsy-proven steatohepatitis who were coached in lifestyle change for 52 weeks. Only 30% lost 5% or more of their weight. Among those who lost at least 10%, steatohepatitis resolved in 90% and fibrosis regressed in 45%; the greater the weight loss, the greater the histological gain [[vilar]].",
         "تستند هذه الحدود أساسًا إلى دراسة استباقية شملت 293 مريضًا بالتهاب كبد دهني مثبت بالخزعة، تلقّوا توجيهًا لتعديل نمط الحياة مدة 52 أسبوعًا. ولم يفقد سوى 30% منهم 5% أو أكثر من وزنهم. ومن بين من فقدوا 10% على الأقل، زال التهاب الكبد الدهني لدى 90% وتراجع التليّف لدى 45%، وكلما زاد إنقاص الوزن زاد التحسّن النسيجي [[vilar]].")),
  ("table", {"caption": ("Table 1. Weight-loss targets in four guidance documents", "الجدول 1. أهداف إنقاص الوزن في أربع وثائق إرشادية"),
             "head": [("Guidance", "الإرشاد"), ("Liver fat", "دهون الكبد"), ("Inflammation (MASH)", "الالتهاب (MASH)"), ("Fibrosis", "التليّف")],
             "rows": [
              ["EASL–EASD–EASO 2024", "≥5%", "7–10%", "≥10%"],
              ["AASLD 2023", "3–5%", ">10%", ">10%"],
              [("Global consensus 2025", "الإجماع العالمي 2025"), ("5% (3–5% if lean)", "5% (و3–5% لذوي الوزن الطبيعي)"), "7–10%", "10%"],
              [("Saudi consensus 2026", "الإجماع السعودي 2026"), ("At least 5%, ideally more than 10% (single target)", "5% على الأقل، والأفضل أكثر من 10% (هدف واحد)"), "–", "–"],
             ]}),
  ("p", ("AASLD sets a lower bar for steatosis (3–5%) but asks for more than 10% for both steatohepatitis and fibrosis; EASL and the global consensus place inflammation at 7–10% [[easl2024,aasld2023,global2025]]. In normal-weight MASLD, EASL still advises diet and exercise to reduce liver fat (LoE 3, strong recommendation), and the global consensus suggests a 3–5% target, although no study has shown an effect on fibrosis or outcomes in this group [[easl2024,global2025]].",
         "تضع AASLD حدًا أدنى للتشحّم (3–5%)، لكنها تطلب أكثر من 10% لكلٍّ من التهاب الكبد الدهني والتليّف، بينما تضع EASL والإجماع العالمي الالتهاب عند 7–10% [[easl2024,aasld2023,global2025]]. وفي MASLD لدى ذوي الوزن الطبيعي، ما تزال EASL تنصح بالغذاء والتمارين لخفض دهون الكبد (مستوى الدليل 3، توصية قوية)، ويقترح الإجماع العالمي هدفًا بنسبة 3–5%، مع أن أي دراسة لم تُثبت أثرًا على التليّف أو المآلات في هذه الفئة [[easl2024,global2025]].")),
  ("p", ("Weight regain is the rule, not the exception. At most 1 in 10 patients achieve effective weight loss at one year despite structured programmes, and fewer than half of these keep it off at five years [[aasld2023]]. In longer diet trials, weight loss peaks at about six months and settles at a net loss of about 5% by 12–24 months [[easl2024]].",
         "استعادة الوزن هي القاعدة لا الاستثناء. فلا يحقق سوى مريض واحد على الأكثر من كل 10 إنقاصًا فعّالًا للوزن بعد سنة رغم البرامج المنظّمة، وأقل من نصف هؤلاء يحافظون عليه بعد خمس سنوات [[aasld2023]]. وفي تجارب الحمية الأطول يبلغ إنقاص الوزن ذروته نحو الشهر السادس، ثم يستقر عند صافي نحو 5% بعد 12–24 شهرًا [[easl2024]].")),

  # 3
  ("h2", ("Diet quality and the calorie deficit", "نوعية الغذاء وعجز السعرات"), "diet"),
  ("rec", ("Advise a better-quality diet along the lines of the Mediterranean pattern, fewer ultra-processed foods rich in sugar and saturated fat, and no sugar-sweetened drinks.", "انصح بغذاء أفضل نوعيةً على نهج النمط المتوسطي، والإقلال من الأطعمة فائقة المعالجة الغنية بالسكر والدهون المشبعة، وتجنّب المشروبات المحلّاة بالسكر."), 2, "strong", "strong", "easl2024"),
  ("p", ("For patients with overweight, the core is a calorie deficit. Low-carbohydrate and low-fat hypocaloric diets reduce liver fat to a similar degree, so the best diet is the one the patient can keep [[easl2024,aasld2023]]. The Mediterranean pattern (olive oil, vegetables, whole fruit, legumes, nuts, whole grains, fish) has added cardiometabolic value and is easier to sustain. Evidence is insufficient for very-low-carbohydrate ketogenic diets, and time-restricted eating has not clearly beaten simple calorie restriction for liver fat [[easl2024]].",
         "لدى المرضى ذوي الوزن الزائد، يبقى عجز السعرات الحرارية هو الأساس. فالحميات منخفضة السعرات، سواء أكانت قليلة الكربوهيدرات أم قليلة الدهون، تخفض دهون الكبد بدرجة متقاربة، لذا فأفضل حمية هي التي يستطيع المريض الالتزام بها [[easl2024,aasld2023]]. وللنمط المتوسطي (زيت الزيتون والخضروات والفاكهة الكاملة والبقوليات والمكسّرات والحبوب الكاملة والأسماك) قيمة قلبية أيضية إضافية، وهو أسهل في الاستمرار. ولا تكفي الأدلة لدعم الحمية الكيتونية شديدة الانخفاض في الكربوهيدرات، ولم يتفوّق الأكل المقيّد بالوقت بوضوح على تقييد السعرات البسيط في خفض دهون الكبد [[easl2024]].")),
  ("p", ("Fructose intake is linked to MASLD and, in AASLD's reading, to steatohepatitis and advanced fibrosis independent of calories [[aasld2023]]. Sugar-sweetened drinks are linked to liver fat and to new MASLD in a dose-dependent way [[easl2024]]. Nutraceuticals and supplements cannot be recommended (LoE 2, open recommendation) [[easl2024]].",
         "تناول الفركتوز مرتبط بـ MASLD، ووفق قراءة AASLD بالتهاب الكبد الدهني والتليّف المتقدّم بمعزل عن السعرات [[aasld2023]]. وترتبط المشروبات المحلّاة بالسكر بدهون الكبد وبظهور MASLD جديد بعلاقة تتناسب مع الكمية [[easl2024]]. ولا يمكن التوصية بالمكمّلات الغذائية (مستوى الدليل 2، توصية مفتوحة) [[easl2024]].")),
  ("aside", ("In a prospective cohort, drinking soft drinks 4 or more times a week was linked to a 45% higher risk of developing MASLD [[easl2024]].",
             "في دراسة أترابية استباقية، ارتبط شرب المشروبات الغازية 4 مرات أسبوعيًا أو أكثر بارتفاع خطر الإصابة بـ MASLD بنسبة 45% [[easl2024]].")),
  ("p", ("Coffee is where guidelines part ways. AASLD states that 3 or more cups a day, caffeinated or not, could be recommended if there is no contraindication [[aasld2023]]. EASL accepts the observational link with less fibrosis and fewer liver deaths (LoE 4) but draws no firm conclusion, because trials are few and negative or inconclusive [[easl2024]]. A reasonable line is not to discourage coffee, without sugar, in patients who already drink it.",
         "في القهوة تختلف الإرشادات. إذ تذكر AASLD أنه يمكن التوصية بثلاثة أكواب يوميًا أو أكثر، بالكافيين أو بدونه، عند عدم وجود مانع [[aasld2023]]. أما EASL فتقرّ بالارتباط الرصدي بتليّف أقل ووفيات كبدية أقل (مستوى الدليل 4)، لكنها لا تخلص إلى استنتاج قاطع لأن التجارب قليلة ونتائجها سلبية أو غير حاسمة [[easl2024]]. والموقف المعقول ألا تُثبّط القهوة، دون سكر، لدى من يشربها أصلًا.")),
  ("table", {"caption": ("Table 2. Practical swaps for common Gulf eating habits", "الجدول 2. بدائل عملية لعادات الأكل الشائعة في الخليج"),
             "head": [("Habit", "العادة"), ("Why it matters", "لماذا تهم"), ("Practical swap", "البديل العملي")],
             "rows": [
              [("Soft drinks, energy drinks, packaged juices", "المشروبات الغازية ومشروبات الطاقة والعصائر المعلّبة"), ("Sugar-sweetened drinks and added fructose", "مشروبات محلّاة وفركتوز مضاف"), ("Water, sparkling water, unsweetened drinks; whole fruit instead of juice", "الماء أو المياه الغازية أو مشروبات غير محلّاة؛ والفاكهة الكاملة بدل العصير")],
              [("Sweet tea through the day", "الشاي المحلّى طوال اليوم"), ("Repeated added sugar", "سكر مضاف متكرر"), ("Reduce sugar step by step to none; fewer cups", "خفض السكر تدريجيًا حتى الاستغناء عنه؛ وتقليل عدد الأكواب")],
              [("Large rice portions (kabsa, mandi) twice a day", "حصص أرز كبيرة (كبسة، مندي) مرتين يوميًا"), ("Refined starch and excess energy", "نشويات مكرّرة وسعرات زائدة"), ("Smaller rice portion, half the plate vegetables, add legumes; brown rice or whole grains", "حصة أرز أصغر ونصف الطبق خضروات وإضافة البقوليات؛ أو الأرز البني والحبوب الكاملة")],
              [("Dates as frequent snacks", "التمر وجبةً خفيفة متكررة"), ("Energy-dense natural sugar", "سكر طبيعي عالي السعرات"), ("Count dates as a fruit portion and keep to a few; pair with nuts or laban", "احسب التمر حصة فاكهة واكتفِ بعدد قليل؛ مع مكسّرات أو لبن")],
              [("Fried snacks, fast food, processed meat", "المقليات والوجبات السريعة واللحوم المصنّعة"), ("Ultra-processed, saturated fat, processed red meat", "أغذية فائقة المعالجة ودهون مشبعة ولحوم حمراء مصنّعة"), ("Grilled fish or poultry, olive oil, home-cooked meals", "سمك أو دجاج مشوي، وزيت الزيتون، ووجبات منزلية")],
              [("Daily sweets and pastries", "الحلويات والمعجّنات يوميًا"), ("Added sugar and refined flour", "سكر مضاف ودقيق مكرّر"), ("Keep for occasions, in small portions", "اجعلها للمناسبات وبحصص صغيرة")],
             ]}),

  # 4
  ("h2", ("Physical activity and resistance training", "النشاط البدني وتمارين المقاومة"), "activity"),
  ("rec", ("Prescribe physical activity tailored to the patient's preference and ability, ideally more than 150 minutes a week of moderate or 75 minutes of vigorous activity, to reduce steatosis.", "صِف نشاطًا بدنيًا يلائم رغبة المريض وقدرته، ويُفضّل أكثر من 150 دقيقة أسبوعيًا من النشاط المعتدل أو 75 دقيقة من النشاط الشديد، لخفض التشحّم."), 1, "strong", "strong", "easl2024"),
  ("p", ("Exercise reduces liver fat even without weight loss. Aerobic, resistance and high-intensity interval training all work; EASL prefers aerobic plus resistance training [[easl2024]]. Evidence for an effect on histology and fibrosis is weaker than for steatosis (LoE 5), but exercise improves fitness, visceral fat and muscle mass, even in advanced disease [[easl2024]].",
         "تخفض التمارين دهون الكبد حتى دون إنقاص الوزن. وتنجح التمارين الهوائية وتمارين المقاومة والتدريب المتقطّع عالي الشدة جميعها، وتفضّل EASL الجمع بين التمارين الهوائية وتمارين المقاومة [[easl2024]]. والأدلة على أثرها في النسيج والتليّف أضعف منها في التشحّم (مستوى الدليل 5)، لكن التمارين تحسّن اللياقة والدهون الحشوية والكتلة العضلية حتى في المرض المتقدّم [[easl2024]].")),
  ("p", ("The global consensus gives a wider range: 150–300 minutes of moderate or 75–150 minutes of vigorous activity a week, with less sitting time [[global2025]]. In practice, start from what the patient does now, add brisk walking in cool hours or indoors (malls, home), and add simple resistance work with body weight or bands.",
         "يعطي الإجماع العالمي مدى أوسع: 150–300 دقيقة من النشاط المعتدل أو 75–150 دقيقة من النشاط الشديد أسبوعيًا، مع تقليل وقت الجلوس [[global2025]]. وعمليًا، ابدأ مما يفعله المريض الآن، وأضف المشي السريع في الساعات الباردة أو في الأماكن المغلقة (المراكز التجارية أو المنزل)، ثم تمارين مقاومة بسيطة بوزن الجسم أو بالأشرطة المطاطية.")),

  # 5
  ("h2", ("Alcohol, MetALD and smoking", "الكحول وMetALD والتدخين"), "alcohol"),
  ("rec", ("Record the amount, pattern and history of alcohol use in every person with steatotic liver disease.", "وثّق كمية تناول الكحول ونمطه وتاريخه لدى كل مريض بمرض الكبد التشحّمي."), 3, "strong", "strong", "easl2024"),
  ("rec", ("Discourage alcohol in steatotic liver disease, especially when intake is moderate or high.", "ثبّط تناول الكحول في مرض الكبد التشحّمي، خاصة عندما يكون التناول معتدلًا أو مرتفعًا."), 3, "strong", "consensus", "easl2024"),
  ("rec", ("People with advanced fibrosis or cirrhosis should stop all alcohol, completely and for good.", "يجب على المصابين بتليّف متقدّم أو تشمّع التوقف عن الكحول كليًا ونهائيًا."), 3, "strong", "strong", "easl2024"),
  ("p", ("Alcohol and metabolic risk factors act together, and the combined effect can be greater than the sum [[easl2024]]. Recent data no longer support a protective effect of light drinking, particularly in people with cardiometabolic risk factors [[easl2024]]. Ask every patient, including where alcohol use is uncommon or under-reported; AUDIT-C takes three questions [[easl2024]].",
         "يعمل الكحول وعوامل الخطر الأيضية معًا، وقد يتجاوز أثرهما المشترك مجموع أثريهما [[easl2024]]. ولم تعد البيانات الحديثة تدعم وجود أثر وقائي للشرب الخفيف، خاصة لدى من لديهم عوامل خطر قلبية أيضية [[easl2024]]. اسأل كل مريض، حتى حيث يكون تناول الكحول غير شائع أو لا يُفصح عنه؛ واستبيان AUDIT-C لا يتجاوز ثلاثة أسئلة [[easl2024]].")),
  ("table", {"caption": ("Table 3. Alcohol intake and the steatotic liver disease categories (EASL–EASD–EASO 2024)", "الجدول 3. تناول الكحول وفئات مرض الكبد التشحّمي (EASL–EASD–EASO 2024)"),
             "head": [("Category", "الفئة"), ("Women (g/day)", "النساء (غ/يوم)"), ("Men (g/day)", "الرجال (غ/يوم)"), ("Advice", "النصيحة")],
             "rows": [
              ["MASLD", "<20", "<30", ("Discourage alcohol", "تثبيط تناول الكحول")],
              ["MetALD", "20–50", "30–60", ("Discourage firmly; aim for abstinence", "تثبيط حازم؛ والهدف الامتناع")],
              [("Alcohol-related liver disease", "مرض الكبد المرتبط بالكحول"), ">50", ">60", ("Abstinence; treat alcohol use disorder", "الامتناع؛ وعلاج اضطراب تعاطي الكحول")],
              [("Any category with advanced fibrosis or cirrhosis", "أي فئة مع تليّف متقدّم أو تشمّع"), "–", "–", ("No alcohol at all, permanently", "لا كحول إطلاقًا وبشكل دائم")],
             ]}),
  ("p", ("The threshold for complete abstinence differs. EASL sets it at advanced fibrosis or cirrhosis, whereas AASLD asks patients with fibrosis stage F2 or more to abstain [[easl2024,aasld2023]]. The global consensus advises minimising alcohol, especially in advanced disease [[global2025]]. AASLD also uses slightly different cut-offs for moderate drinking (21–39 g/day in women, 31–59 g/day in men) [[aasld2023]].",
         "يختلف حد الامتناع التام. فتضعه EASL عند التليّف المتقدّم أو التشمّع، بينما تطلب AASLD من مرضى التليّف بمرحلة F2 فأكثر الامتناع [[easl2024,aasld2023]]. وينصح الإجماع العالمي بتقليل الكحول إلى أدنى حد، خاصة في المرض المتقدّم [[global2025]]. كما تستخدم AASLD حدودًا مختلفة قليلًا للشرب المعتدل (21–39 غ/يوم للنساء و31–59 غ/يوم للرجال) [[aasld2023]].")),
  ("p", ("Smoking adds liver risk. In a meta-analysis of 81 studies, the odds of liver cancer were 1.55 times higher in current smokers and 1.39 times higher in former smokers [[easl2024]]. Advise stopping all tobacco products and offer cessation support; the global consensus lists smoking cessation as part of the lifestyle plan [[global2025]].",
         "يضيف التدخين خطرًا على الكبد. ففي تحليل تجميعي لـ 81 دراسة، كانت احتمالات سرطان الكبد أعلى بـ 1.55 مرة لدى المدخنين الحاليين و1.39 مرة لدى المدخنين السابقين [[easl2024]]. انصح بالتوقف عن جميع منتجات التبغ وقدّم دعم الإقلاع؛ ويعدّ الإجماع العالمي الإقلاع عن التدخين جزءًا من خطة نمط الحياة [[global2025]].")),

  # 6
  ("h2", ("Behaviour change in the clinic", "تغيير السلوك في العيادة"), "behaviour"),
  ("p", ("Advice alone rarely changes weight. EASL describes behavioural therapy as self-monitoring, building the patient's confidence and motivation, setting realistic goals that are negotiated rather than imposed, and working through barriers [[easl2024]]. AASLD adds that a team approach, with dietitians, behavioural specialists and family involvement, does better than physician counselling alone [[aasld2023]].",
         "نادرًا ما تغيّر النصيحة وحدها الوزن. وتصف EASL العلاج السلوكي بأنه المراقبة الذاتية، وبناء ثقة المريض ودافعيته، ووضع أهداف واقعية يُتفاوض عليها لا تُفرض، ومعالجة العوائق [[easl2024]]. وتضيف AASLD أن نهج الفريق، مع أخصائيي التغذية والسلوك وإشراك الأسرة، أنجح من استشارة الطبيب وحده [[aasld2023]].")),
  ("ul", [
   ("Ask about a usual day's food and drink, activity, alcohol and smoking.", "اسأل عن طعام يوم عادي وشرابه، والنشاط، والكحول، والتدخين."),
   ("Explain: link the plan to a number the patient can follow, such as weight, waist or a repeat FIB-4.", "اشرح: اربط الخطة برقم يستطيع المريض متابعته، مثل الوزن أو محيط الخصر أو إعادة FIB-4."),
   ("Agree: choose one or two changes the patient chooses, for example stopping soft drinks and walking after the evening meal.", "اتفق: اختر تغييرًا أو اثنين يختارهما المريض، مثل التوقف عن المشروبات الغازية والمشي بعد وجبة المساء."),
   ("Record: ask the patient to log weight, steps or meals between visits.", "سجّل: اطلب من المريض تدوين الوزن أو الخطوات أو الوجبات بين الزيارات."),
   ("Review: weigh at each visit, praise progress, solve the next barrier, and refer to a dietitian when available.", "راجع: قِس الوزن في كل زيارة، وامدح التقدّم، وعالج العائق التالي، وأحِل إلى أخصائي تغذية عند توفره."),
  ]),

  # 7
  ("h2", ("When lifestyle is not enough", "عندما لا يكفي تعديل نمط الحياة"), "beyond"),
  ("rec", ("GLP-1 receptor agonists are safe in MASH, including compensated cirrhosis, and should be used for their licensed indications of type 2 diabetes and obesity, because they improve cardiometabolic outcomes.", "منبّهات مستقبل GLP-1 آمنة في MASH بما في ذلك التشمّع المعاوَض، وينبغي استخدامها لدواعيها المرخّصة، أي السكري من النوع الثاني والسمنة، لأنها تحسّن المآلات القلبية الأيضية."), 2, "strong", "strong", "easl2024"),
  ("p", ("Obesity medicines make a 10% target reachable: semaglutide 2.4 mg weekly produced a mean weight loss of 14.9% in STEP 1 [[sema2025]]. In ESSENCE, 72 weeks of semaglutide 2.4 mg resolved MASH in 62.9% versus 34.3% on placebo and improved fibrosis in 36.8% versus 22.4%, in patients with F2–F3 fibrosis [[sema2025]]. EASL 2024, written before ESSENCE, did not endorse GLP-1 receptor agonists as MASH-targeted therapy, and does not recommend non-incretin weight-loss drugs for that purpose [[easl2024]]. Approval differs by country: check local (SFDA) approval and the label before prescribing. Lifestyle change continues alongside any drug [[sema2025]].",
         "تجعل أدوية السمنة هدف 10% قابلًا للتحقيق: فقد أدى السيماغلوتايد 2.4 ملغ أسبوعيًا إلى متوسط إنقاص للوزن بلغ 14.9% في STEP 1 [[sema2025]]. وفي تجربة ESSENCE، أزال السيماغلوتايد 2.4 ملغ لمدة 72 أسبوعًا MASH لدى 62.9% مقابل 34.3% مع الدواء الوهمي، وحسّن التليّف لدى 36.8% مقابل 22.4%، لدى مرضى تليّف F2–F3 [[sema2025]]. ولم تعتمد إرشادات EASL 2024، التي صدرت قبل ESSENCE، منبّهات GLP-1 علاجًا موجّهًا لـ MASH، ولا توصي بأدوية إنقاص الوزن غير المعتمدة على الإنكريتين لهذا الغرض [[easl2024]]. وتختلف الموافقات بين الدول، فتحقّق من موافقة الهيئة العامة للغذاء والدواء (SFDA) ومن النشرة الدوائية قبل الوصف. ويستمر تعديل نمط الحياة مع أي دواء [[sema2025]].")),
  ("rec", ("In adults with non-cirrhotic MASLD who meet the indications for metabolic surgery, bariatric surgery should be considered for its lasting liver benefit, diabetes remission and cardiometabolic gains.", "لدى البالغين المصابين بـ MASLD دون تشمّع ممن تنطبق عليهم دواعي الجراحة الأيضية، ينبغي النظر في جراحة السمنة لفائدتها الكبدية الدائمة وتحقيقها هدأة السكري ومكاسبها القلبية الأيضية."), 3, "strong", "strong", "easl2024"),
  ("p", ("The randomised BRAVES trial assigned 288 adults with biopsy-proven steatohepatitis to lifestyle plus best medical care, Roux-en-Y gastric bypass or sleeve gastrectomy. At one year, steatohepatitis resolved without worsening fibrosis in 56% after bypass and 57% after sleeve gastrectomy, against 16% with lifestyle care; 6% of surgical patients had a severe adverse event, and none died [[braves2023]]. In a French cohort of 180 patients, steatohepatitis had resolved in 84% at five years and fibrosis had decreased in 70% [[lassailly]].",
         "وزّعت تجربة BRAVES العشوائية 288 بالغًا بالتهاب كبد دهني مثبت بالخزعة على تعديل نمط الحياة مع أفضل رعاية طبية، أو تحويل المعدة بطريقة Roux-en-Y، أو تكميم المعدة. وبعد سنة زال التهاب الكبد الدهني دون تفاقم التليّف لدى 56% بعد التحويل و57% بعد التكميم، مقابل 16% مع رعاية نمط الحياة؛ وأصيب 6% من مرضى الجراحة بحدث سلبي شديد ولم تحدث وفيات [[braves2023]]. وفي دراسة فرنسية شملت 180 مريضًا، زال التهاب الكبد الدهني لدى 84% بعد خمس سنوات وتراجع التليّف لدى 70% [[lassailly]].")),
  ("p", ("Indications follow body mass index and comorbidity, and surgical societies updated them in 2022 [[asmbs2022]]. EASL summarises them as BMI 40 kg/m² or more; 35–40 with comorbidities; or 30–35 with poorly controlled type 2 diabetes or hypertension despite optimal medical therapy, with lower thresholds in Asian populations [[easl2024]].",
         "تُحدَّد الدواعي بمؤشر كتلة الجسم والأمراض المصاحبة، وقد حدّثتها الجمعيات الجراحية عام 2022 [[asmbs2022]]. وتلخّصها EASL بمؤشر كتلة 40 كغ/م² فأكثر، أو 35–40 مع أمراض مصاحبة، أو 30–35 مع سكري من النوع الثاني أو ارتفاع ضغط غير منضبطين رغم العلاج الطبي الأمثل، مع حدود أدنى لدى الشعوب الآسيوية [[easl2024]].")),
  ("rec", ("In compensated advanced chronic liver disease or compensated cirrhosis, bariatric surgery can be considered only after careful review of the indication, type of operation and portal hypertension by an experienced multidisciplinary team.", "في المرض الكبدي المزمن المتقدّم المعاوَض أو التشمّع المعاوَض، يمكن النظر في جراحة السمنة فقط بعد مراجعة دقيقة للداعي ونوع العملية وارتفاع ضغط الوريد البابي من قبل فريق متعدد التخصصات ذي خبرة."), 4, "weak", "strong", "easl2024"),
  ("p", ("Cirrhosis changes the balance. People with decompensated cirrhosis are about ten times more likely to die after bariatric surgery than those whose cirrhosis is compensated; EASL avoids surgery with clinically significant portal hypertension except in highly selected cases in expert centres [[easl2024]]. EASL, AASLD and the Saudi consensus all treat decompensated cirrhosis as a contraindication unless surgery is part of liver transplant planning [[easl2024,aasld2023,saudi2026]]. Endoscopic bariatric procedures are not yet recommended as MASH treatment [[easl2024,saudi2026]].",
         "يغيّر التشمّع الموازنة. فلدى مرضى التشمّع غير المعاوَض خطر وفاة بعد جراحة السمنة أعلى بنحو 10 أضعاف من مرضى التشمّع المعاوَض، وتتجنّب EASL الجراحة مع ارتفاع ضغط الوريد البابي المهم سريريًا إلا في حالات منتقاة بعناية وفي مراكز خبيرة [[easl2024]]. وتعدّ EASL وAASLD والإجماع السعودي التشمّع غير المعاوَض مانعًا للجراحة ما لم تكن ضمن التخطيط لزراعة الكبد [[easl2024,aasld2023,saudi2026]]. ولا يُوصى بعد بإجراءات السمنة بالمنظار علاجًا لـ MASH [[easl2024,saudi2026]].")),

  # 8
  ("h2", ("Muscle, cirrhosis and older adults", "العضلات والتشمّع وكبار السن"), "muscle"),
  ("rec", ("In sarcopenia, sarcopenic obesity or decompensated cirrhosis, provide a high-protein diet and a late-evening snack.", "في ضمور العضلات أو السمنة الساركوبينية أو التشمّع غير المعاوَض، قدّم غذاءً عالي البروتين ووجبة خفيفة في آخر المساء."), 2, "strong", "consensus", "easl2024"),
  ("rec", ("In compensated cirrhosis with obesity, moderate weight loss can be suggested, with high protein intake and physical activity to protect muscle.", "في التشمّع المعاوَض مع السمنة، يمكن اقتراح إنقاص معتدل للوزن، مع تناول بروتين مرتفع ونشاط بدني لحماية العضلات."), 3, "weak", "strong", "easl2024"),
  ("p", ("Sarcopenia affects 50–60% of people with cirrhosis awaiting transplantation, and sarcopenic obesity, low muscle with excess fat, is found in 20–35% of people with cirrhosis around transplantation [[easl2024]]. In non-obese patients with cirrhosis, most nutrition plans supply at least 35 kcal/kg/day and 1.2–1.5 g/kg/day of protein. For obese patients with compensated cirrhosis, the EASL nutrition guideline cited in 2024 suggests 5–10% weight loss on a moderately hypocaloric diet (500–800 kcal/day below needs) while keeping protein above 1.5 g/kg of ideal body weight [[easl2024]]. Avoid long gaps without food: eat every 4–6 hours and add a late-evening snack [[easl2024]].",
         "يصيب ضمور العضلات 50–60% من مرضى التشمّع المنتظرين لزراعة الكبد، وتوجد السمنة الساركوبينية، أي قلة العضلات مع فرط الدهون، لدى 20–35% من مرضى التشمّع قبل الزراعة وبعدها [[easl2024]]. ولدى مرضى التشمّع غير المصابين بالسمنة، توفّر معظم خطط التغذية 35 كيلوكالوري/كغ/يوم على الأقل و1.2–1.5 غ/كغ/يوم من البروتين. ولمرضى السمنة مع تشمّع معاوَض، تقترح إرشادات EASL للتغذية المذكورة في إرشادات 2024 إنقاص الوزن بنسبة 5–10% بحمية معتدلة الانخفاض في السعرات (أقل من الاحتياج بـ 500–800 كيلوكالوري يوميًا) مع إبقاء البروتين فوق 1.5 غ/كغ من الوزن المثالي [[easl2024]]. وتجنّب الفترات الطويلة دون طعام: وجبة كل 4–6 ساعات مع وجبة خفيفة في آخر المساء [[easl2024]].")),
  ("aside", ("With semaglutide, lean mass makes up about 39% of the weight lost. AASLD advises resistance exercise and protein of 1.2–1.5 g/kg/day to limit muscle loss [[sema2025]].",
             "مع السيماغلوتايد تشكّل الكتلة غير الدهنية نحو 39% من الوزن المفقود، وتنصح AASLD بتمارين المقاومة وبروتين بمقدار 1.2–1.5 غ/كغ/يوم للحد من فقدان العضلات [[sema2025]].")),
  ("p", ("Muscle loss on GLP-1 therapy is more marked in older people and in those with sarcopenia [[sema2025]]. In older patients, put strength and protein first and set modest weight goals.",
         "خسارة العضلات مع علاج GLP-1 أوضح لدى كبار السن ولدى المصابين بضمور العضلات [[sema2025]]. لذا ضع القوة العضلية والبروتين أولًا لدى المرضى المسنّين، وحدّد أهدافًا متواضعة للوزن.")),

  # 9
  ("h2", ("Our region: Saudi consensus and Ramadan", "منطقتنا: الإجماع السعودي ورمضان"), "region"),
  ("p", ("The Saudi 2026 consensus recommends lifestyle change for patients with excess body fat: structured, individualised exercise, a healthy diet with less saturated fat and starch, and weight loss of at least 5%, ideally more than 10%, together with control of metabolic risk factors (high level of evidence). It also advises diet and exercise for normal-weight MASLD (moderate evidence) [[saudi2026]]. It sets bariatric thresholds for Saudi patients at BMI 35–39.99 kg/m² with comorbidities and 40 or more without, and calls for a multidisciplinary review before surgery in well-compensated cirrhosis [[saudi2026]].",
         "يوصي الإجماع السعودي 2026 بتعديل نمط الحياة لمن لديهم فرط في دهون الجسم: برامج تمارين منظّمة ومفصّلة على المريض، وغذاء صحي أقل في الدهون المشبعة والنشويات، وإنقاص الوزن 5% على الأقل والأفضل أكثر من 10%، مع ضبط عوامل الخطر الأيضية (مستوى دليل مرتفع). كما ينصح بالغذاء والتمارين في MASLD لدى ذوي الوزن الطبيعي (دليل متوسط) [[saudi2026]]. ويحدد عتبات جراحة السمنة للمرضى السعوديين بمؤشر كتلة 35–39.99 كغ/م² مع أمراض مصاحبة، و40 فأكثر دون أمراض مصاحبة، ويطلب مراجعة متعددة التخصصات قبل الجراحة في التشمّع جيد المعاوضة [[saudi2026]].")),
  ("p", ("A 2025 meta-analysis of Ramadan fasting pooled eight small studies (603 people with metabolic dysfunction-associated fatty liver disease), most at serious risk of bias. It found slightly more weight loss in those who fasted (about 1.4 kg) than in non-fasters, while changes in ALT and AST were similar in both groups [[ramadanma2025]]. The evidence is too weak to present fasting as a liver treatment. A recent Saudi review calls for risk-stratified, culturally sensitive advice across the spectrum from MASLD to cirrhosis and transplantation [[ramadanrev2026]].",
         "جمع تحليل تجميعي عام 2025 عن صيام رمضان ثماني دراسات صغيرة (603 مصابين بمرض الكبد الدهني المرتبط بخلل التمثيل الغذائي)، معظمها بخطر تحيّز كبير، ووجد إنقاصًا أكبر قليلًا للوزن لدى الصائمين (نحو 1.4 كغ) مقارنة بغير الصائمين، بينما كانت التغيرات في ALT وAST متشابهة في المجموعتين [[ramadanma2025]]. والأدلة أضعف من أن يُقدَّم الصيام علاجًا للكبد. وتدعو مراجعة سعودية حديثة إلى نصائح مراعية للثقافة ومصنّفة حسب الخطورة، تشمل الطيف من MASLD إلى التشمّع والزراعة [[ramadanrev2026]].")),
  ("ul", [
   ("Plan before Ramadan: review diabetes medicines and doses with the patient's diabetes team, especially insulin and sulfonylureas.", "خطّط قبل رمضان: راجع أدوية السكري وجرعاتها مع فريق السكري المعالج، خاصة الإنسولين والسلفونيل يوريا."),
   ("Use the month: suhoor and iftar are a chance to cut sugary drinks, fried foods and sweets.", "استثمر الشهر: السحور والإفطار فرصة لتقليل المشروبات المحلّاة والمقليات والحلويات."),
   ("Cirrhosis needs an individual decision: EASL advises short gaps between meals and a late-evening snack, which a long daytime fast does not allow [[easl2024]].", "يحتاج التشمّع إلى قرار فردي: إذ تنصح EASL بفترات قصيرة بين الوجبات ووجبة خفيفة في آخر المساء، وهو ما لا يتيحه صيام النهار الطويل [[easl2024]]."),
  ]),

  # 10
  ("h2", ("Clinical case", "حالة سريرية"), "case"),
  ("case", {"title": ("A 46-year-old man with diabetes and a sweet tooth", "رجل عمره 46 عامًا مصاب بالسكري ويحب السكريات"),
            "parts": [
             (("Presentation", "العرض"), ("Office worker in Jeddah with type 2 diabetes for three years, on metformin; HbA1c 7.4%. Weight 98 kg, height 1.70 m: BMI = 98 ÷ (1.70 × 1.70) = 98 ÷ 2.89 = 33.9 kg/m². Ultrasound shows steatosis. AST 38 U/L, ALT 52 U/L, platelets 245 ×10⁹/L. He drinks three to four cans of soft drink and several cups of sweet tea a day, eats rice at lunch and dinner, and snacks on dates. He is inactive, smokes 10 cigarettes a day, and drinks no alcohol (AUDIT-C 0).", "موظف مكتبي في جدة مصاب بالسكري من النوع الثاني منذ ثلاث سنوات ويتناول الميتفورمين، وHbA1c ‏7.4%. الوزن 98 كغ والطول 1.70 م: مؤشر الكتلة = 98 ÷ (1.70 × 1.70) = 98 ÷ 2.89 = 33.9 كغ/م². تُظهر الأشعة الصوتية تشحّمًا. AST ‏38 وحدة/ل، وALT ‏52 وحدة/ل، والصفائح 245 ×10⁹/ل. يشرب ثلاث إلى أربع علب من المشروبات الغازية وعدة أكواب من الشاي المحلّى يوميًا، ويأكل الأرز في الغداء والعشاء، ويتناول التمر بين الوجبات. قليل الحركة، ويدخّن 10 سجائر يوميًا، ولا يتناول الكحول (AUDIT-C صفر).")),
             (("Risk assessment", "تقييم الخطورة"), ("FIB-4 = (46 × 38) ÷ (245 × √52) = 1,748 ÷ (245 × 7.21) = 1,748 ÷ 1,767 = 0.99. This is below 1.3, so advanced fibrosis is unlikely. The main task is lifestyle and cardiometabolic care in primary care.", "FIB-4 = (46 × 38) ÷ (245 × √52) = 1,748 ÷ (245 × 7.21) = 1,748 ÷ 1,767 = 0.99، وهي أقل من 1.3، لذا فالتليّف المتقدّم غير مرجّح. والمهمة الأساسية هي رعاية نمط الحياة وعوامل الخطر القلبية الأيضية في الرعاية الأولية.")),
             (("The prescription", "الوصفة"), ("First target 5%: 98 × 0.05 = 4.9 kg, to about 93 kg. Longer-term target 10%: 9.8 kg, to about 88 kg. He chooses two changes: water instead of soft drinks, and tea with less sugar each week until none. Rice portion halved, with vegetables and legumes; dates counted as fruit. Walking after the evening meal, building up to more than 150 minutes a week, plus body-weight exercises. Smoking cessation clinic referral. He plans to fast in Ramadan, so his diabetes plan is reviewed beforehand.", "الهدف الأول 5%: 98 × 0.05 = 4.9 كغ، أي إلى نحو 93 كغ. والهدف الأبعد 10%: 9.8 كغ، أي إلى نحو 88 كغ. يختار تغييرين: الماء بدل المشروبات الغازية، وتقليل سكر الشاي كل أسبوع حتى الاستغناء عنه. وتُخفَّض حصة الأرز إلى النصف مع الخضروات والبقوليات، ويُحسب التمر حصة فاكهة. ويمشي بعد وجبة المساء حتى يتجاوز 150 دقيقة أسبوعيًا، مع تمارين بوزن الجسم. ويُحال إلى عيادة الإقلاع عن التدخين. وينوي صيام رمضان، فتُراجع خطة السكري قبله.")),
             (("Six months later", "بعد ستة أشهر"), ("Weight 91.0 kg: loss = 7.0 kg, and 7.0 ÷ 98 = 7.1%. BMI = 91 ÷ 2.89 = 31.5 kg/m². ALT has fallen to 34 U/L. He has stopped soft drinks and cut down to 4 cigarettes a day. He has passed the 5% target and is within the 7–10% band; the plan continues toward 10%. If weight loss stalls, a GLP-1 receptor agonist for his diabetes and obesity is a reasonable next step, after checking local SFDA approval and the label.", "الوزن 91.0 كغ: أي فقد 7.0 كغ، و7.0 ÷ 98 = 7.1%. ومؤشر الكتلة = 91 ÷ 2.89 = 31.5 كغ/م². وانخفض ALT إلى 34 وحدة/ل. توقّف عن المشروبات الغازية وقلّل التدخين إلى 4 سجائر يوميًا. تجاوز هدف 5% وأصبح ضمن نطاق 7–10%، وتستمر الخطة نحو 10%. وإذا توقّف نزول الوزن، فإن منبّه مستقبل GLP-1 للسكري والسمنة خطوة تالية معقولة، بعد التحقق من موافقة SFDA المحلية والنشرة الدوائية.")),
             (("Teaching points", "نقاط تعليمية"), ("Two changes chosen by the patient beat a long list of rules, and targets in kilograms are easier to follow than percentages. A low FIB-4 decides where care happens, not whether lifestyle change is needed.", "تغييران يختارهما المريض أفضل من قائمة طويلة من القواعد، والأهداف بالكيلوغرامات أسهل في المتابعة من النسب المئوية. ويحدد FIB-4 المنخفض مكان الرعاية، لا الحاجة إلى تعديل نمط الحياة.")),
            ]}),

  # 11
  ("h2", ("Test yourself", "اختبر نفسك"), "quiz"),
  ("mcq", [
   {"q": ("According to EASL–EASD–EASO 2024, what sustained weight loss is needed to improve fibrosis?", "وفق EASL–EASD–EASO 2024، ما مقدار إنقاص الوزن المستدام اللازم لتحسين التليّف؟"),
    "options": [("3%", "3%"), ("5%", "5%"), ("7%", "7%"), ("10% or more", "10% أو أكثر")],
    "answer": 3,
    "why": ("EASL links at least 5% to less liver fat, 7–10% to less inflammation and at least 10% to fibrosis improvement.", "تربط EASL نسبة 5% على الأقل بخفض دهون الكبد، و7–10% بتخفيف الالتهاب، و10% على الأقل بتحسّن التليّف.")},
   {"q": ("A man with type 2 diabetes and steatosis drinks about 40 g of alcohol a day. How is he classified?", "رجل مصاب بالسكري من النوع الثاني وتشحّم الكبد يتناول نحو 40 غ من الكحول يوميًا. كيف يُصنّف؟"),
    "options": [("MASLD", "MASLD"), ("MetALD", "MetALD"), ("Alcohol-related liver disease", "مرض الكبد المرتبط بالكحول"), ("Cannot be classified", "لا يمكن تصنيفه")],
    "answer": 1,
    "why": ("In men, 30–60 g/day with a cardiometabolic risk factor defines MetALD. He should be firmly advised to stop.", "لدى الرجال يُعرَّف MetALD بتناول 30–60 غ/يوم مع عامل خطر قلبي أيضي، ويجب نصحه بحزم بالتوقف.")},
   {"q": ("Which activity target does EASL recommend for adults with MASLD?", "ما هدف النشاط البدني الذي توصي به EASL للبالغين المصابين بـ MASLD؟"),
    "options": [("More than 150 min/week moderate or 75 min/week vigorous activity", "أكثر من 150 دقيقة أسبوعيًا من النشاط المعتدل أو 75 دقيقة من النشاط الشديد"), ("10,000 steps every day", "10,000 خطوة يوميًا"), ("Resistance training only", "تمارين المقاومة فقط"), ("Exercise only if weight loss fails", "التمارين فقط إذا فشل إنقاص الوزن")],
    "answer": 0,
    "why": ("EASL recommends more than 150 minutes of moderate or 75 minutes of vigorous activity a week, tailored to the patient; exercise lowers liver fat even without weight loss.", "توصي EASL بأكثر من 150 دقيقة من النشاط المعتدل أو 75 دقيقة من النشاط الشديد أسبوعيًا بما يلائم المريض، والتمارين تخفض دهون الكبد حتى دون إنقاص الوزن.")},
   {"q": ("A patient with decompensated MASH cirrhosis and BMI 41 asks about sleeve gastrectomy. What is the best answer?", "مريض بتشمّع MASH غير معاوَض ومؤشر كتلة 41 يسأل عن تكميم المعدة. ما أفضل إجابة؟"),
    "options": [("Proceed, as BMI over 40 is a clear indication", "المضي فيها لأن مؤشر الكتلة فوق 40 داعٍ واضح"), ("Offer an intragastric balloon instead", "عرض بالون المعدة بديلًا"), ("Surgery is contraindicated unless planned with liver transplantation", "الجراحة ممنوعة ما لم يُخطط لها مع زراعة الكبد"), ("Proceed after three months of diet", "المضي فيها بعد ثلاثة أشهر من الحمية")],
    "answer": 2,
    "why": ("Decompensated cirrhosis carries about a 10-fold higher surgical mortality; EASL, AASLD and the Saudi consensus all advise against surgery outside transplant planning.", "يحمل التشمّع غير المعاوَض خطر وفاة جراحية أعلى بنحو 10 أضعاف، وتنصح EASL وAASLD والإجماع السعودي جميعها بعدم الجراحة خارج التخطيط للزراعة.")},
   {"q": ("A 68-year-old woman on semaglutide has lost 12% of her weight. What should you add?", "امرأة عمرها 68 عامًا تتناول السيماغلوتايد وفقدت 12% من وزنها. ماذا تضيف؟"),
    "options": [("A ketogenic diet to speed weight loss", "حمية كيتونية لتسريع النزول"), ("Resistance exercise and protein 1.2–1.5 g/kg/day", "تمارين مقاومة وبروتين 1.2–1.5 غ/كغ/يوم"), ("Stop all exercise to save energy", "إيقاف التمارين لتوفير الطاقة"), ("Vitamin and herbal supplements for the liver", "مكمّلات فيتامينات وأعشاب للكبد")],
    "answer": 1,
    "why": ("About 39% of weight lost on semaglutide is lean mass, more so in older adults; AASLD advises resistance exercise and adequate protein.", "نحو 39% من الوزن المفقود مع السيماغلوتايد كتلة غير دهنية، وأكثر لدى كبار السن، وتنصح AASLD بتمارين المقاومة والبروتين الكافي.")},
  ]),

  # 12
  ("h2", ("Key messages", "الرسائل الأساسية"), "summary"),
  ("ul", [
   ("Lifestyle change is the first treatment at every stage of MASLD and continues alongside drugs or surgery.", "تعديل نمط الحياة هو العلاج الأول في كل مراحل MASLD ويستمر مع الأدوية أو الجراحة."),
   ("Targets (EASL): at least 5% weight loss for fat, 7–10% for inflammation, at least 10% for fibrosis; plan for maintenance.", "الأهداف (EASL): إنقاص الوزن 5% على الأقل للدهون، و7–10% للالتهاب، و10% على الأقل للتليّف؛ مع التخطيط للمحافظة."),
   ("Cut sugary drinks, added sugar, refined starch and ultra-processed food; move more than 150 minutes a week, with resistance work.", "قلّل المشروبات المحلّاة والسكر المضاف والنشويات المكرّرة والأغذية فائقة المعالجة، وتحرّك أكثر من 150 دقيقة أسبوعيًا مع تمارين المقاومة."),
   ("Ask about alcohol and tobacco in everyone; no alcohol at all with advanced fibrosis or cirrhosis (AASLD: from F2).", "اسأل الجميع عن الكحول والتبغ؛ ولا كحول إطلاقًا مع التليّف المتقدّم أو التشمّع (ووفق AASLD من F2)."),
   ("Add obesity medicines or metabolic surgery when lifestyle is not enough; in cirrhosis protect muscle and avoid surgery once decompensated.", "أضف أدوية السمنة أو الجراحة الأيضية عندما لا يكفي نمط الحياة؛ وفي التشمّع احمِ العضلات وتجنّب الجراحة عند عدم المعاوضة."),
  ]),
 ],
}
