# -*- coding: utf-8 -*-
"""
Physician reference library (English + Arabic).
Each topic becomes its own page: ref/<slug>.html and ar/ref/<slug>.html.
Edit text here, then run:  python3 build.py

Text pairs are written as (English, Arabic).
A table cell can be a plain string (same in both languages) or a pair.

Fields
  slug      page address
  group     section on the index page (see GROUPS)
  title     {en, ar}
  lead      one-line summary {en, ar}
  key       "Key points" box: list of pairs
  sections  list of {h: pair, p: [pairs], ul: [pairs], table: {head: [cells], rows: [[cells]]}, note: pair}
  see       related slugs
  src       source keys (SOURCES here, or learn.SOURCES)
"""

UPDATED = "2026-10-03"
NEXT_REVIEW = "2027-10"
# Medical review record. When you have reviewed a page, add:  "slug": "YYYY-MM-DD",
# The page will then show "Medically reviewed by Dr. Mahmoud Desoky on <date>".
REVIEWED = {
}
# Version per page (default "1.0"). Raise it when the medical meaning of a page changes.
VERSIONS = {
}

GROUPS = [
    ("diagnose", {"en": "Diagnose and stage", "ar": "التشخيص وتقييم المرحلة"}),
    ("treat",    {"en": "Treat",              "ar": "العلاج"}),
    ("follow",   {"en": "Follow up and special groups", "ar": "المتابعة والفئات الخاصة"}),
    ("context",  {"en": "Guidelines and our region", "ar": "الإرشادات ومنطقتنا"}),
]

# Extra sources for doctors (all checked on PubMed). Keys from content/learn.py also work.
SOURCES = {
    "maestro": ("Harrison SA, et al. A phase 3, randomized, controlled trial of resmetirom in NASH with liver fibrosis (MAESTRO-NASH). N Engl J Med 2024;390:497–509.", "https://doi.org/10.1056/NEJMoa2309000"),
    "essence": ("Sanyal AJ, et al. Phase 3 trial of semaglutide in metabolic dysfunction-associated steatohepatitis (ESSENCE). N Engl J Med 2025;392:2089–99.", "https://doi.org/10.1056/NEJMoa2413258"),
    "baveno7": ("de Franchis R, et al. Baveno VII – Renewing consensus in portal hypertension. J Hepatol 2022;76:959–74.", "https://doi.org/10.1016/j.jhep.2021.12.022"),
    "nfs":     ("Angulo P, et al. The NAFLD fibrosis score: a noninvasive system that identifies liver fibrosis in patients with NAFLD. Hepatology 2007;45:846–54.", "https://doi.org/10.1002/hep.21496"),
    "fib4":    ("Sterling RK, et al. Development of a simple noninvasive index to predict significant fibrosis in patients with HIV/HCV coinfection. Hepatology 2006;43:1317–25.", "https://doi.org/10.1002/hep.21178"),
    "shah":    ("Shah AG, et al. Comparison of noninvasive markers of fibrosis in patients with nonalcoholic fatty liver disease. Clin Gastroenterol Hepatol 2009;7:1104–12.", "https://doi.org/10.1016/j.cgh.2009.05.033"),
    "mcpherson": ("McPherson S, et al. Age as a confounding factor for the accurate non-invasive diagnosis of advanced NAFLD fibrosis. Am J Gastroenterol 2017;112:740–51.", "https://doi.org/10.1038/ajg.2016.453"),
    "apri":    ("Wai CT, et al. A simple noninvasive index can predict both significant fibrosis and cirrhosis in patients with chronic hepatitis C. Hepatology 2003;38:518–26.", "https://doi.org/10.1053/jhep.2003.50346"),
    "nit2021": ("EASL Clinical Practice Guidelines on non-invasive tests for evaluation of liver disease severity and prognosis – 2021 update. J Hepatol 2021;75:659–89.", "https://doi.org/10.1016/j.jhep.2021.05.025"),
    "vilar":   ("Vilar-Gomez E, et al. Weight loss through lifestyle modification significantly reduces features of nonalcoholic steatohepatitis. Gastroenterology 2015;149:367–78.", "https://doi.org/10.1053/j.gastro.2015.04.005"),
    "aga2021": ("Kanwal F, et al. Clinical care pathway for the risk stratification and management of patients with NAFLD (AGA). Gastroenterology 2021;161:1657–69.", "https://doi.org/10.1053/j.gastro.2021.07.049"),
    "aace2022": ("Cusi K, et al. AACE clinical practice guideline for the diagnosis and management of NAFLD in primary care and endocrinology clinical settings. Endocr Pract 2022;28:528–62.", "https://doi.org/10.1016/j.eprac.2022.03.010"),
    "naspghan": ("Vos MB, et al. NASPGHAN clinical practice guideline for the diagnosis and treatment of NAFLD in children. J Pediatr Gastroenterol Nutr 2017;64:319–34.", "https://doi.org/10.1097/MPG.0000000000001482"),
    "lassailly": ("Lassailly G, et al. Bariatric surgery provides long-term resolution of NASH and regression of fibrosis. Gastroenterology 2020;159:1290–1301.", "https://doi.org/10.1053/j.gastro.2020.06.006"),
    "resm2024": ("Chen VL, et al. Resmetirom therapy for MASLD: October 2024 updates to AASLD Practice Guidance. Hepatology 2025;81(1):312–20.", "https://doi.org/10.1097/HEP.0000000000001112"),
    "noureddin2024": ("Noureddin M, et al. Expert panel recommendations: practical clinical applications for initiating and monitoring resmetirom in patients with MASH and moderate to noncirrhotic advanced fibrosis. Clin Gastroenterol Hepatol 2024;22(12):2367–77.", "https://doi.org/10.1016/j.cgh.2024.07.003"),
    "peds2025": ("Xanthakos SA, et al. AASLD Practice Statement on the evaluation and management of MASLD in children. Hepatology 2025;82(5):1352–94.", "https://doi.org/10.1097/HEP.0000000000001368"),
    "apasl2025": ("Eslam M, et al. APASL clinical practice guidelines for the diagnosis and management of metabolic dysfunction-associated fatty liver disease. Hepatol Int 2025;19(2):261–301.", "https://doi.org/10.1007/s12072-024-10774-3"),
    "china2024": ("Fan JG, et al. Guideline for the prevention and treatment of metabolic dysfunction-associated fatty liver disease (version 2024). J Clin Transl Hepatol 2024;12(11):955–74.", "https://doi.org/10.14218/JCTH.2024.00311"),
    "egypt2022": ("Fouad Y, et al. The Egyptian clinical practice guidelines for the diagnosis and management of metabolic associated fatty liver disease. Saudi J Gastroenterol 2022;28(1):3–20.", "https://doi.org/10.4103/sjg.sjg_357_21"),
    "braves2023": ("Verrastro O, et al. Bariatric–metabolic surgery versus lifestyle intervention plus best medical care in NASH (BRAVES): a multicentre, open-label, randomised trial. Lancet 2023;401(10390):1786–97.", "https://doi.org/10.1016/S0140-6736(23)00634-7"),
    "sanai2021": ("Sanai FM, et al. Clinical and economic burden of NASH in Saudi Arabia, United Arab Emirates and Kuwait. Hepatol Int 2021;15(4):912–21.", "https://doi.org/10.1007/s12072-021-10182-x"),
    "mena2024": ("Younossi ZM, et al. Prevalence of MASLD in the Middle East and North Africa. Liver Int 2024;44(4):1061–70.", "https://doi.org/10.1111/liv.15852"),
    "ksaburden2024": ("Alqahtani SA, et al. The burden of MASLD and viral hepatitis in Saudi Arabia. Saudi J Gastroenterol 2024;30(5):310–8.", "https://doi.org/10.4103/sjg.sjg_62_24"),
    "stigma2024": ("Alqahtani SA, et al. Stigma in steatotic liver disease: a survey of patients from Saudi Arabia. Saudi J Gastroenterol 2024;30(5):335–41.", "https://doi.org/10.4103/sjg.sjg_122_24"),
    "menaknow2025": ("Alqahtani SA, et al. Knowledge about MASLD among medical professionals from countries in the MENA region. Ann Hepatol 2025;30(1):101569.", "https://doi.org/10.1016/j.aohep.2024.101569"),
    "menagbd2025": ("Sarkoohi Z, et al. Epidemiological trends and burden of MASLD in the Middle East and North Africa region: a 32-year analysis. J Health Popul Nutr 2025;44(1):207.", "https://doi.org/10.1186/s41043-025-00973-5"),
    "arabbiblio2025": ("Alhazzani W, et al. A bibliometric analysis of a decade's research on MASLD in the Arab world. Saudi J Gastroenterol 2025;31(3):157–67.", "https://doi.org/10.4103/sjg.sjg_431_24"),
    "asmbs2022": ("Eisenberg D, et al. 2022 ASMBS and IFSO indications for metabolic and bariatric surgery. Surg Obes Relat Dis 2022;18:1345–56.", "https://doi.org/10.1016/j.soard.2022.08.013"),
}

PAGES = [
# =================================================================== DIAGNOSE
{
 "slug": "definitions", "group": "diagnose",
 "title": {"en": "Definitions and diagnosis of MASLD", "ar": "تعريف الكبد الدهني الأيضي (MASLD) وتشخيصه"},
 "lead": {"en": "Steatosis plus at least one cardiometabolic risk factor, with no other cause, is MASLD.",
          "ar": "وجود تشحّم الكبد مع عامل خطر قلبي أيضي واحد على الأقل، دون سبب آخر، يعني MASLD."},
 "key": [
  ("MASLD = hepatic steatosis (imaging, biopsy or CAP) + ≥1 of 5 cardiometabolic criteria.",
   "MASLD = تشحّم كبدي (بالتصوير أو الخزعة أو CAP) + معيار واحد على الأقل من 5 معايير قلبية أيضية."),
  ("MASH is the inflammatory form. It is still a histological diagnosis.",
   "MASH هو الشكل الالتهابي، ويظل تشخيصه نسيجيًا."),
  ("MetALD = MASLD plus moderate alcohol intake (140–350 g/week women, 210–420 g/week men).",
   "MetALD = MASLD مع تناول كحول بكمية متوسطة (140–350 غ/أسبوع للنساء، و210–420 غ/أسبوع للرجال)."),
  ("Always look for other causes before labelling MASLD.",
   "ابحث دائمًا عن الأسباب الأخرى قبل تشخيص MASLD."),
 ],
 "sections": [
  {"h": ("The five cardiometabolic criteria (adults)", "المعايير القلبية الأيضية الخمسة (للبالغين)"),
   "p": [("One is enough. Each criterion also counts if the patient is on treatment for it.",
          "يكفي معيار واحد. ويُحتسب المعيار أيضًا إذا كان المريض يتلقى علاجًا له.")],
   "table": {"head": [("Criterion", "المعيار"), ("Threshold", "الحد")],
             "rows": [
              [("Weight", "الوزن"), ("BMI ≥25 kg/m² (≥23 in Asian people), or waist >94 cm men / >80 cm women (>90 cm men in South Asian and Chinese people)", "مؤشر كتلة الجسم ≥25 كغ/م² (≥23 للآسيويين)، أو محيط الخصر >94 سم للرجال و>80 سم للنساء (>90 سم للرجال من جنوب آسيا والصين)")],
              [("Glucose", "السكر"), ("Fasting glucose ≥5.6 mmol/L (100 mg/dL), 2-h glucose ≥7.8 mmol/L (140 mg/dL), HbA1c ≥5.7%, or type 2 diabetes", "سكر صائم ≥5.6 مليمول/ل (100 ملغ/دل)، أو سكر بعد ساعتين ≥7.8 مليمول/ل (140 ملغ/دل)، أو HbA1c ≥5.7%، أو سكري من النوع الثاني")],
              [("Blood pressure", "ضغط الدم"), ("≥130/85 mmHg", "≥130/85 ملم زئبق")],
              [("Triglycerides", "الدهون الثلاثية"), ("≥1.70 mmol/L (150 mg/dL)", "≥1.70 مليمول/ل (150 ملغ/دل)")],
              [("HDL cholesterol", "الكوليسترول النافع HDL"), ("≤1.0 mmol/L (40 mg/dL) men, ≤1.3 mmol/L (50 mg/dL) women", "≤1.0 مليمول/ل (40 ملغ/دل) للرجال، و≤1.3 مليمول/ل (50 ملغ/دل) للنساء")],
             ]}},
  {"h": ("The steatotic liver disease family", "عائلة أمراض الكبد التشحّمي"),
   "table": {"head": [("Term", "المصطلح"), ("Meaning", "المعنى")],
             "rows": [
              ["SLD", ("Steatotic liver disease: the umbrella term for any fatty liver", "مرض الكبد التشحّمي: المصطلح الجامع لكل أنواع الكبد الدهني")],
              ["MASLD", ("Steatosis + ≥1 cardiometabolic criterion, little or no alcohol", "تشحّم + معيار قلبي أيضي واحد على الأقل، مع كحول قليل أو معدوم")],
              ["MASH", ("MASLD with steatohepatitis (inflammation and ballooning) on biopsy", "MASLD مع التهاب كبدي دهني (التهاب وتضخّم الخلايا) في الخزعة")],
              ["MetALD", ("MASLD + 140–350 g/week (women) or 210–420 g/week (men) alcohol", "MASLD + كحول 140–350 غ/أسبوع (نساء) أو 210–420 غ/أسبوع (رجال)")],
              ["ALD", ("Alcohol-related liver disease: above those amounts", "مرض الكبد المرتبط بالكحول: فوق هذه الكميات")],
              [("Specific causes", "أسباب محددة"), ("Drug-induced, monogenic, other (e.g. Wilson disease, HCV genotype 3)", "دوائي، أو وراثي أحادي الجين، أو غيره (مثل داء ويلسون، والتهاب الكبد C النمط 3)")],
              [("Cryptogenic SLD", "SLD مجهول السبب"), ("Steatosis with no cardiometabolic criterion and no other cause", "تشحّم دون معيار قلبي أيضي ودون سبب آخر")],
             ]}},
  {"h": ("Rule out other causes", "استبعاد الأسباب الأخرى"),
   "p": [("A standard first work-up for raised liver tests or steatosis:", "التقييم الأولي المعتاد لارتفاع إنزيمات الكبد أو التشحّم:")],
   "ul": [
    ("Alcohol history in grams per week; AUDIT-C helps.", "تاريخ الكحول بالغرامات أسبوعيًا، ويفيد استبيان AUDIT-C."),
    ("HBsAg and anti-HCV.", "HBsAg وanti-HCV."),
    ("Medicines: amiodarone, methotrexate, tamoxifen, corticosteroids, valproate, some antiretrovirals.", "الأدوية: الأميودارون، والميثوتريكسات، والتاموكسيفين، والكورتيزون، والفالبروات، وبعض مضادات الفيروسات القهقرية."),
    ("Ferritin and transferrin saturation. A high ferritin is common in MASLD; check saturation before thinking of haemochromatosis.", "الفيريتين وتشبّع الترانسفيرين. ارتفاع الفيريتين شائع في MASLD، فافحص التشبّع قبل التفكير في داء ترسّب الأصبغة الدموية."),
    ("If ALT is high or the picture is unusual: autoimmune markers and IgG, ceruloplasmin (under 40 years), alpha-1 antitrypsin, coeliac serology, TSH.", "إذا كان ALT مرتفعًا أو الصورة غير معتادة: مؤشرات المناعة الذاتية وIgG، والسيرولوبلازمين (تحت 40 سنة)، وألفا-1 أنتيتربسين، وأمصال الداء البطني، وTSH."),
   ]},
  {"h": ("When is a biopsy needed?", "متى نحتاج إلى خزعة؟"),
   "p": [("Rarely, now. Consider it when non-invasive tests disagree, when another liver disease is suspected, or for a trial. Biopsy is the only way to confirm MASH and grade activity.",
          "نادرًا في الوقت الحالي. فكّر فيها عند تعارض الفحوص غير الجراحية، أو الاشتباه في مرض كبدي آخر، أو للمشاركة في تجربة سريرية. والخزعة هي الطريقة الوحيدة لتأكيد MASH وتقدير نشاطه.")]},
 ],
 "see": ["case-finding", "fibrosis-pathway", "special-groups"],
 "src": ["delphi2023", "easl2024", "aasld2023", "saudi2026"],
},
{
 "slug": "case-finding", "group": "diagnose",
 "title": {"en": "Who to test for liver fibrosis", "ar": "مَن نفحص للكشف عن تليّف الكبد"},
 "lead": {"en": "Test the people most likely to have advanced fibrosis, not everyone.",
          "ar": "افحص الأكثر عرضة للتليّف المتقدّم، لا الجميع."},
 "key": [
  ("Population screening is not recommended. Case-finding in high-risk groups is.",
   "لا يُوصى بالمسح السكاني الشامل، بل بالبحث عن الحالات في الفئات عالية الخطورة."),
  ("Top groups: type 2 diabetes, obesity with metabolic risk factors, and raised liver enzymes or steatosis on imaging.",
   "أهم الفئات: السكري من النوع الثاني، والسمنة مع عوامل خطر أيضية، وارتفاع إنزيمات الكبد أو ظهور تشحّم في التصوير."),
  ("The aim is to find fibrosis, not just fat. Start with FIB-4.",
   "الهدف هو كشف التليّف وليس الدهون فقط. ابدأ بـ FIB-4."),
  ("Normal ALT does not exclude advanced fibrosis.",
   "ALT الطبيعي لا ينفي التليّف المتقدّم."),
 ],
 "sections": [
  {"h": ("High-risk groups to check", "الفئات عالية الخطورة التي تستحق الفحص"),
   "ul": [
    ("Type 2 diabetes or prediabetes.", "السكري من النوع الثاني أو مقدمات السكري."),
    ("Abdominal obesity with at least one other metabolic risk factor.", "السمنة البطنية مع عامل خطر أيضي آخر على الأقل."),
    ("Persistently raised ALT or AST.", "ارتفاع مستمر في ALT أو AST."),
    ("Steatosis found by chance on ultrasound or CT.", "تشحّم يُكتشف صدفة في الأشعة الصوتية أو المقطعية."),
    ("First-degree relative with cirrhosis from MASLD.", "قريب من الدرجة الأولى مصاب بتشمّع ناتج عن MASLD."),
    ("Moderate alcohol intake on top of metabolic risk (MetALD).", "تناول كحول بكمية متوسطة مع وجود خطر أيضي (MetALD)."),
   ]},
  {"h": ("Where to do it", "أين يتم الفحص"),
   "p": [("FIB-4 needs only age, AST, ALT and platelets, so it fits primary care, diabetes clinics and obesity services. Building it into lab reports or the electronic record raises testing rates.",
          "يحتاج FIB-4 إلى العمر وAST وALT والصفائح فقط، لذا يناسب الرعاية الأولية وعيادات السكري والسمنة. وإدراجه آليًا في تقارير المختبر أو الملف الإلكتروني يزيد معدلات الفحص.")]},
  {"h": ("Steatosis alone is not the target", "التشحّم وحده ليس الهدف"),
   "p": [("Fibrosis stage, not the amount of fat, predicts liver events and death. Ultrasound shows fat but cannot stage fibrosis.",
          "مرحلة التليّف، لا كمية الدهون، هي ما يتنبأ بمضاعفات الكبد والوفاة. والأشعة الصوتية تُظهر الدهون لكنها لا تحدد مرحلة التليّف.")]},
 ],
 "see": ["fibrosis-pathway", "nit-reference", "definitions"],
 "src": ["easl2024", "aasld2023", "aga2021", "aace2022", "saudi2026"],
},
{
 "slug": "fibrosis-pathway", "group": "diagnose",
 "title": {"en": "The two-step fibrosis pathway", "ar": "مسار تقييم التليّف على خطوتين"},
 "lead": {"en": "FIB-4 first, then elastography or ELF if FIB-4 is not low.",
          "ar": "FIB-4 أولًا، ثم قياس مرونة الكبد أو ELF إذا لم يكن FIB-4 منخفضًا."},
 "key": [
  ("Step 1: FIB-4. Below 1.3 (below 2.0 if aged 65+) = low risk.", "الخطوة 1: FIB-4. أقل من 1.3 (أقل من 2.0 لمن هم 65 سنة فأكثر) = خطر منخفض."),
  ("Step 2: liver stiffness (VCTE) or ELF if FIB-4 is 1.3 or more.", "الخطوة 2: قياس صلابة الكبد (VCTE) أو ELF إذا كان FIB-4 ‏1.3 فأكثر."),
  ("LSM below 8 kPa = low risk. 8–12 = indeterminate. 12 or more = high risk: refer to hepatology.", "صلابة أقل من 8 كيلوباسكال = خطر منخفض، و8–12 = غير حاسم، و12 فأكثر = خطر مرتفع: أحِل إلى طبيب الكبد."),
  ("FIB-4 is not reliable under age 35.", "FIB-4 غير موثوق تحت سن 35."),
 ],
 "sections": [
  {"h": ("Step 1: FIB-4", "الخطوة 1: FIB-4"),
   "p": [("FIB-4 = (age × AST) ÷ (platelets [10⁹/L] × √ALT).", "FIB-4 = (العمر × AST) ÷ (الصفائح [10⁹/ل] × الجذر التربيعي لـ ALT).")],
   "table": {"head": [("FIB-4", "FIB-4"), ("Meaning", "المعنى"), ("Action", "الإجراء")],
             "rows": [
              [("<1.3 (<2.0 if ≥65 y)", "<1.3 (<2.0 لمن ≥65 سنة)"), ("Low risk of advanced fibrosis", "خطر منخفض للتليّف المتقدّم"), ("Manage risk factors in primary care. Repeat in 1–3 years.", "عالج عوامل الخطر في الرعاية الأولية، وأعد الفحص بعد 1–3 سنوات.")],
              [("1.3–2.67", "1.3–2.67"), ("Indeterminate", "غير حاسم"), ("Second test: VCTE or ELF.", "فحص ثانٍ: VCTE أو ELF.")],
              [("≥2.67", "≥2.67"), ("High risk", "خطر مرتفع"), ("Second test, and usually refer.", "فحص ثانٍ، وغالبًا الإحالة.")],
             ]}},
  {"h": ("Step 2: liver stiffness or ELF", "الخطوة 2: صلابة الكبد أو ELF"),
   "table": {"head": [("Result", "النتيجة"), ("Meaning", "المعنى"), ("Action", "الإجراء")],
             "rows": [
              [("LSM <8 kPa", "صلابة <8 كيلوباسكال"), ("Low risk", "خطر منخفض"), ("Primary care follow-up", "متابعة في الرعاية الأولية")],
              [("LSM 8–12 kPa", "صلابة 8–12 كيلوباسكال"), ("Indeterminate", "غير حاسم"), ("Specialist review, or add ELF / MRE", "مراجعة لدى المختص، أو إضافة ELF أو MRE")],
              [("LSM ≥12 kPa", "صلابة ≥12 كيلوباسكال"), ("Advanced fibrosis likely", "التليّف المتقدّم مرجّح"), ("Refer to hepatology", "الإحالة إلى طبيب الكبد")],
              [("LSM ≥15 kPa", "صلابة ≥15 كيلوباسكال"), ("Compensated advanced chronic liver disease likely", "مرض كبدي مزمن متقدّم معاوَض مرجّح"), ("Hepatology; assess portal hypertension", "طبيب الكبد، وتقييم ارتفاع ضغط الوريد البابي")],
              [("ELF <7.7", "ELF <7.7"), ("Low risk", "خطر منخفض"), ("Primary care follow-up", "متابعة في الرعاية الأولية")],
              [("ELF ≥9.8", "ELF ≥9.8"), ("High risk", "خطر مرتفع"), ("Refer to hepatology", "الإحالة إلى طبيب الكبد")],
             ]},
   "note": ("Cut-offs follow the EASL–EASD–EASO 2024 and AASLD 2023 guidance. Some services use other ELF cut-offs, so check your lab.",
            "الحدود وفق إرشادات EASL–EASD–EASO لعام 2024 وAASLD لعام 2023. وبعض الجهات تستخدم حدودًا أخرى لـ ELF، فراجع مختبرك.")},
  {"h": ("Pitfalls", "مواطن الخطأ"),
   "ul": [
    ("Age under 35: FIB-4 and NFS perform poorly. Go straight to VCTE if you are worried.", "تحت سن 35: أداء FIB-4 وNFS ضعيف. انتقل مباشرة إلى VCTE إذا كنت قلقًا."),
    ("Age 65+: use the 2.0 lower cut-off to cut false positives.", "65 سنة فأكثر: استخدم الحد الأدنى 2.0 لتقليل النتائج الإيجابية الكاذبة."),
    ("Acute hepatitis, very high ALT, or low platelets from another cause can mislead FIB-4.", "التهاب الكبد الحاد، أو ارتفاع ALT الشديد، أو نقص الصفائح لسبب آخر قد يضلّل FIB-4."),
    ("A low score in a patient with clinical signs of cirrhosis does not exclude it.", "النتيجة المنخفضة لدى مريض لديه علامات سريرية للتشمّع لا تنفيه."),
   ]},
 ],
 "see": ["nit-reference", "follow-up", "cirrhosis"],
 "src": ["easl2024", "aasld2023", "fib4", "shah", "mcpherson", "global2026"],
},
{
 "slug": "nit-reference", "group": "diagnose",
 "title": {"en": "Non-invasive tests at a glance", "ar": "الفحوص غير الجراحية في لمحة"},
 "lead": {"en": "Formulas, cut-offs and pitfalls for the tests used in MASLD.",
          "ar": "المعادلات والحدود ومواطن الخطأ للفحوص المستخدمة في MASLD."},
 "key": [
  ("Blood scores (FIB-4, NFS) are best at ruling out advanced fibrosis.", "مؤشرات الدم (FIB-4 وNFS) أفضل في نفي التليّف المتقدّم."),
  ("VCTE (FibroScan) and ELF are the usual second-line tests.", "VCTE (فيبروسكان) وELF هما فحصا الخط الثاني المعتادان."),
  ("MRE is the most accurate imaging test for fibrosis but costly and less available.", "MRE هو أدق فحص تصويري للتليّف لكنه مكلف وأقل توافرًا."),
  ("APRI was built for hepatitis C. It is not advised for MASLD.", "صُمّم APRI لالتهاب الكبد C، ولا يُنصح به في MASLD."),
 ],
 "sections": [
  {"h": ("Blood-based scores", "مؤشرات الدم"),
   "table": {"head": [("Test", "الفحص"), ("Inputs", "المدخلات"), ("Rule out", "النفي"), ("Rule in", "الإثبات"), ("Notes", "ملاحظات")],
             "rows": [
              ["FIB-4", ("Age, AST, ALT, platelets", "العمر، AST، ALT، الصفائح"), ("<1.3 (<2.0 if ≥65)", "<1.3 (<2.0 لمن ≥65)"), "≥2.67", ("Free, first-line. Not for under 35.", "مجاني وخط أول. لا يصلح تحت 35 سنة.")],
              ["NFS", ("Age, BMI, diabetes/IFG, AST/ALT, platelets, albumin", "العمر، مؤشر الكتلة، السكري، AST/ALT، الصفائح، الألبومين"), ("<−1.455 (<0.12 if ≥65)", "<−1.455 (<0.12 لمن ≥65)"), ">0.676", ("Similar accuracy to FIB-4. BMI and diabetes push it up.", "دقته مقاربة لـ FIB-4. ويرتفع مع زيادة الوزن والسكري.")],
              ["APRI", ("AST, platelets", "AST، الصفائح"), "—", "—", ("Low accuracy in MASLD. Use FIB-4 instead.", "دقته منخفضة في MASLD. استخدم FIB-4 بدلًا منه.")],
              ["ELF", ("HA, PIIINP, TIMP-1 (lab test)", "HA وPIIINP وTIMP-1 (فحص مخبري)"), "<7.7", "≥9.8", ("Second-line. Raised by other fibrotic conditions and age.", "خط ثانٍ. يرتفع مع أمراض تليّفية أخرى ومع العمر.")],
             ]}},
  {"h": ("Formulas", "المعادلات"),
   "ul": [
    ("FIB-4 = (age × AST) ÷ (platelets × √ALT)", "FIB-4 = (العمر × AST) ÷ (الصفائح × √ALT)"),
    ("NFS = −1.675 + 0.037 × age + 0.094 × BMI + 1.13 × (IFG or diabetes: 1, else 0) + 0.99 × AST/ALT − 0.013 × platelets − 0.66 × albumin (g/dL)",
     "NFS = −1.675 + 0.037 × العمر + 0.094 × مؤشر الكتلة + 1.13 × (اضطراب سكر الصيام أو السكري: 1، وإلا 0) + 0.99 × AST/ALT − 0.013 × الصفائح − 0.66 × الألبومين (غ/دل)"),
    ("APRI = (AST ÷ upper limit of normal) ÷ platelets × 100", "APRI = (AST ÷ الحد الأعلى الطبيعي) ÷ الصفائح × 100"),
   ]},
  {"h": ("Imaging", "التصوير"),
   "table": {"head": [("Test", "الفحص"), ("Measures", "ماذا يقيس"), ("Useful cut-offs", "حدود مفيدة"), ("Notes", "ملاحظات")],
             "rows": [
              [("VCTE (FibroScan) LSM", "VCTE (فيبروسكان) - الصلابة"), ("Liver stiffness, kPa", "صلابة الكبد بالكيلوباسكال"), ("<8 low · 8–12 grey · ≥12 high · ≥15 cACLD likely", "<8 منخفض · 8–12 منطقة رمادية · ≥12 مرتفع · ≥15 مرض متقدّم مرجّح"), ("Fast 3 hours. Use the XL probe in obesity. Valid if IQR/median ≤30%.", "صيام 3 ساعات. استخدم المجس XL في السمنة. صالح إذا كان IQR/الوسيط ≤30%.")],
              [("VCTE CAP", "CAP"), ("Steatosis, dB/m", "التشحّم بوحدة dB/m"), ("About ≥275 dB/m suggests steatosis", "نحو ≥275 dB/m يشير إلى التشحّم"), ("Does not stage fibrosis.", "لا يحدد مرحلة التليّف.")],
              [("MR elastography (MRE)", "مرونة الكبد بالرنين (MRE)"), ("Liver stiffness, kPa", "صلابة الكبد بالكيلوباسكال"), ("Centre-specific", "تختلف حسب المركز"), ("Most accurate, costly.", "الأدق والأعلى تكلفة.")],
              ["MRI-PDFF", ("Liver fat fraction", "نسبة دهون الكبد"), ("≥5% = steatosis", "≥5% = تشحّم"), ("Good for tracking fat change in trials.", "مفيد لتتبع تغيّر الدهون في الدراسات.")],
              [("Ultrasound", "الأشعة الصوتية"), ("Steatosis (moderate or more)", "التشحّم (المتوسط فأكثر)"), "—", ("Misses mild fat. Cannot stage fibrosis.", "يفوّت الدهون الخفيفة ولا يحدد التليّف.")],
             ]}},
  {"h": ("Things that falsely raise liver stiffness", "عوامل ترفع صلابة الكبد كذبًا"),
   "ul": [
    ("Recent meal (fast 3 hours).", "وجبة حديثة (الصيام 3 ساعات)."),
    ("High ALT or acute hepatitis.", "ارتفاع ALT أو التهاب كبد حاد."),
    ("Heart failure or liver congestion.", "قصور القلب أو احتقان الكبد."),
    ("Biliary obstruction.", "انسداد القنوات المرارية."),
    ("Heavy recent alcohol intake.", "تناول كحول كثير مؤخرًا."),
   ]},
 ],
 "see": ["fibrosis-pathway", "cirrhosis"],
 "src": ["easl2024", "aasld2023", "nit2021", "fib4", "nfs", "apri", "mcpherson"],
},
{
 "slug": "fib4-method", "group": "diagnose",
 "title": {"en": "FIB-4 calculator: method, users and limits", "ar": "حاسبة FIB-4: الطريقة والفئة المستهدفة والحدود"},
 "lead": {"en": "How our FIB-4 calculator works, who it is for, and when not to rely on it.",
          "ar": "كيف تعمل حاسبة FIB-4 لدينا، ولمن صُممت، ومتى لا يُعتمد عليها."},
 "key": [
  ("For healthcare professionals assessing adults with known or suspected MASLD.", "للعاملين في المجال الصحي عند تقييم البالغين المصابين بـ MASLD أو المشتبه بإصابتهم."),
  ("It estimates the chance of advanced fibrosis (F3–F4). It does not diagnose MASLD or MASH.", "تقدّر احتمال التليّف المتقدّم (F3–F4)، ولا تشخّص MASLD أو MASH."),
  ("It is a first step. Results of 1.3 or more need a second test.", "هي خطوة أولى، والنتيجة 1.3 فأكثر تحتاج إلى فحص ثانٍ."),
  ("Runs only in the browser. Nothing typed is stored or sent.", "تعمل داخل المتصفح فقط، ولا يُحفظ أو يُرسل أي شيء يُكتب."),
 ],
 "sections": [
  {"h": ("Formula and units", "المعادلة والوحدات"),
   "p": [("FIB-4 = (age in years × AST in U/L) ÷ (platelets in 10⁹/L × √ALT in U/L).", "FIB-4 = (العمر بالسنوات × AST بوحدة/ل) ÷ (الصفائح بـ 10⁹/ل × الجذر التربيعي لـ ALT بوحدة/ل)."),
         ("Platelets in 10⁹/L are the same number as in 10³/µL. Use AST and ALT taken on the same day.", "الصفائح بوحدة 10⁹/ل هي الرقم نفسه بوحدة 10³/ميكرولتر. استخدم AST وALT من العينة نفسها.")],
   "table": {"head": [("Input", "المُدخل"), ("Accepted range", "النطاق المقبول")],
             "rows": [
              [("Age", "العمر"), ("18–100 years", "18–100 سنة")],
              ["AST", ("Above 0 and below 5000 U/L", "أكبر من 0 وأقل من 5000 وحدة/ل")],
              ["ALT", ("Above 0 and below 5000 U/L", "أكبر من 0 وأقل من 5000 وحدة/ل")],
              [("Platelets", "الصفائح"), ("Above 0 and below 2000 ×10⁹/L", "أكبر من 0 وأقل من 2000 ×10⁹/ل")],
             ]},
   "note": ("Worked example: age 55, AST 40, ALT 35, platelets 200 → (55 × 40) ÷ (200 × 5.92) = 1.86 → indeterminate.",
            "مثال: العمر 55، وAST ‏40، وALT ‏35، والصفائح 200 ← (55 × 40) ÷ (200 × 5.92) = 1.86 ← غير حاسم.")},
  {"h": ("How results are labelled", "كيف تُصنّف النتائج"),
   "table": {"head": [("Score", "النتيجة"), ("Label", "التصنيف")],
             "rows": [
              [("Below 1.3 (below 2.0 if aged 65+)", "أقل من 1.3 (أقل من 2.0 لمن 65 سنة فأكثر)"), ("Low risk", "خطر منخفض")],
              [("From the low cut-off up to below 2.67", "من الحد الأدنى إلى أقل من 2.67"), ("Indeterminate", "غير حاسم")],
              [("2.67 or above", "2.67 فأكثر"), ("High risk", "خطر مرتفع")],
             ]},
   "note": ("Cut-offs from the EASL–EASD–EASO 2024 and AASLD 2023 guidance; the age-65 cut-off from McPherson 2017.",
            "الحدود من إرشادات EASL–EASD–EASO لعام 2024 وAASLD لعام 2023، وحد عمر 65 من دراسة McPherson لعام 2017.")},
  {"h": ("Do not rely on FIB-4 alone when", "لا تعتمد على FIB-4 وحده في الحالات التالية"),
   "ul": [
    ("The patient is under 35 (accuracy is poor). The calculator shows a warning.", "عمر المريض أقل من 35 سنة (الدقة ضعيفة)، وتُظهر الحاسبة تنبيهًا."),
    ("AST or ALT is very high, or there is acute liver injury. The calculator warns above 200 U/L.", "ارتفاع شديد في AST أو ALT، أو إصابة كبدية حادة. تنبّه الحاسبة عند تجاوز 200 وحدة/ل."),
    ("Platelets are low for another reason (e.g. blood disease, hypersplenism from another cause, recent chemotherapy).", "نقص الصفائح لسبب آخر (مثل أمراض الدم، أو تضخّم الطحال لسبب آخر، أو علاج كيميائي حديث)."),
    ("There are clinical or imaging signs of cirrhosis. A low score does not exclude it.", "وجود علامات سريرية أو تصويرية للتشمّع، فالنتيجة المنخفضة لا تنفيه."),
    ("Another liver disease is present. FIB-4 cut-offs here are for MASLD.", "وجود مرض كبدي آخر، فهذه الحدود خاصة بـ MASLD."),
    ("Children and pregnancy: not validated.", "الأطفال والحمل: غير مُعتمدة."),
   ]},
  {"h": ("How we check the calculator", "كيف نتحقق من الحاسبة"),
   "p": [("The code is public on GitHub. Before each change we test known values, including the worked example above and the cut-off edges (1.29, 1.30, 2.66, 2.67), and both age groups. Report a problem by email.",
          "الشيفرة منشورة علنًا على GitHub. قبل كل تعديل نختبر قيمًا معروفة، منها المثال أعلاه وحواف الحدود (1.29 و1.30 و2.66 و2.67) والفئتان العمريتان. أبلغنا عن أي مشكلة بالبريد الإلكتروني.")]},
 ],
 "see": ["fibrosis-pathway", "nit-reference"],
 "src": ["fib4", "shah", "mcpherson", "easl2024", "aasld2023"],
},
{
 "slug": "nfs-method", "group": "diagnose",
 "title": {"en": "NFS calculator: method, users and limits", "ar": "حاسبة NFS: الطريقة والفئة المستهدفة والحدود"},
 "lead": {"en": "How our NAFLD fibrosis score calculator works, and when not to rely on it.",
          "ar": "كيف تعمل حاسبة مؤشر التليّف NFS لدينا، ومتى لا يُعتمد عليها."},
 "key": [
  ("For healthcare professionals assessing adults with known or suspected MASLD.", "للعاملين في المجال الصحي عند تقييم البالغين المصابين بـ MASLD أو المشتبه بإصابتهم."),
  ("Estimates the chance of advanced fibrosis (F3–F4). Accuracy is similar to FIB-4 in people over 35.", "يقدّر احتمال التليّف المتقدّم (F3–F4)، ودقته مقاربة لـ FIB-4 لمن تجاوزوا 35 سنة."),
  ("Obesity and diabetes raise the score, so false positives are more common in these groups.", "ترفع السمنة والسكري قيمة المؤشر، لذا تكثر النتائج الإيجابية الكاذبة لديهم."),
  ("Runs only in the browser. Nothing typed is stored or sent.", "يعمل داخل المتصفح فقط، ولا يُحفظ أو يُرسل أي شيء يُكتب."),
 ],
 "sections": [
  {"h": ("Formula and units", "المعادلة والوحدات"),
   "p": [("NFS = −1.675 + 0.037 × age + 0.094 × BMI + 1.13 × (impaired fasting glucose or diabetes: 1, else 0) + 0.99 × AST/ALT − 0.013 × platelets (10⁹/L) − 0.66 × albumin (g/dL).",
          "NFS = −1.675 + 0.037 × العمر + 0.094 × مؤشر كتلة الجسم + 1.13 × (اضطراب سكر الصيام أو السكري: 1، وإلا 0) + 0.99 × AST/ALT − 0.013 × الصفائح (10⁹/ل) − 0.66 × الألبومين (غ/دل)."),
         ("The calculator works out BMI from weight and height, and converts albumin from g/L to g/dL (divide by 10) if you choose g/L.", "تحسب الأداة مؤشر كتلة الجسم من الوزن والطول، وتحوّل الألبومين من غ/ل إلى غ/دل (بالقسمة على 10) إذا اخترت غ/ل.")],
   "note": ("Worked example: age 55, weight 90 kg, height 170 cm (BMI 31.1), diabetes yes, AST 40, ALT 35, platelets 200, albumin 4.2 g/dL → 0.18 → indeterminate.",
            "مثال: العمر 55، الوزن 90 كغ، الطول 170 سم (مؤشر الكتلة 31.1)، سكري نعم، AST ‏40، ALT ‏35، الصفائح 200، الألبومين 4.2 غ/دل ← 0.18 ← غير حاسم.")},
  {"h": ("How results are labelled", "كيف تُصنّف النتائج"),
   "table": {"head": [("Score", "النتيجة"), ("Label", "التصنيف")],
             "rows": [
              [("Below −1.455 (below 0.12 if aged 65+)", "أقل من −1.455 (أقل من 0.12 لمن 65 سنة فأكثر)"), ("Low risk", "خطر منخفض")],
              [("From the low cut-off up to 0.676", "من الحد الأدنى حتى 0.676"), ("Indeterminate", "غير حاسم")],
              [("Above 0.676", "أعلى من 0.676"), ("High risk", "خطر مرتفع")],
             ]},
   "note": ("Cut-offs from Angulo 2007; the age-65 cut-off from McPherson 2017.", "الحدود من دراسة Angulo لعام 2007، وحد عمر 65 من دراسة McPherson لعام 2017.")},
  {"h": ("Do not rely on NFS alone when", "لا تعتمد على NFS وحده في الحالات التالية"),
   "ul": [
    ("The patient is under 35 (accuracy is poor).", "عمر المريض أقل من 35 سنة (الدقة ضعيفة)."),
    ("BMI is 35 or more, or the patient has diabetes: the score runs high. Confirm with a second-line test.", "مؤشر الكتلة 35 فأكثر أو وجود السكري: ترتفع النتيجة، فأكّدها بفحص من الخط الثاني."),
    ("Albumin is low for another reason (e.g. kidney or bowel protein loss, malnutrition, acute illness).", "انخفاض الألبومين لسبب آخر (مثل فقد البروتين عبر الكلى أو الأمعاء، أو سوء التغذية، أو مرض حاد)."),
    ("Platelets are low for another reason, or there is acute liver injury.", "نقص الصفائح لسبب آخر، أو وجود إصابة كبدية حادة."),
    ("Children and pregnancy: not validated.", "الأطفال والحمل: غير مُعتمد."),
   ]},
  {"h": ("Why there is no APRI calculator", "لماذا لا توجد حاسبة APRI"),
   "p": [("APRI was built for hepatitis C. In MASLD it is less accurate than FIB-4 and NFS, and the EASL and AASLD guidance prefer FIB-4 as the first step.", "صُمّم APRI لالتهاب الكبد C، ودقته في MASLD أقل من FIB-4 وNFS، وتفضّل إرشادات EASL وAASLD البدء بـ FIB-4.")]},
  {"h": ("How we check the calculator", "كيف نتحقق من الحاسبة"),
   "p": [("The code is public on GitHub. Before each change we test known values, including the worked example, both age groups and both albumin units.", "الشيفرة منشورة علنًا على GitHub. قبل كل تعديل نختبر قيمًا معروفة، منها المثال أعلاه والفئتان العمريتان ووحدتا الألبومين.")]},
 ],
 "see": ["fib4-method", "nit-reference", "fibrosis-pathway"],
 "src": ["nfs", "mcpherson", "shah", "easl2024", "aasld2023"],
},
# =================================================================== TREAT
{
 "slug": "lifestyle", "group": "treat",
 "title": {"en": "Lifestyle treatment: the targets", "ar": "العلاج بتعديل نمط الحياة: الأهداف"},
 "lead": {"en": "Weight loss is the base of treatment for every patient, at every stage.",
          "ar": "خسارة الوزن هي أساس العلاج لكل مريض وفي كل مرحلة."},
 "key": [
  ("≥5% weight loss cuts liver fat. 7–10% improves MASH. ≥10% can reverse fibrosis.", "خسارة ≥5% من الوزن تقلل دهون الكبد، و7–10% تحسّن MASH، و≥10% قد تعكس التليّف."),
  ("Mediterranean-style diet. Cut sugary drinks and ultra-processed food.", "نظام غذائي على نمط البحر المتوسط، وتقليل المشروبات المحلّاة والأطعمة فائقة التصنيع."),
  ("150–300 min/week moderate activity (or 75–150 vigorous), plus resistance training.", "150–300 دقيقة أسبوعيًا من النشاط المتوسط (أو 75–150 من النشاط الشديد)، مع تمارين المقاومة."),
  ("No alcohol if there is advanced fibrosis. Stop smoking.", "لا كحول مع التليّف المتقدّم، والتوقف عن التدخين."),
 ],
 "sections": [
  {"h": ("Weight loss and histology", "خسارة الوزن والتحسّن النسيجي"),
   "p": [("In a prospective study of 293 patients with biopsy-proven NASH, those who lost ≥10% of body weight had NASH resolution in 90% and fibrosis regression in 45%. Even 5% loss led to NASH resolution in 58%.",
          "في دراسة استباقية شملت 293 مريضًا مصابًا بـ NASH مؤكدًا بالخزعة، حقق من خسروا ≥10% من وزنهم زوال NASH بنسبة 90% وتراجع التليّف بنسبة 45%. وحتى خسارة 5% أدّت إلى زوال NASH لدى 58%.")]},
  {"h": ("Diet", "الغذاء"),
   "ul": [
    ("Calorie deficit of about 500–1000 kcal/day for weight loss.", "عجز في السعرات بنحو 500–1000 سعرة يوميًا لخسارة الوزن."),
    ("Mediterranean pattern: vegetables, legumes, whole grains, olive oil, fish, nuts.", "نمط البحر المتوسط: خضروات، وبقوليات، وحبوب كاملة، وزيت زيتون، وأسماك، ومكسّرات."),
    ("Limit fructose-sweetened drinks, refined carbohydrates, red and processed meat.", "قلّل المشروبات المحلّاة بالفركتوز، والنشويات المكرّرة، واللحوم الحمراء والمصنّعة."),
    ("Coffee is linked to lower fibrosis risk in observational studies.", "ترتبط القهوة بانخفاض خطر التليّف في الدراسات الرصدية."),
   ]},
  {"h": ("Activity", "النشاط البدني"),
   "p": [("Exercise lowers liver fat even without weight loss. Pick what the patient will keep doing. Add resistance training to protect muscle, especially with GLP-1 drugs and in older adults.",
          "يقلل الرياضة دهون الكبد حتى دون خسارة الوزن. اختر ما سيستمر عليه المريض، وأضف تمارين المقاومة لحماية العضلات، خاصة مع أدوية GLP-1 ولدى كبار السن.")]},
  {"h": ("Alcohol", "الكحول"),
   "p": [("Alcohol and metabolic risk add up. Advise complete abstinence in advanced fibrosis or cirrhosis, and as little as possible otherwise.",
          "تتضاعف أضرار الكحول مع الخطر الأيضي. انصح بالامتناع التام في التليّف المتقدّم أو التشمّع، وبأقل قدر ممكن في غير ذلك.")]},
 ],
 "see": ["drugs", "cardiometabolic", "surgery"],
 "src": ["easl2024", "aasld2023", "vilar", "global2025"],
},
{
 "slug": "drugs", "group": "treat",
 "title": {"en": "Drug treatment for MASH", "ar": "العلاج الدوائي لـ MASH"},
 "lead": {"en": "Two drugs are approved for non-cirrhotic MASH with F2–F3 fibrosis: resmetirom and semaglutide.",
          "ar": "يوجد دواءان معتمدان لـ MASH دون تشمّع مع تليّف F2–F3: الريسميتيروم والسيماغلوتايد."},
 "key": [
  ("Who: adults with MASH and moderate-to-advanced fibrosis (F2–F3), no cirrhosis, alongside lifestyle change.", "لمن: البالغون المصابون بـ MASH مع تليّف متوسط إلى متقدّم (F2–F3)، دون تشمّع، مع تعديل نمط الحياة."),
  ("Biopsy is not required. Non-invasive tests can identify likely F2–F3.", "الخزعة ليست شرطًا، ويمكن للفحوص غير الجراحية تحديد F2–F3 المرجّح."),
  ("Approvals differ by country. Check local status (in Saudi Arabia, the SFDA) before prescribing.", "تختلف الموافقات من بلد لآخر. تحقق من الوضع المحلي (في السعودية: هيئة الغذاء والدواء) قبل الوصف."),
  ("Neither is approved for cirrhosis yet.", "لم يُعتمد أيٌّ منهما للتشمّع حتى الآن."),
 ],
 "sections": [
  {"h": ("The two approved drugs", "الدواءان المعتمدان"),
   "table": {"head": ["", ("Resmetirom", "الريسميتيروم"), ("Semaglutide 2.4 mg", "السيماغلوتايد 2.4 ملغ")],
             "rows": [
              [("How it works", "آلية العمل"), ("Liver-directed thyroid hormone receptor-β agonist", "منبّه لمستقبل هرمون الغدة الدرقية بيتا موجّه للكبد"), ("GLP-1 receptor agonist; weight loss and metabolic effects", "منبّه لمستقبل GLP-1؛ خسارة وزن وتأثيرات أيضية")],
              [("Dose", "الجرعة"), ("80 mg daily (<100 kg) or 100 mg daily (≥100 kg), by mouth", "80 ملغ يوميًا (<100 كغ) أو 100 ملغ يوميًا (≥100 كغ) بالفم"), ("2.4 mg weekly injection, built up over about 16 weeks", "2.4 ملغ حقنة أسبوعية، تُرفع تدريجيًا خلال نحو 16 أسبوعًا")],
              [("Trial", "التجربة"), ("MAESTRO-NASH, 52 weeks", "MAESTRO-NASH، 52 أسبوعًا"), ("ESSENCE, 72 weeks", "ESSENCE، 72 أسبوعًا")],
              [("MASH resolution", "زوال MASH"), ("25.9% (80 mg) and 29.9% (100 mg) vs 9.7% placebo", "25.9% (80 ملغ) و29.9% (100 ملغ) مقابل 9.7% للدواء الوهمي"), ("62.9% vs 34.3% placebo", "62.9% مقابل 34.3% للدواء الوهمي")],
              [("Fibrosis improved ≥1 stage", "تحسّن التليّف مرحلة أو أكثر"), ("24.2% and 25.9% vs 14.2%", "24.2% و25.9% مقابل 14.2%"), ("36.8% vs 22.4%", "36.8% مقابل 22.4%")],
              [("Weight", "الوزن"), ("Neutral", "لا تأثير يُذكر"), ("−10.5% vs −2.0%", "−10.5% مقابل −2.0%")],
              [("Main side effects", "أهم الآثار الجانبية"), ("Diarrhoea, nausea", "إسهال، غثيان"), ("Nausea, vomiting, diarrhoea, constipation", "غثيان، قيء، إسهال، إمساك")],
              [("Watch for", "انتبه إلى"), ("Interactions: avoid strong CYP2C8 inhibitors (e.g. gemfibrozil). With a CYP2C8 inhibitor such as clopidogrel, lower the dose (80 mg if ≥100 kg, 60 mg if <100 kg). Statin caps: rosuvastatin and simvastatin 20 mg, atorvastatin and pravastatin 40 mg. Check TSH and free T4 if on levothyroxine.", "التداخلات: تجنّب مثبطات CYP2C8 القوية (مثل الجمفيبروزيل). ومع مثبط لـ CYP2C8 مثل الكلوبيدوغريل تُخفّض الجرعة (80 ملغ لمن وزنه ≥100 كغ، و60 ملغ لمن وزنه <100 كغ). الحد الأعلى للستاتين: روزوفاستاتين وسيمفاستاتين 20 ملغ، وأتورفاستاتين وبرافاستاتين 40 ملغ. افحص TSH وfree T4 لمن يتناول الليفوثيروكسين."), ("Gallstones, pancreatitis history, muscle loss; not in pregnancy", "حصى المرارة، تاريخ التهاب البنكرياس، فقدان العضلات؛ لا يُستخدم في الحمل")],
             ]},
   "note": ("Approved in the US (resmetirom 2024, semaglutide 2025), the EU (resmetirom, conditional, 2025) and the UK (both, 2026). Long-term outcome trials are ongoing.",
            "معتمدان في الولايات المتحدة (الريسميتيروم 2024، والسيماغلوتايد 2025)، والاتحاد الأوروبي (الريسميتيروم، اعتماد مشروط، 2025)، والمملكة المتحدة (كلاهما، 2026). وما زالت تجارب المآلات طويلة المدى جارية.")},
  {"h": ("Who qualifies for resmetirom (AASLD 2024)", "مَن يناسبه الريسميتيروم (AASLD 2024)"),
   "table": {"head": [("Recommended", "يوصى به"), ("Not recommended", "لا يوصى به")],
             "rows": [
              [("MASLD with VCTE 8–15 kPa, or MRE 3.1–4.4 kPa, or biopsy-proven MASH F2–F3", "MASLD مع صلابة VCTE ‏8–15 كيلوباسكال، أو MRE ‏3.1–4.4 كيلوباسكال، أو MASH مؤكد بالخزعة F2–F3"),
               ("Cirrhosis, including VCTE >20 kPa or MRE >5 kPa", "التشمّع، ومنه صلابة VCTE >20 كيلوباسكال أو MRE >5 كيلوباسكال")],
              [("Values outside these ranges: individual decision by a liver specialist", "القيم خارج هذه النطاقات: قرار فردي من طبيب كبد متمرّس"),
               ("Other active liver disease; alcohol >20 g/day (women) or >30 g/day (men); active thyroid disease", "مرض كبدي نشط آخر؛ كحول >20 غ/يوم (نساء) أو >30 غ/يوم (رجال)؛ مرض درقي نشط")],
             ]},
   "note": ("The 2025 global consensus also allows treatment at 16–20 kPa if a second test excludes cirrhosis and there are no signs of portal hypertension.",
            "ويسمح الإجماع العالمي لعام 2025 أيضًا بالعلاج عند 16–20 كيلوباسكال إذا نفى فحص ثانٍ التشمّع ولم توجد علامات لارتفاع ضغط الوريد البابي.")},
  {"h": ("Choosing between them", "الاختيار بينهما"),
   "ul": [
    ("Obesity or type 2 diabetes needing treatment anyway: semaglutide treats both.", "سمنة أو سكري يحتاج علاجًا في كل الأحوال: السيماغلوتايد يعالج الاثنين."),
    ("Normal weight, GLP-1 not tolerated, or already on a GLP-1 drug: resmetirom is an option.", "وزن طبيعي، أو عدم تحمّل GLP-1، أو يتناول دواء GLP-1 أصلًا: الريسميتيروم خيار."),
    ("Data on using both together are still limited.", "البيانات عن الجمع بينهما ما زالت محدودة."),
   ]},
  {"h": ("Monitoring resmetirom", "متابعة العلاج بالريسميتيروم"),
   "ul": [
    ("Safety: liver panel at 3, 6 and 12 months.", "السلامة: تحاليل الكبد بعد 3 و6 و12 شهرًا."),
    ("Stop for liver injury: AST or ALT >5× the upper limit, or bilirubin >2.5 mg/dL with raised enzymes, among other label criteria.", "أوقف الدواء عند إصابة الكبد: AST أو ALT أكثر من 5 أضعاف الحد الأعلى، أو البيليروبين >2.5 ملغ/دل مع ارتفاع الإنزيمات، إضافة إلى معايير أخرى في النشرة."),
    ("Response at 12 months, using the same test as at baseline (image-based stiffness preferred).", "تقييم الاستجابة بعد 12 شهرًا بالفحص نفسه المستخدم في البداية (ويفضَّل قياس الصلابة بالتصوير)."),
   ]},
  {"h": ("Response at 12 months", "الاستجابة بعد 12 شهرًا"),
   "table": {"head": [("Finding", "النتيجة"), ("Action", "الإجراء")],
             "rows": [
              [("LSM falls ≥25% on VCTE (≥20% on MRE), or ALT normalises or clearly improves", "انخفاض الصلابة ≥25% بـ VCTE (≥20% بـ MRE)، أو تطبّع ALT أو تحسّنه بوضوح"), ("Benefit: continue", "فائدة: استمر")],
              [("Small fall in LSM, no clear ALT change", "انخفاض بسيط في الصلابة دون تغيّر واضح في ALT"), ("Uncertain: re-optimise lifestyle, consider other options", "غير مؤكد: حسّن نمط الحياة، وفكّر في خيارات أخرى")],
              [("Non-invasive tests worsen, or ALT keeps rising", "تدهور الفحوص غير الجراحية أو استمرار ارتفاع ALT"), ("No response: stop", "لا استجابة: أوقف الدواء")],
             ]},
   "note": ("Based on the AASLD October 2024 update. The 2025 global consensus uses a ≥30% change in VCTE stiffness, and says ALT alone should not decide response.",
            "وفق تحديث AASLD في أكتوبر 2024. ويستخدم الإجماع العالمي لعام 2025 تغيّرًا ≥30% في صلابة VCTE، ويرى ألا يُعتمد على ALT وحده لتقييم الاستجابة.")},
  {"h": ("Other medicines", "أدوية أخرى"),
   "table": {"head": [("Drug", "الدواء"), ("Place in MASLD", "مكانه في MASLD")],
             "rows": [
              [("Pioglitazone", "البيوغليتازون"), ("Improved histology in trials. AASLD: can be considered with type 2 diabetes. EASL and the global consensus: safe, but use it for diabetes, not as a MASH treatment. Weight gain and fluid retention.", "حسّن النسيج في التجارب. AASLD: يمكن النظر فيه مع السكري من النوع الثاني. وEASL والإجماع العالمي: آمن، لكن يُستخدم للسكري لا علاجًا لـ MASH. يسبب زيادة الوزن واحتباس السوائل.")],
              [("Vitamin E", "فيتامين E"), ("AASLD: can be considered in selected people. Global consensus: only in selected people without diabetes or cirrhosis. EASL 2024: not recommended as MASH treatment.", "AASLD: يمكن النظر فيه لدى أشخاص مختارين. والإجماع العالمي: فقط لدى أشخاص مختارين دون سكري أو تشمّع. وEASL 2024: لا يوصى به علاجًا لـ MASH.")],
              [("Tirzepatide, other GLP-1 drugs", "التيرزيباتايد وأدوية GLP-1 الأخرى"), ("Use for diabetes or obesity. Liver data promising, not yet approved for MASH.", "تُستخدم للسكري أو السمنة. بيانات الكبد واعدة لكنها غير معتمدة لـ MASH بعد.")],
              [("SGLT2 inhibitors", "مثبطات SGLT2"), ("Use for diabetes, heart and kidney benefit. Not a liver treatment.", "تُستخدم للسكري ولفائدتها القلبية والكلوية، وليست علاجًا للكبد.")],
              [("Metformin", "الميتفورمين"), ("Safe; no effect on histology.", "آمن، ولا تأثير له على النسيج.")],
              [("Statins", "الستاتينات"), ("Safe and recommended for heart risk, including compensated cirrhosis.", "آمنة ويوصى بها للخطر القلبي، بما في ذلك التشمّع المعاوَض.")],
              [("Ursodeoxycholic acid, silymarin, other supplements", "حمض أورسوديوكسيكوليك، والسيليمارين، والمكمّلات الأخرى"), ("Not recommended.", "لا يوصى بها.")],
             ]}},
 ],
 "see": ["lifestyle", "cardiometabolic", "fibrosis-pathway"],
 "src": ["resm2024", "global2025", "maestro", "essence", "easl2024", "aasld2023", "noureddin2024", "global2026", "blt2026", "ec2025"],
},
{
 "slug": "cardiometabolic", "group": "treat",
 "title": {"en": "Heart and metabolic care in MASLD", "ar": "رعاية القلب والأيض في MASLD"},
 "lead": {"en": "Heart disease, not liver disease, is the top cause of death in most MASLD patients.",
          "ar": "أمراض القلب، لا الكبد، هي السبب الأول للوفاة لدى معظم مرضى MASLD."},
 "key": [
  ("Assess and treat cardiovascular risk in every patient.", "قيّم الخطر القلبي الوعائي وعالجه لدى كل مريض."),
  ("Statins are safe in MASLD and should not be withheld.", "الستاتينات آمنة في MASLD ولا ينبغي حجبها."),
  ("In type 2 diabetes, favour drugs with liver and heart benefit (GLP-1 RA, SGLT2i, pioglitazone).", "في السكري من النوع الثاني، فضّل الأدوية ذات الفائدة الكبدية والقلبية (منبّهات GLP-1، ومثبطات SGLT2، والبيوغليتازون)."),
  ("MASLD raises the risk of type 2 diabetes and chronic kidney disease.", "يزيد MASLD خطر الإصابة بالسكري من النوع الثاني ومرض الكلى المزمن."),
 ],
 "sections": [
  {"h": ("What to check", "ما الذي يجب فحصه"),
   "ul": [
    ("Blood pressure, lipid profile, HbA1c or fasting glucose.", "ضغط الدم، ودهون الدم، وHbA1c أو سكر الصيام."),
    ("Kidney function and urine albumin in diabetes.", "وظائف الكلى وألبومين البول لدى مرضى السكري."),
    ("Smoking, sleep apnoea symptoms.", "التدخين وأعراض انقطاع النفس أثناء النوم."),
    ("A 10-year cardiovascular risk score.", "مؤشر الخطر القلبي الوعائي لعشر سنوات."),
   ]},
  {"h": ("Statins", "الستاتينات"),
   "p": [("Raised liver enzymes are not a reason to avoid statins. They are safe in compensated cirrhosis. Use care in decompensated cirrhosis.",
          "ارتفاع إنزيمات الكبد ليس سببًا لتجنّب الستاتينات. وهي آمنة في التشمّع المعاوَض، ويجب الحذر في التشمّع غير المعاوَض.")]},
  {"h": ("Diabetes drugs", "أدوية السكري"),
   "p": [("GLP-1 receptor agonists and pioglitazone improve liver histology. SGLT2 inhibitors protect heart and kidney. Metformin is safe but does not treat the liver. In decompensated cirrhosis, insulin is often the safest choice.",
          "تحسّن منبّهات مستقبل GLP-1 والبيوغليتازون نسيج الكبد، وتحمي مثبطات SGLT2 القلب والكلى. والميتفورمين آمن لكنه لا يعالج الكبد. وفي التشمّع غير المعاوَض يكون الإنسولين غالبًا الخيار الأكثر أمانًا.")]},
 ],
 "see": ["drugs", "lifestyle", "cirrhosis"],
 "src": ["easl2024", "aasld2023", "aace2022", "global2025"],
},
{
 "slug": "surgery", "group": "treat",
 "title": {"en": "Metabolic and bariatric surgery", "ar": "جراحات السمنة والجراحات الأيضية"},
 "lead": {"en": "Surgery gives the largest, longest-lasting improvement in MASH, in the right patient.",
          "ar": "تحقق الجراحة أكبر تحسّن وأطوله أثرًا في MASH، إذا اختير المريض المناسب."},
 "key": [
  ("Consider in MASLD with BMI ≥35, or 30–34.9 with metabolic disease (lower thresholds in Asian people).", "يُنظر فيها في MASLD مع مؤشر كتلة ≥35، أو 30–34.9 مع مرض أيضي (حدود أقل للآسيويين)."),
  ("Randomised trial (BRAVES): MASH resolved at 1 year in 56–57% after surgery vs 16% with lifestyle and medical care.", "تجربة عشوائية (BRAVES): زال MASH بعد سنة لدى 56–57% بعد الجراحة مقابل 16% مع نمط الحياة والرعاية الطبية."),
  ("Long term: at 5 years, MASH resolved in 84% and fibrosis fell in 70% of re-biopsied patients.", "على المدى الطويل: بعد 5 سنوات زال MASH لدى 84% وتراجع التليّف لدى 70% ممن أُعيدت لهم الخزعة."),
  ("Compensated cirrhosis without portal hypertension: possible in expert centres.", "التشمّع المعاوَض دون ارتفاع ضغط بابي: ممكنة في المراكز المتخصصة."),
  ("Avoid in decompensated cirrhosis.", "تُتجنّب في التشمّع غير المعاوَض."),
 ],
 "sections": [
  {"h": ("Before surgery", "قبل الجراحة"),
   "ul": [
    ("Stage fibrosis first. Unknown cirrhosis raises surgical risk.", "حدّد مرحلة التليّف أولًا، فالتشمّع غير المكتشف يرفع خطر الجراحة."),
    ("If cirrhosis is likely, assess portal hypertension (Baveno VII).", "إذا كان التشمّع مرجّحًا، قيّم ارتفاع ضغط الوريد البابي (Baveno VII)."),
    ("Sleeve gastrectomy is often preferred in compensated cirrhosis.", "يُفضَّل غالبًا تكميم المعدة في التشمّع المعاوَض."),
   ]},
  {"h": ("After surgery", "بعد الجراحة"),
   "ul": [
    ("No alcohol: absorption changes and the risk of alcohol use disorder rises.", "لا كحول: يتغيّر الامتصاص ويزداد خطر اضطراب تعاطي الكحول."),
    ("Very fast weight loss can rarely worsen liver function. Watch closely in the first months.", "قد تؤدي خسارة الوزن السريعة جدًا نادرًا إلى تدهور وظائف الكبد، فراقب المريض عن كثب في الأشهر الأولى."),
    ("Keep up fibrosis follow-up.", "استمر في متابعة التليّف."),
   ]},
 ],
 "see": ["lifestyle", "cirrhosis", "drugs"],
 "src": ["easl2024", "braves2023", "lassailly", "asmbs2022", "baveno7"],
},
# =================================================================== FOLLOW UP
{
 "slug": "follow-up", "group": "follow",
 "title": {"en": "Follow-up and referral", "ar": "المتابعة والإحالة"},
 "lead": {"en": "How often to retest, and when to send the patient to a liver specialist.",
          "ar": "متى نعيد الفحص، ومتى نحيل المريض إلى طبيب الكبد."},
 "key": [
  ("Low risk: repeat FIB-4 every 1–2 years with diabetes or several risk factors, every 2–3 years otherwise.", "خطر منخفض: أعد FIB-4 كل 1–2 سنة مع السكري أو تعدد عوامل الخطر، وكل 2–3 سنوات في غير ذلك."),
  ("Indeterminate: repeat second-line test in about a year, or refer.", "غير حاسم: أعد فحص الخط الثاني بعد نحو سنة، أو أحِل المريض."),
  ("High risk (LSM ≥12 kPa, ELF ≥9.8): hepatology.", "خطر مرتفع (صلابة ≥12 كيلوباسكال، أو ELF ≥9.8): طبيب الكبد."),
  ("Any sign of cirrhosis or decompensation: urgent referral.", "أي علامة تشمّع أو عدم معاوضة: إحالة عاجلة."),
 ],
 "sections": [
  {"h": ("Refer to hepatology if", "أحِل إلى طبيب الكبد إذا"),
   "ul": [
    ("LSM ≥12 kPa or ELF ≥9.8, or FIB-4 ≥2.67 without access to a second test.", "الصلابة ≥12 كيلوباسكال أو ELF ≥9.8، أو FIB-4 ≥2.67 مع تعذّر الفحص الثاني."),
    ("Clinical, lab or imaging signs of cirrhosis.", "علامات سريرية أو مخبرية أو تصويرية للتشمّع."),
    ("Doubt about the diagnosis or another liver disease suspected.", "الشك في التشخيص أو الاشتباه في مرض كبدي آخر."),
    ("Candidate for MASH drug treatment.", "مرشّح للعلاج الدوائي لـ MASH."),
    ("ALT persistently above 3 times normal.", "ALT أعلى من 3 أضعاف الطبيعي باستمرار."),
   ]},
  {"h": ("Red flags: same-day care", "علامات الخطر: رعاية في اليوم نفسه"),
   "ul": [
    ("Jaundice, confusion, vomiting blood or black stools, rapid abdominal swelling.", "اليرقان، أو التشوّش، أو تقيؤ الدم أو البراز الأسود، أو انتفاخ البطن السريع."),
   ]},
  {"h": ("Every visit", "في كل زيارة"),
   "ul": [
    ("Weight and waist, blood pressure.", "الوزن ومحيط الخصر، وضغط الدم."),
    ("Diabetes and lipid control.", "ضبط السكري والدهون."),
    ("Alcohol and smoking.", "الكحول والتدخين."),
    ("Review new medicines for liver effects.", "مراجعة الأدوية الجديدة وتأثيرها على الكبد."),
   ]},
 ],
 "see": ["fibrosis-pathway", "cirrhosis", "drugs"],
 "src": ["aasld2023", "easl2024", "aga2021", "saudi2026"],
},
{
 "slug": "cirrhosis", "group": "follow",
 "title": {"en": "MASLD cirrhosis: key care", "ar": "التشمّع الناتج عن MASLD: أساسيات الرعاية"},
 "lead": {"en": "Find portal hypertension, screen for liver cancer, and keep treating metabolic risk.",
          "ar": "اكشف ارتفاع ضغط الوريد البابي، وافحص لسرطان الكبد، واستمر في علاج الخطر الأيضي."},
 "key": [
  ("Baveno VII \"rule of five\" for liver stiffness: 10, 15, 20, 25 kPa.", "قاعدة الخمسات في Baveno VII لصلابة الكبد: 10 و15 و20 و25 كيلوباسكال."),
  ("Liver cancer surveillance: ultrasound (± AFP) every 6 months in cirrhosis.", "مراقبة سرطان الكبد: أشعة صوتية (± AFP) كل 6 أشهر في التشمّع."),
  ("Carry on statins, diabetes care and weight management in compensated disease.", "استمر في الستاتينات وعلاج السكري وضبط الوزن في المرض المعاوَض."),
  ("Approved MASH drugs are not yet licensed for cirrhosis.", "أدوية MASH المعتمدة غير مرخّصة للتشمّع حتى الآن."),
 ],
 "sections": [
  {"h": ("Liver stiffness: the rule of five", "صلابة الكبد: قاعدة الخمسات"),
   "table": {"head": [("LSM (VCTE)", "الصلابة (VCTE)"), ("Meaning", "المعنى")],
             "rows": [
              ["<10 kPa", ("Compensated advanced chronic liver disease (cACLD) unlikely", "المرض الكبدي المزمن المتقدّم المعاوَض غير مرجّح")],
              ["10–15 kPa", ("Suggestive of cACLD", "يشير إلى مرض متقدّم معاوَض")],
              [">15 kPa", ("Highly suggestive of cACLD", "يشير بقوة إلى مرض متقدّم معاوَض")],
              [("≤15 kPa + platelets ≥150", "≤15 + صفائح ≥150"), ("Rules out clinically significant portal hypertension (CSPH)", "ينفي ارتفاع ضغط الوريد البابي المهم سريريًا")],
              [("<20 kPa + platelets >150", "<20 + صفائح >150"), ("Screening endoscopy for varices can be skipped", "يمكن الاستغناء عن منظار الكشف عن الدوالي")],
              ["≥25 kPa", ("Rules in CSPH (less reliable in obese MASLD)", "يُثبت ارتفاع الضغط البابي المهم (أقل موثوقية في MASLD مع السمنة)")],
             ]}},
  {"h": ("Other essentials", "أساسيات أخرى"),
   "ul": [
    ("Non-selective beta-blocker (carvedilol preferred) if CSPH, to prevent decompensation.", "حاصر بيتا غير انتقائي (يفضّل الكارفيديلول) عند وجود ارتفاع الضغط البابي المهم، للوقاية من عدم المعاوضة."),
    ("Vaccinate: hepatitis A and B, pneumococcus, influenza.", "التطعيم: التهاب الكبد A وB، والمكورات الرئوية، والإنفلونزا."),
    ("Watch for sarcopenia; avoid long fasts and give enough protein.", "انتبه لضمور العضلات، وتجنّب الصيام الطويل، وأعطِ كمية كافية من البروتين."),
    ("Refer for transplant assessment after decompensation or a MELD score of about 15 or more.", "أحِل لتقييم الزراعة بعد عدم المعاوضة أو عند بلوغ مؤشر MELD نحو 15 فأكثر."),
   ]},
  {"h": ("Advanced fibrosis without cirrhosis (F3)", "التليّف المتقدّم دون تشمّع (F3)"),
   "p": [("Liver cancer can occur in MASLD before cirrhosis, but routine surveillance in F3 is not generally advised. Decide case by case.",
          "قد يحدث سرطان الكبد في MASLD قبل التشمّع، لكن المراقبة الروتينية في F3 لا يُنصح بها عمومًا. ويُقرر ذلك لكل حالة على حدة.")]},
 ],
 "see": ["follow-up", "nit-reference", "surgery"],
 "src": ["baveno7", "easl2024", "aasld2023", "nit2021"],
},
{
 "slug": "special-groups", "group": "follow",
 "title": {"en": "Special groups", "ar": "فئات خاصة"},
 "lead": {"en": "Children, lean patients, older adults, young adults and people who drink alcohol.",
          "ar": "الأطفال، وذوو الوزن الطبيعي، وكبار السن، والشباب، ومن يتناولون الكحول."},
 "key": [
  ("Children: screen with ALT from age 10 with obesity, or overweight plus risk factors. FIB-4 is not valid.", "الأطفال: الفحص بـ ALT من عمر 10 سنوات مع السمنة، أو زيادة الوزن مع عوامل خطر. FIB-4 غير صالح."),
  ("Lean MASLD (BMI <25, <23 Asian) can still progress. Use the same pathway.", "MASLD لدى ذوي الوزن الطبيعي (مؤشر الكتلة <25، و<23 للآسيويين) قد يتطور أيضًا. استخدم المسار نفسه."),
  ("Age 65+: FIB-4 lower cut-off 2.0; NFS 0.12.", "65 سنة فأكثر: الحد الأدنى لـ FIB-4 هو 2.0، ولـ NFS هو 0.12."),
  ("MetALD: treat both the alcohol use and the metabolic risk.", "MetALD: عالج تعاطي الكحول والخطر الأيضي معًا."),
 ],
 "sections": [
  {"h": ("Children and adolescents (AASLD 2025)", "الأطفال والمراهقون (AASLD 2025)"),
   "ul": [
    ("Screen from age 10 in children with obesity, or with overweight plus cardiometabolic risk factors or a family history. Some guidelines screen younger children with risk factors.", "افحص من عمر 10 سنوات الأطفال المصابين بالسمنة، أو بزيادة الوزن مع عوامل خطر قلبية أيضية أو تاريخ عائلي. وبعض الإرشادات تفحص أطفالًا أصغر عند وجود عوامل خطر."),
    ("Use ALT, not ultrasound, to screen. Abnormal: above 22 U/L in girls and 26 U/L in boys.", "استخدم ALT لا الأشعة الصوتية للفحص. ويُعد غير طبيعي إذا تجاوز 22 وحدة/ل للبنات و26 للأولاد."),
    ("A single high ALT in a well child: repeat within 3 months. Persistently high: evaluate or refer. Do not wait for ALT to reach twice normal.", "ارتفاع ALT مرة واحدة لدى طفل سليم: أعد الفحص خلال 3 أشهر. وإذا استمر الارتفاع فقيّم أو أحِل، ولا تنتظر حتى يبلغ ضعف الطبيعي."),
    ("Diagnosis needs steatosis on imaging or biopsy plus a cardiometabolic risk factor. ALT alone is not enough.", "يحتاج التشخيص إلى إثبات التشحّم بالتصوير أو الخزعة مع عامل خطر قلبي أيضي، وALT وحده لا يكفي."),
    ("Look harder for other causes (Wilson disease, autoimmune hepatitis, genetic disorders).", "ابحث بعناية أكبر عن الأسباب الأخرى (داء ويلسون، والتهاب الكبد المناعي، والاضطرابات الوراثية)."),
    ("Family-based lifestyle change is the main treatment. No drug is approved for MASH in children.", "تعديل نمط حياة الأسرة كلها هو العلاج الأساسي، ولا يوجد دواء معتمد لـ MASH لدى الأطفال."),
   ]},
  {"h": ("Lean MASLD", "MASLD لدى ذوي الوزن الطبيعي"),
   "p": [("Check waist size, diet, activity and genetics (e.g. PNPLA3). Rule out other causes carefully. A 3–5% weight loss can help.",
          "افحص محيط الخصر والنظام الغذائي والنشاط والعوامل الوراثية (مثل PNPLA3)، واستبعد الأسباب الأخرى بعناية. وخسارة 3–5% من الوزن قد تفيد.")]},
  {"h": ("Under 35 and over 65", "تحت 35 سنة وفوق 65 سنة"),
   "p": [("Blood scores perform poorly under 35; use elastography if concerned. At 65 or over, use the age-adjusted cut-offs to avoid over-referral.",
          "أداء مؤشرات الدم ضعيف تحت 35 سنة، فاستخدم قياس المرونة عند القلق. ومن عمر 65 فأكثر استخدم الحدود المعدّلة حسب العمر لتجنّب الإحالات الزائدة.")]},
  {"h": ("MetALD", "MetALD"),
   "p": [("Ask about alcohol in grams per week. Use a validated tool (AUDIT-C) and offer support for alcohol use. Fibrosis progresses faster when both causes are present.",
          "اسأل عن الكحول بالغرامات أسبوعيًا، واستخدم أداة معتمدة (AUDIT-C)، وقدّم الدعم لتعاطي الكحول. ويتطور التليّف أسرع عند اجتماع السببين.")]},
 ],
 "see": ["definitions", "fibrosis-pathway", "lifestyle"],
 "src": ["peds2025", "naspghan", "easl2024", "aasld2023", "mcpherson", "delphi2023"],
},
# =================================================================== CONTEXT
{
 "slug": "guidelines-compared", "group": "context",
 "title": {"en": "MASLD guidelines side by side", "ar": "إرشادات MASLD جنبًا إلى جنب"},
 "lead": {"en": "Where the main international and regional guidelines agree, and where they differ.",
          "ar": "أين تتفق الإرشادات الدولية والإقليمية الرئيسية، وأين تختلف."},
 "key": [
  ("All agree: FIB-4 first (1.3 and 2.67), then elastography. A liver stiffness below 8 kPa is low risk.", "تتفق جميعها على: FIB-4 أولًا (1.3 و2.67)، ثم قياس المرونة. والصلابة الأقل من 8 كيلوباسكال خطر منخفض."),
  ("Names differ: Western and global documents use MASLD; Asian, Chinese and Egyptian guidelines use MAFLD. The patients are largely the same.", "تختلف الأسماء: تستخدم الوثائق الغربية والعالمية MASLD، وتستخدم الإرشادات الآسيوية والصينية والمصرية MAFLD، والمرضى متقاربون إلى حد كبير."),
  ("They differ most on drugs: how to select patients for resmetirom, and whether vitamin E or pioglitazone count as liver treatment.", "أكثر ما تختلف فيه الأدوية: كيفية اختيار المرضى للريسميتيروم، وهل يُعدّ فيتامين E أو البيوغليتازون علاجًا للكبد."),
  ("Always check the full guideline and your local drug approvals.", "راجع دائمًا الإرشادات كاملة وموافقات الأدوية المحلية."),
 ],
 "sections": [
  {"h": ("Diagnosis and staging", "التشخيص وتقييم المرحلة"),
   "table": {"head": [("Guideline", "الإرشادات"), ("Name", "التسمية"), ("First step", "الخطوة الأولى"), ("Second step", "الخطوة الثانية"), ("Retest if low risk", "إعادة الفحص عند الخطر المنخفض")],
             "rows": [
              ["EASL–EASD–EASO 2024", "MASLD", ("FIB-4 <1.3 / ≥1.3", "FIB-4 ‏<1.3 / ≥1.3"), ("VCTE <8 / ≥12 kPa, or ELF <7.7 / ≥9.8", "VCTE ‏<8 / ≥12 كيلوباسكال، أو ELF ‏<7.7 / ≥9.8"), ("Every 1–3 years", "كل 1–3 سنوات")],
              ["AASLD 2023", ("NAFLD, renamed MASLD in 2023", "NAFLD، وأعيدت تسميته MASLD عام 2023"), ("FIB-4 <1.3 / 1.3–2.67 / >2.67", "FIB-4 ‏<1.3 / 1.3–2.67 / >2.67"), ("VCTE <8 / 8–12 / >12 kPa, or ELF <7.7 / ≥9.8", "VCTE ‏<8 / 8–12 / >12 كيلوباسكال، أو ELF ‏<7.7 / ≥9.8"), ("2–3 years; 1–2 years with diabetes or ≥2 risk factors", "2–3 سنوات؛ و1–2 سنة مع السكري أو ≥2 عوامل خطر")],
              [("Global consensus 2025", "الإجماع العالمي 2025"), "MASLD", ("FIB-4 <1.3 (<2.0 if ≥65)", "FIB-4 ‏<1.3 (<2.0 لمن ≥65)"), ("VCTE ≥8 kPa = at risk", "VCTE ‏≥8 كيلوباسكال = معرّض للخطر"), "—"],
              ["APASL 2025", "MAFLD", ("FIB-4 <1.3 / 1.3–2.67 / >2.67", "FIB-4 ‏<1.3 / 1.3–2.67 / >2.67"), ("VCTE <8 kPa rules out; ELF as an option", "VCTE ‏<8 كيلوباسكال ينفي؛ وELF خيار"), ("2–3 years", "2–3 سنوات")],
              [("Chinese 2024", "الصينية 2024"), "MAFLD", ("FIB-4 <1.3 / ≥2.67", "FIB-4 ‏<1.3 / ≥2.67"), ("VCTE <8 / >12 kPa (advanced fibrosis); <10 / >15 kPa (cirrhosis)", "VCTE ‏<8 / >12 (تليّف متقدّم)؛ <10 / >15 كيلوباسكال (تشمّع)"), "—"],
              [("Egyptian 2022", "المصرية 2022"), "MAFLD", ("FIB-4 1.3 / 2.67, NFS, or APRI 0.5 / 1.5", "FIB-4 ‏1.3 / 2.67، أو NFS، أو APRI ‏0.5 / 1.5"), ("Elastography; LSM >15 kPa suggests cirrhosis", "قياس المرونة؛ والصلابة >15 كيلوباسكال تشير إلى التشمّع"), "—"],
              [("Saudi consensus 2026", "الإجماع السعودي 2026"), "MASLD", ("Adapts international standards to Saudi practice. See the full text.", "يكيّف المعايير الدولية مع الممارسة السعودية. راجع النص الكامل."), "—", "—"],
             ]},
   "note": ("\"—\" means we have not summarised that point yet. It does not mean the guideline is silent.", "تعني \"—\" أننا لم نلخّص هذه النقطة بعد، ولا تعني أن الإرشادات لا تتناولها.")},
  {"h": ("Medicines", "الأدوية"),
   "table": {"head": [("Guideline", "الإرشادات"), ("Resmetirom", "الريسميتيروم"), ("Vitamin E", "فيتامين E"), ("Pioglitazone", "البيوغليتازون")],
             "rows": [
              ["EASL–EASD–EASO 2024", ("Consider where approved, in non-cirrhotic MASH with significant fibrosis (e.g. VCTE ≥10 kPa, MRE ≥5 kPa or ELF ≥9.8, without cirrhosis)", "يُنظر فيه حيث يُعتمد، في MASH دون تشمّع مع تليّف ملحوظ (مثل VCTE ‏≥10 أو MRE ‏≥5 كيلوباسكال أو ELF ‏≥9.8، دون تشمّع)"), ("Not as MASH treatment", "ليس علاجًا لـ MASH"), ("Safe; not as MASH treatment", "آمن؛ وليس علاجًا لـ MASH")],
              [("AASLD 2023 + 2024 update", "AASLD 2023 + تحديث 2024"), ("VCTE 8–15 kPa or MRE 3.1–4.4 kPa; not if VCTE >20 kPa", "VCTE ‏8–15 أو MRE ‏3.1–4.4 كيلوباسكال؛ ولا يُعطى إذا تجاوزت VCTE ‏20"), ("Consider in selected people", "يُنظر فيه لأشخاص مختارين"), ("Consider with type 2 diabetes", "يُنظر فيه مع السكري من النوع الثاني")],
              [("Global consensus 2025", "الإجماع العالمي 2025"), ("VCTE 8–<16 kPa; 16–20 kPa if a second test excludes cirrhosis; not if >20 kPa", "VCTE ‏8 إلى أقل من 16؛ و16–20 إذا نفى فحص ثانٍ التشمّع؛ ولا يُعطى فوق 20"), ("Only selected people without diabetes or cirrhosis", "فقط لأشخاص مختارين دون سكري أو تشمّع"), ("For diabetes, not as MASH treatment", "للسكري، وليس علاجًا لـ MASH")],
              ["APASL 2025", ("Improves inflammation and fibrosis; prescribe within a specialist team", "يحسّن الالتهاب والتليّف؛ ويوصف ضمن فريق متخصص"), ("May improve histology", "قد يحسّن النسيج"), ("Improves histology", "يحسّن النسيج")],
              [("Egyptian 2022", "المصرية 2022"), ("Before approval", "قبل اعتماده"), ("May improve histology", "قد يحسّن النسيج"), ("Improves histology", "يحسّن النسيج")],
             ]},
   "note": ("Summaries of each document's own words, checked against the full texts in October 2026.", "ملخصات لنصوص كل وثيقة، رُوجعت مقابل النصوص الكاملة في أكتوبر 2026.")},
 ],
 "see": ["fibrosis-pathway", "drugs", "middle-east"],
 "src": ["easl2024", "aasld2023", "resm2024", "global2025", "apasl2025", "china2024", "egypt2022", "saudi2026"],
},
{
 "slug": "middle-east", "group": "context",
 "title": {"en": "Fatty liver in Saudi Arabia and the Middle East", "ar": "الكبد الدهني في السعودية والشرق الأوسط"},
 "lead": {"en": "The numbers behind our mission: how common MASLD is in our region, and the gaps we need to close.",
          "ar": "الأرقام وراء رسالتنا: مدى انتشار MASLD في منطقتنا، والفجوات التي نحتاج إلى سدّها."},
 "key": [
  ("About 39% of people in the Middle East and North Africa have MASLD, and about 69% of people with type 2 diabetes.", "نحو 39% من سكان الشرق الأوسط وشمال أفريقيا لديهم MASLD، ونحو 69% من مرضى السكري من النوع الثاني."),
  ("In Saudi Arabia, estimated adult prevalence rose from 41% (2012) to 44% (2019).", "في السعودية ارتفع الانتشار المقدّر لدى البالغين من 41% (2012) إلى 44% (2019)."),
  ("Models predict cirrhosis and liver cancer from MASH in Saudi Arabia will roughly triple from 2018 to 2030.", "تتوقع النماذج أن تتضاعف حالات التشمّع وسرطان الكبد الناتجة عن MASH في السعودية نحو ثلاث مرات بين 2018 و2030."),
  ("Doctors' knowledge varies, and the region produces only about 3% of world MASLD research.", "تتفاوت معرفة الأطباء، ولا تُنتج المنطقة سوى نحو 3% من أبحاث MASLD في العالم."),
 ],
 "sections": [
  {"h": ("How common it is", "مدى الانتشار"),
   "table": {"head": [("Population", "الفئة"), ("Estimate", "التقدير"), ("Source", "المصدر")],
             "rows": [
              [("MENA, general population", "الشرق الأوسط وشمال أفريقيا، عامة السكان"), "39.4%", ("Meta-analysis, Younossi 2024", "تحليل تجميعي، Younossi 2024")],
              [("MENA, type 2 diabetes", "الشرق الأوسط وشمال أفريقيا، مرضى السكري"), "68.7%", ("Meta-analysis, Younossi 2024", "تحليل تجميعي، Younossi 2024")],
              [("MENA, trend", "الشرق الأوسط وشمال أفريقيا، الاتجاه"), ("35.4% (2008–16) → 46.2% (2017–20)", "35.4% (2008–2016) ← 46.2% (2017–2020)"), ("Younossi 2024", "Younossi 2024")],
              [("Saudi Arabia, adults", "السعودية، البالغون"), ("40.6% (2012) → 44.0% (2019)", "40.6% (2012) ← 44.0% (2019)"), ("Global Burden of Disease, Alqahtani 2024", "العبء العالمي للأمراض، Alqahtani 2024")],
              [("Saudi Arabia, all ages", "السعودية، جميع الأعمار"), ("28.0% → 33.1% (about 11.8 million people)", "28.0% ← 33.1% (نحو 11.8 مليون شخص)"), ("Alqahtani 2024", "Alqahtani 2024")],
             ]},
   "note": ("Modelled and pooled estimates. Local studies vary with the test used and the group studied.", "تقديرات مبنية على نماذج وتحليلات تجميعية، وتختلف الدراسات المحلية حسب الفحص المستخدم والفئة المدروسة.")},
  {"h": ("Where it is heading", "إلى أين يتجه"),
   "ul": [
    ("A Saudi model (2018–2030) predicts people with F0–F3 fibrosis doubling to 2.5 million, and cirrhosis plus liver cancer cases tripling to about 212,000.", "يتوقع نموذج سعودي (2018–2030) أن يتضاعف عدد المصابين بتليّف F0–F3 إلى 2.5 مليون، وأن تتضاعف حالات التشمّع وسرطان الكبد ثلاث مرات إلى نحو 212 ألفًا."),
    ("The same model estimated NASH-related costs at about 5.8% of national health spending in 2019.", "وقدّر النموذج نفسه تكلفة NASH بنحو 5.8% من الإنفاق الصحي الوطني في 2019."),
    ("In Saudi Arabia, MASLD is rising while hepatitis B is falling and hepatitis C is stable. Fatty liver is becoming the main chronic liver disease.", "في السعودية يرتفع MASLD بينما ينخفض التهاب الكبد B ويستقر C، فيصبح الكبد الدهني المرض الكبدي المزمن الرئيسي."),
    ("Across the region, high fasting blood glucose is the largest risk factor driving the MASLD burden.", "وعلى مستوى المنطقة، يُعد ارتفاع سكر الدم الصائم أكبر عامل خطر يقود عبء MASLD."),
   ]},
  {"h": ("What patients tell us", "ماذا يقول المرضى"),
   "p": [("In a survey of 804 Saudi patients, 79% called their condition \"fatty liver\" frequently or always, and only 17% had told family or friends about it. Few reported stigma, but 43% had missed or avoided a primary care visit because of their liver disease.",
          "في استبيان شمل 804 مرضى سعوديين، استخدم 79% عبارة \"الكبد الدهني\" غالبًا أو دائمًا، ولم يُخبر سوى 17% أسرهم أو أصدقاءهم. وقلّة أبلغوا عن وصمة، لكن 43% فوّتوا زيارة للرعاية الأولية أو تجنّبوها بسبب مرض الكبد."),
         ("This is why our patient pages say \"fatty liver\" (الكبد الدهني) first and explain MASLD second.", "لذلك تبدأ صفحات المرضى لدينا بعبارة \"الكبد الدهني\" ثم تشرح MASLD.")]},
  {"h": ("The gaps", "الفجوات"),
   "ul": [
    ("Knowledge: in a survey of 584 doctors from Saudi Arabia, Egypt and Türkiye, guideline adherence was 81–84% among specialists but 38–51% among non-specialists.", "المعرفة: في استبيان شمل 584 طبيبًا من السعودية ومصر وتركيا، بلغ الالتزام بالإرشادات 81–84% لدى المختصين و38–51% فقط لدى غيرهم."),
    ("Research: from 2014 to 2023, Arab countries produced 844 MASLD papers, about 3.3% of the world total, despite some of the highest prevalence.", "البحث: بين 2014 و2023 أنتجت الدول العربية 844 بحثًا عن MASLD، أي نحو 3.3% من الإجمالي العالمي، رغم أن انتشاره فيها من الأعلى."),
   ]},
 ],
 "see": ["guidelines-compared", "case-finding", "fibrosis-pathway"],
 "src": ["mena2024", "ksaburden2024", "sanai2021", "menagbd2025", "stigma2024", "menaknow2025", "arabbiblio2025", "saudi2026"],
},
]
